import json
from pathlib import Path
import shutil
import subprocess
import sys

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_score32_exact_local_temporal_reducer_gqa8_physical_harness import generate
from npu.rtlgen.gen_attention_score32_online_state_merge import (
    FACTORED_H33_L64_MUL_EXACT,
    LEGACY_MONOLITHIC_LUT_EXACT,
)


def _rtl_tools_available() -> bool:
    return bool(shutil.which("verilator") or Path("/oss-cad-suite/bin/verilator").exists())


def _yosys_available() -> bool:
    return bool(shutil.which("yosys") or Path("/oss-cad-suite/bin/yosys").exists())


def _tool(name: str) -> str:
    path = shutil.which(name)
    if path:
        return path
    fallback = Path("/oss-cad-suite/bin") / name
    if fallback.exists():
        return str(fallback)
    raise RuntimeError(f"required tool unavailable: {name}")


def _config_path(producers: int, mode: str) -> Path:
    return (
        REPO_ROOT
        / "runs"
        / "designs"
        / "npu_blocks"
        / f"attention_score32_exact_local_temporal_reducer_gqa8_physical_harness_p{producers}_{mode}_w8"
        / "config.json"
    )


def _load_config(producers: int, mode: str) -> dict[str, object]:
    return json.loads(_config_path(producers, mode).read_text(encoding="utf-8"))


@pytest.mark.parametrize("producers", [53, 54])
@pytest.mark.parametrize("mode", ["reducer", "source_only"])
@pytest.mark.skipif(not _rtl_tools_available(), reason="RTL tools unavailable")
def test_gqa8_physical_harness_manifest_and_verilator_lint(tmp_path: Path, producers: int, mode: str) -> None:
    config = _load_config(producers, mode)
    generate(config, tmp_path / "rtl")

    manifest = json.loads(
        (
            tmp_path / "rtl" / "attention_score32_exact_local_temporal_reducer_gqa8_physical_harness_manifest.json"
        ).read_text(encoding="utf-8")
    )
    top_text = (tmp_path / "rtl" / "top.v").read_text(encoding="utf-8")
    harness_text = top_text[
        top_text.index("// Generated by npu/rtlgen/gen_attention_score32_exact_local_temporal_reducer_gqa8_physical_harness.py") :
    ]

    assert manifest["producers"] == producers
    assert manifest["mode"] == mode
    assert manifest["waves"] == 8
    assert manifest["exp_scale_impl"] == LEGACY_MONOLITHIC_LUT_EXACT
    assert manifest["keep_hierarchy"] is False
    assert manifest["command_count"] == 2
    assert manifest["query_heads_per_group"] == 8
    assert manifest["head_group_bases"] == [0, 8]
    assert manifest["equivalence_hash"] is False
    assert manifest["top_pin_bits"] == 776
    assert manifest["source_traffic_contract"] == "shared_state_atomic_batch_stable_ready_valid"
    assert manifest["source_state_contract"] == "single_shared_held_lfsr_and_12bit_batch_counter"
    assert manifest["source_batch_contract"] == "all_leaf_valids_atomic_advance_on_all_leaf_handshakes"
    assert manifest["command_schedule_contract"] == "two_explicit_gqa8_head_groups_0_and_8_each_over_8_waves"
    assert manifest["head_mapping_contract"] == "head_major_slice_minor_source_order_with_explicit_head_ids"
    assert manifest["wave_terminal_contract"] == "advance_only_after_source_head_lane7_slice15_per_wave"
    assert manifest["per_leaf_payload_state"] is False
    assert manifest["linked_proposal_id"] == "prop_l1_decoder_attention_score32_local_temporal_reducer_gqa8_v1"
    assert manifest["caveats"] == [
        "structural_only",
        "nonlinear_ppa_delta_vs_functional_reducer_measurement",
    ]
    assert "output wire [327:0] final_value," in harness_text
    assert "source_fold_q <=" in harness_text
    assert "reg [31:0] shared_lfsr_q;" in harness_text
    assert "reg [11:0] shared_beat_count_q;" in harness_text
    assert "wire batch_command_index_w = shared_beat_count_q[10];" in harness_text
    assert "wire [2:0] batch_wave_index_w = shared_beat_count_q[9:7];" in harness_text
    assert "wire [2:0] batch_head_lane_w = shared_beat_count_q[6:4];" in harness_text
    assert "wire [SLICE_BITS-1:0] batch_slice_index_w = shared_beat_count_q[3:0];" in harness_text
    assert "leaf_lfsr_q" not in harness_text
    assert "leaf_beat_count_q" not in harness_text
    assert "leaf_value_q" not in harness_text
    assert "reg [31:0] shared_lfsr_q [0:PRODUCERS-1]" not in harness_text
    assert "reg [327:0]" not in harness_text.replace("reg [327:0] final_value_q;", "")
    assert harness_text.count("assign leaf_valid_w[") == producers
    for index in range(producers):
        assert f"assign leaf_valid_w[{index}] = atomic_batch_valid_w;" in harness_text
        assert f"{{24'd0, leaf_value_w[{index * 328 + 320} +: 8]}}" in harness_text
    if mode == "reducer":
        assert manifest["submodule_manifests"]["gqa8_reducer"]["producers"] == producers
        assert manifest["submodule_manifests"]["gqa8_reducer"]["exp_scale_impl"] == LEGACY_MONOLITHIC_LUT_EXACT
        assert manifest["submodule_manifests"]["gqa8_reducer"]["keep_hierarchy"] is False
        assert "u_reducer" in top_text
        assert "(reducer_out_command_id_w == 16'h7b01)" in harness_text
        assert "(reducer_out_head_id_w == 5'd15)" in harness_text
        assert "(reducer_out_slice_w == 4'd15);" in harness_text
    else:
        assert manifest["submodule_manifests"]["gqa8_reducer"] is None
        assert "if (shared_beat_count_q == 12'd2047) begin" in top_text

    lint = subprocess.run(
        [
            _tool("verilator"),
            "--lint-only",
            "-Wno-WIDTHEXPAND",
            "-Wno-WIDTHTRUNC",
            "--top-module",
            str(config["top_name"]),
            str(tmp_path / "rtl" / "top.v"),
        ],
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert lint.returncode == 0, lint.stderr


@pytest.mark.skipif(not _rtl_tools_available(), reason="RTL tools unavailable")
def test_gqa8_physical_harness_factored_exp_scale_propagates_to_reducer_and_temporal_merge(tmp_path: Path) -> None:
    config = _load_config(53, "reducer")
    config["attention_score32_exact_local_temporal_reducer_gqa8_physical_harness"][
        "exp_scale_impl"
    ] = FACTORED_H33_L64_MUL_EXACT
    generate(config, tmp_path / "rtl")

    manifest = json.loads(
        (
            tmp_path / "rtl" / "attention_score32_exact_local_temporal_reducer_gqa8_physical_harness_manifest.json"
        ).read_text(encoding="utf-8")
    )
    reducer_manifest = manifest["submodule_manifests"]["gqa8_reducer"]
    assert manifest["exp_scale_impl"] == FACTORED_H33_L64_MUL_EXACT
    assert manifest["keep_hierarchy"] is False
    assert reducer_manifest["exp_scale_impl"] == FACTORED_H33_L64_MUL_EXACT
    assert reducer_manifest["keep_hierarchy"] is False
    assert reducer_manifest["submodule_manifests"]["local_reducer"]["exp_scale_impl"] == FACTORED_H33_L64_MUL_EXACT
    assert (
        reducer_manifest["submodule_manifests"]["local_reducer"]["submodule_manifests"]["pair_merge"]["exp_scale_impl"]
        == FACTORED_H33_L64_MUL_EXACT
    )
    assert reducer_manifest["submodule_manifests"]["temporal_merge"]["exp_scale_impl"] == FACTORED_H33_L64_MUL_EXACT

    rtl = (tmp_path / "rtl" / "top.v").read_text(encoding="utf-8")
    assert "case (bucket)" not in rtl
    assert rtl.count("case (bucket_hi)") == 2
    assert rtl.count("case (bucket_lo)") == 2
    assert "33'd4096: exp_lut = 24'd" not in rtl


@pytest.mark.skipif(not _yosys_available(), reason="yosys unavailable")
def test_gqa8_physical_harness_keep_hierarchy_propagates_and_survives_flatten(tmp_path: Path) -> None:
    config = _load_config(53, "reducer")
    body = config["attention_score32_exact_local_temporal_reducer_gqa8_physical_harness"]
    body["exp_scale_impl"] = FACTORED_H33_L64_MUL_EXACT
    body["keep_hierarchy"] = True
    generate(config, tmp_path / "rtl")

    manifest = json.loads(
        (
            tmp_path / "rtl" / "attention_score32_exact_local_temporal_reducer_gqa8_physical_harness_manifest.json"
        ).read_text(encoding="utf-8")
    )
    reducer_manifest = manifest["submodule_manifests"]["gqa8_reducer"]
    assert manifest["keep_hierarchy"] is True
    assert reducer_manifest["keep_hierarchy"] is True
    assert reducer_manifest["submodule_manifests"]["local_reducer"]["keep_hierarchy"] is True
    assert (
        reducer_manifest["submodule_manifests"]["local_reducer"]["submodule_manifests"]["pair_merge"]["keep_hierarchy"]
        is True
    )
    assert reducer_manifest["submodule_manifests"]["temporal_merge"]["keep_hierarchy"] is True

    rtl = (tmp_path / "rtl" / "top.v").read_text(encoding="utf-8")
    assert rtl.count("(* keep_hierarchy = 1 *)") >= 2

    flattened_json = tmp_path / "flattened.json"
    subprocess.run(
        [
            _tool("yosys"),
            "-p",
            (
                f"read_verilog -sv {tmp_path / 'rtl' / 'top.v'}; "
                f"hierarchy -check -top {config['top_name']}; "
                "proc; "
                "flatten; "
                f"write_json {flattened_json}"
            ),
        ],
        capture_output=True,
        text=True,
        check=True,
        timeout=300,
    )
    design = json.loads(flattened_json.read_text(encoding="utf-8"))
    cell_types = {cell["type"] for cell in design["modules"][str(config["top_name"])]["cells"].values()}
    assert f"{config['top_name']}__reducer__temporal_merge" in cell_types
    assert f"{config['top_name']}__reducer__local_reducer__pair_node" in cell_types


def test_gqa8_physical_harness_rejects_invalid_mode(tmp_path: Path) -> None:
    config = _load_config(53, "reducer")
    config["attention_score32_exact_local_temporal_reducer_gqa8_physical_harness"]["mode"] = "broken"
    with pytest.raises(SystemExit, match="mode must be reducer or source_only"):
        generate(config, tmp_path / "rtl")


def test_gqa8_physical_harness_rejects_invalid_waves(tmp_path: Path) -> None:
    config = _load_config(53, "reducer")
    config["attention_score32_exact_local_temporal_reducer_gqa8_physical_harness"]["waves"] = 7
    with pytest.raises(SystemExit, match="waves must remain fixed at 8"):
        generate(config, tmp_path / "rtl")
