/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "yosys_mult8u_booth_yosys.v:1.1-8.10" *)
module yosys_mult8u_booth(multiplicand, multiplier, product);
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [15:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [15:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [15:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [15:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [15:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [15:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [15:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [15:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [15:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [15:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:214.23-214.24" *)
  wire [15:0] _040_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _041_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _042_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _043_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _044_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _045_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _046_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _047_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _048_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _049_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _050_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _051_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _052_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _053_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _054_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _055_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _056_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _057_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _058_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _059_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _060_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _061_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _062_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _063_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _064_;
  (* src = "yosys_mult8u_booth_yosys.v:2.15-2.27" *)
  input [7:0] multiplicand;
  wire [7:0] multiplicand;
  (* src = "yosys_mult8u_booth_yosys.v:3.15-3.25" *)
  input [7:0] multiplier;
  wire [7:0] multiplier;
  (* src = "yosys_mult8u_booth_yosys.v:4.17-4.24" *)
  output [15:0] product;
  wire [15:0] product;
  assign _032_[1] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[2] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[3] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[4] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[5] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[6] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[7] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _032_[8] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[1];
  assign product[0] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[1] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[2] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[3] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[4] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[5] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[6] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _033_[7] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _034_[2] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _034_[3] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _034_[4] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _034_[5] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _034_[6] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _034_[7] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _034_[8] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _008_[9] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _000_[3] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[4] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[5] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[6] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[7] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[8] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[9] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _000_[10] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _001_[4] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[5] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[6] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[7] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[8] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[9] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[10] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _001_[11] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[4];
  assign _002_[5] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[6] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[7] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[8] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[9] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[10] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[11] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _002_[12] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[5];
  assign _015_[6] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[7] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[8] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[9] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[10] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[11] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[12] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _015_[13] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[6];
  assign _016_[7] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[8] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[9] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[10] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[11] = multiplicand[4] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[12] = multiplicand[5] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[13] = multiplicand[6] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _016_[14] = multiplicand[7] &(* src = {0{1'b0}} *)  multiplier[7];
  assign _009_[3] = _036_[2] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _037_[2];
  assign _009_[4] = _036_[3] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _037_[3];
  assign _009_[5] = _036_[4] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _037_[4];
  assign _009_[6] = _036_[5] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _037_[5];
  assign _009_[7] = _036_[6] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _037_[6];
  assign _009_[8] = _036_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _037_[7];
  assign _008_[2] = _035_[2] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[2];
  assign _008_[3] = _035_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[3];
  assign _008_[4] = _035_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[4];
  assign _008_[5] = _035_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[5];
  assign _008_[6] = _035_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[6];
  assign _008_[7] = _035_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[7];
  assign _008_[8] = _032_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _034_[8];
  assign _037_[2] = _034_[2] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _035_[2];
  assign _037_[3] = _034_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _035_[3];
  assign _037_[4] = _034_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _035_[4];
  assign _037_[5] = _034_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _035_[5];
  assign _037_[6] = _034_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _035_[6];
  assign _037_[7] = _034_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _035_[7];
  assign _009_[9] = _034_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _032_[8];
  assign _009_[2] = _032_[1] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[1];
  assign _036_[2] = _032_[2] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[2];
  assign _036_[3] = _032_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[3];
  assign _036_[4] = _032_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[4];
  assign _036_[5] = _032_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[5];
  assign _036_[6] = _032_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[6];
  assign _036_[7] = _032_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _033_[7];
  assign product[1] = _032_[1] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[1];
  assign _035_[2] = _032_[2] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[2];
  assign _035_[3] = _032_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[3];
  assign _035_[4] = _032_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[4];
  assign _035_[5] = _032_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[5];
  assign _035_[6] = _032_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[6];
  assign _035_[7] = _032_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _033_[7];
  assign _003_[5] = _006_[5] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[5];
  assign _003_[6] = _006_[6] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[6];
  assign _003_[7] = _006_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[7];
  assign _003_[8] = _006_[8] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[8];
  assign _003_[9] = _006_[9] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[9];
  assign _003_[10] = _006_[10] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[10];
  assign _004_[5] = _005_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[5];
  assign _004_[6] = _005_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[6];
  assign _004_[7] = _005_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[7];
  assign _004_[8] = _005_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[8];
  assign _004_[9] = _005_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[9];
  assign _004_[10] = _005_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[10];
  assign _004_[11] = _001_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[11];
  assign _007_[5] = _002_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[5];
  assign _007_[6] = _002_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[6];
  assign _007_[7] = _002_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[7];
  assign _007_[8] = _002_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[8];
  assign _007_[9] = _002_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[9];
  assign _007_[10] = _002_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[10];
  assign _003_[11] = _002_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _001_[11];
  assign _003_[4] = _000_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[4];
  assign _006_[5] = _000_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[5];
  assign _006_[6] = _000_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[6];
  assign _006_[7] = _000_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[7];
  assign _006_[8] = _000_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[8];
  assign _006_[9] = _000_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[9];
  assign _006_[10] = _000_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[10];
  assign _004_[4] = _000_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[4];
  assign _005_[5] = _000_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[5];
  assign _005_[6] = _000_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[6];
  assign _005_[7] = _000_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[7];
  assign _005_[8] = _000_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[8];
  assign _005_[9] = _000_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[9];
  assign _005_[10] = _000_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[10];
  assign _010_[3] = _013_[3] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[3];
  assign _010_[4] = _013_[4] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[4];
  assign _010_[5] = _013_[5] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[5];
  assign _010_[6] = _013_[6] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[6];
  assign _010_[7] = _013_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[7];
  assign _010_[8] = _013_[8] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[8];
  assign _010_[9] = _013_[9] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _014_[9];
  assign _011_[3] = _012_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _000_[3];
  assign _011_[4] = _012_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_[4];
  assign _011_[5] = _012_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_[5];
  assign _011_[6] = _012_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_[6];
  assign _011_[7] = _012_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_[7];
  assign _011_[8] = _012_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_[8];
  assign _011_[9] = _012_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_[9];
  assign _014_[3] = _000_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[3];
  assign _014_[4] = _004_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[4];
  assign _014_[5] = _004_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[5];
  assign _014_[6] = _004_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[6];
  assign _014_[7] = _004_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[7];
  assign _014_[8] = _004_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[8];
  assign _014_[9] = _004_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _012_[9];
  assign _010_[2] = _008_[2] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[2];
  assign _013_[3] = _008_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[3];
  assign _013_[4] = _008_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[4];
  assign _013_[5] = _008_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[5];
  assign _013_[6] = _008_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[6];
  assign _013_[7] = _008_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[7];
  assign _013_[8] = _008_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[8];
  assign _013_[9] = _008_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[9];
  assign product[2] = _008_[2] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[2];
  assign _012_[3] = _008_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[3];
  assign _012_[4] = _008_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[4];
  assign _012_[5] = _008_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[5];
  assign _012_[6] = _008_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[6];
  assign _012_[7] = _008_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[7];
  assign _012_[8] = _008_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[8];
  assign _012_[9] = _008_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[9];
  assign _017_[7] = _020_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _021_[7];
  assign _017_[8] = _020_[8] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _021_[8];
  assign _017_[9] = _020_[9] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _021_[9];
  assign _017_[10] = _020_[10] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _021_[10];
  assign _017_[11] = _020_[11] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _021_[11];
  assign _017_[12] = _020_[12] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _021_[12];
  assign _018_[7] = _019_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[7];
  assign _018_[8] = _019_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[8];
  assign _018_[9] = _019_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[9];
  assign _018_[10] = _019_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[10];
  assign _018_[11] = _019_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[11];
  assign _018_[12] = _019_[12] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[12];
  assign _018_[13] = _015_[13] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _016_[13];
  assign _021_[7] = _016_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _019_[7];
  assign _021_[8] = _016_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _019_[8];
  assign _021_[9] = _016_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _019_[9];
  assign _021_[10] = _016_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _019_[10];
  assign _021_[11] = _016_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _019_[11];
  assign _021_[12] = _016_[12] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _019_[12];
  assign _017_[13] = _016_[13] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _015_[13];
  assign _017_[6] = _003_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[6];
  assign _020_[7] = _003_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[7];
  assign _020_[8] = _003_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[8];
  assign _020_[9] = _003_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[9];
  assign _020_[10] = _003_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[10];
  assign _020_[11] = _003_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[11];
  assign _020_[12] = _003_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _015_[12];
  assign _018_[6] = _003_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[6];
  assign _019_[7] = _003_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[7];
  assign _019_[8] = _003_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[8];
  assign _019_[9] = _003_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[9];
  assign _019_[10] = _003_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[10];
  assign _019_[11] = _003_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[11];
  assign _019_[12] = _003_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _015_[12];
  assign _022_[5] = _025_[5] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _026_[5];
  assign _022_[6] = _025_[6] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _026_[6];
  assign _022_[7] = _025_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _026_[7];
  assign _022_[8] = _025_[8] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _026_[8];
  assign _022_[9] = _025_[9] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _026_[9];
  assign _022_[10] = _025_[10] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _026_[10];
  assign _023_[5] = _024_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _003_[4];
  assign _023_[6] = _024_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[6];
  assign _023_[7] = _024_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[7];
  assign _023_[8] = _024_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[8];
  assign _023_[9] = _024_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[9];
  assign _023_[10] = _024_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[10];
  assign _023_[11] = _004_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[11];
  assign _023_[12] = _002_[12] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _018_[12];
  assign _026_[5] = _003_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _024_[5];
  assign _026_[6] = _018_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _024_[6];
  assign _026_[7] = _018_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _024_[7];
  assign _026_[8] = _018_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _024_[8];
  assign _026_[9] = _018_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _024_[9];
  assign _026_[10] = _018_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _024_[10];
  assign _022_[11] = _018_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _004_[11];
  assign _022_[12] = _018_[12] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _002_[12];
  assign _022_[3] = _011_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[2];
  assign _022_[4] = _011_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[3];
  assign _025_[5] = _011_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[4];
  assign _025_[6] = _011_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[5];
  assign _025_[7] = _011_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[6];
  assign _025_[8] = _011_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[7];
  assign _025_[9] = _011_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[8];
  assign _025_[10] = _004_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _010_[9];
  assign product[3] = _011_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[2];
  assign _023_[4] = _011_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[3];
  assign _024_[5] = _011_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[4];
  assign _024_[6] = _011_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[5];
  assign _024_[7] = _011_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[6];
  assign _024_[8] = _011_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[7];
  assign _024_[9] = _011_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[8];
  assign _024_[10] = _004_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _010_[9];
  assign _027_[7] = _030_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[7];
  assign _027_[8] = _030_[8] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[8];
  assign _027_[9] = _030_[9] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[9];
  assign _027_[10] = _030_[10] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[10];
  assign _027_[11] = _030_[11] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[11];
  assign _027_[12] = _030_[12] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[12];
  assign _027_[13] = _030_[13] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _031_[13];
  assign _028_[7] = _029_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[6];
  assign _028_[8] = _029_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[7];
  assign _028_[9] = _029_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[8];
  assign _028_[10] = _029_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[9];
  assign _028_[11] = _029_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[10];
  assign _028_[12] = _029_[12] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[11];
  assign _028_[13] = _029_[13] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[12];
  assign _028_[14] = _016_[14] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _017_[13];
  assign _031_[7] = _017_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[7];
  assign _031_[8] = _017_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[8];
  assign _031_[9] = _017_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[9];
  assign _031_[10] = _017_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[10];
  assign _031_[11] = _017_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[11];
  assign _031_[12] = _017_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[12];
  assign _031_[13] = _017_[12] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _029_[13];
  assign _027_[14] = _017_[13] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _016_[14];
  assign _027_[4] = _023_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[3];
  assign _027_[5] = _023_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[4];
  assign _027_[6] = _023_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[5];
  assign _030_[7] = _023_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[6];
  assign _030_[8] = _023_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[7];
  assign _030_[9] = _023_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[8];
  assign _030_[10] = _023_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[9];
  assign _030_[11] = _023_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[10];
  assign _030_[12] = _023_[12] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[11];
  assign _030_[13] = _018_[13] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _022_[12];
  assign product[4] = _023_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[3];
  assign _028_[5] = _023_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[4];
  assign _028_[6] = _023_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[5];
  assign _029_[7] = _023_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[6];
  assign _029_[8] = _023_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[7];
  assign _029_[9] = _023_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[8];
  assign _029_[10] = _023_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[9];
  assign _029_[11] = _023_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[10];
  assign _029_[12] = _023_[12] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[11];
  assign _029_[13] = _018_[13] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _022_[12];
  assign product[6] = _039_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[5];
  assign product[7] = _039_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[6];
  assign product[8] = _039_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[7];
  assign product[9] = _039_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[8];
  assign product[10] = _039_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[9];
  assign product[11] = _039_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[10];
  assign product[12] = _039_[12] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[11];
  assign product[13] = _039_[13] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[12];
  assign product[14] = _039_[14] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[13];
  assign product[15] = _027_[14] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _038_[14];
  assign product[5] = _028_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[4];
  assign _039_[6] = _028_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[5];
  assign _039_[7] = _028_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[6];
  assign _039_[8] = _028_[8] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[7];
  assign _039_[9] = _028_[9] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[8];
  assign _039_[10] = _028_[10] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[9];
  assign _039_[11] = _028_[11] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[10];
  assign _039_[12] = _028_[12] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[11];
  assign _039_[13] = _028_[13] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[12];
  assign _039_[14] = _028_[14] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _027_[13];
  assign _038_[5] = _028_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[4];
  assign _040_[6] = _028_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[5];
  assign _040_[7] = _028_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[6];
  assign _040_[8] = _028_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[7];
  assign _040_[9] = _028_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[8];
  assign _040_[10] = _028_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[9];
  assign _040_[11] = _028_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[10];
  assign _040_[12] = _028_[12] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[11];
  assign _040_[13] = _028_[13] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[12];
  assign _040_[14] = _028_[14] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _027_[13];
  assign _041_ = _039_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _040_[6];
  assign _042_ = _039_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _040_[8];
  assign _043_ = _039_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _040_[10];
  assign _044_ = _039_[13] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _040_[12];
  assign _045_ = _047_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _038_[5];
  assign _046_ = _049_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _061_;
  assign _047_ = _039_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _039_[6];
  assign _048_ = _039_[9] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _039_[8];
  assign _049_ = _039_[11] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _039_[10];
  assign _050_ = _039_[13] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _039_[12];
  assign _051_ = _049_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)  _048_;
  assign _052_ = _051_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _053_ = _048_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _054_ = _050_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _055_ = _039_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[5];
  assign _056_ = _039_[8] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[7];
  assign _057_ = _039_[10] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[9];
  assign _058_ = _039_[12] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[11];
  assign _059_ = _039_[14] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _038_[13];
  assign _060_ = _040_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _041_;
  assign _061_ = _040_[9] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _042_;
  assign _062_ = _040_[11] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _043_;
  assign _063_ = _040_[13] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _044_;
  assign _038_[7] = _060_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _045_;
  assign _064_ = _062_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _046_;
  assign _038_[11] = _064_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _052_;
  assign _038_[9] = _061_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _053_;
  assign _038_[13] = _063_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _054_;
  assign _038_[6] = _040_[6] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _055_;
  assign _038_[8] = _040_[8] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _056_;
  assign _038_[10] = _040_[10] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _057_;
  assign _038_[12] = _040_[12] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _058_;
  assign _038_[14] = _040_[14] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _059_;
  assign { _000_[15:11], _000_[2:0] } = 8'h00;
  assign { _001_[15:12], _001_[3:0] } = 8'h00;
  assign { _002_[15:13], _002_[4:0] } = 8'h00;
  assign { _003_[15:12], _003_[3:0] } = 8'h00;
  assign { _004_[15:12], _004_[3:0] } = { 3'h0, _002_[12], _000_[3], 3'h0 };
  assign { _005_[15:11], _005_[4:0] } = { 4'h0, _001_[11], _004_[4], _000_[3], 3'h0 };
  assign { _006_[15:11], _006_[4:0] } = { 5'h00, _003_[4], 4'h0 };
  assign { _007_[15:11], _007_[4:0] } = { 4'h0, _003_[11], 5'h00 };
  assign { _008_[15:10], _008_[1:0] } = { 6'h00, product[1:0] };
  assign { _009_[15:10], _009_[1:0] } = 8'h00;
  assign { _010_[15:10], _010_[1:0] } = 8'h00;
  assign { _011_[15:10], _011_[2:0] } = { 3'h0, _002_[12], _004_[11:10], product[2:0] };
  assign { _012_[15:10], _012_[2:0] } = { 6'h00, product[2:0] };
  assign { _013_[15:10], _013_[2:0] } = { 6'h00, _010_[2], 2'h0 };
  assign { _014_[15:10], _014_[2:0] } = 9'h000;
  assign { _015_[15:14], _015_[5:0] } = 8'h00;
  assign { _016_[15], _016_[6:0] } = 8'h00;
  assign { _017_[15:14], _017_[5:0] } = 8'h00;
  assign { _018_[15:14], _018_[5:0] } = { 1'h0, _016_[14], _003_[4], 5'h00 };
  assign { _019_[15:13], _019_[6:0] } = { 2'h0, _015_[13], _018_[6], _003_[4], 5'h00 };
  assign { _020_[15:13], _020_[6:0] } = { 3'h0, _017_[6], 6'h00 };
  assign { _021_[15:13], _021_[6:0] } = { 2'h0, _017_[13], 7'h00 };
  assign { _022_[15:13], _022_[2:0] } = 6'h00;
  assign { _023_[15:13], _023_[3:0] } = { 1'h0, _016_[14], _018_[13], product[3:0] };
  assign { _024_[15:11], _024_[4:0] } = { 3'h0, _002_[12], _004_[11], _023_[4], product[3:0] };
  assign { _025_[15:11], _025_[4:0] } = { 5'h00, _022_[4:3], 3'h0 };
  assign { _026_[15:11], _026_[4:0] } = { 3'h0, _022_[12:11], 5'h00 };
  assign { _027_[15], _027_[3:0] } = 5'h00;
  assign { _028_[15], _028_[4:0] } = { 1'h0, product[4:0] };
  assign { _029_[15:14], _029_[6:0] } = { 1'h0, _016_[14], _028_[6:5], product[4:0] };
  assign { _030_[15:14], _030_[6:0] } = { 2'h0, _027_[6:4], 4'h0 };
  assign { _031_[15:14], _031_[6:0] } = { 1'h0, _027_[14], 7'h00 };
  assign { _032_[15:9], _032_[0] } = 8'h00;
  assign { _033_[15:8], _033_[0] } = { 8'h00, product[0] };
  assign { _034_[15:9], _034_[1:0] } = { 6'h00, _008_[9], 2'h0 };
  assign { _035_[15:8], _035_[1:0] } = { 7'h00, _032_[8], product[1:0] };
  assign { _036_[15:8], _036_[1:0] } = { 8'h00, _009_[2], 1'h0 };
  assign { _037_[15:8], _037_[1:0] } = { 7'h00, _009_[9], 2'h0 };
  assign _038_[4:0] = 5'h00;
  assign { _039_[15], _039_[5:0] } = { _027_[14], product[5:0] };
  assign { _040_[15], _040_[5:0] } = { 1'h0, _038_[5], 5'h00 };
endmodule
