#!/usr/bin/env python3
import argparse
import json
import math
import subprocess
import sys
from pathlib import Path


TOP_TEMPLATE = """\
{compute_modules}// Auto-generated by npu/rtlgen/gen.py (v0.1)
module {top_name} (
    input  wire                  clk,
    input  wire                  rst_n,
    input  wire [{mmio_addr_width_minus1}:0] mmio_addr,
    input  wire                  mmio_we,
    input  wire [{data_width_minus1}:0] mmio_wdata,
    output reg  [{data_width_minus1}:0] mmio_rdata,
    output reg                   irq{dma_ports}{cq_mem_ports}{axi_ports}
);

  // Minimal stub: MMIO register block with queue bookkeeping.
  reg [{data_width_minus1}:0] version;
  reg [{data_width_minus1}:0] capabilities;
  reg [{data_width_minus1}:0] status;
  reg [{data_width_minus1}:0] control;
  reg [{data_width_minus1}:0] irq_status;
  reg [{data_width_minus1}:0] irq_enable;
  reg [{data_width_minus1}:0] cq_base_lo;
  reg [{data_width_minus1}:0] cq_base_hi;
  reg [{data_width_minus1}:0] cq_size;
  reg [{data_width_minus1}:0] cq_head;
  reg [{data_width_minus1}:0] cq_tail;
  reg [{data_width_minus1}:0] cq_count;
  reg [255:0] cq_word0;
  reg [7:0]  cq_word0_size;
  reg        cq_pending_ext;
  reg [7:0] last_opcode;
  reg [31:0] last_tag;
  reg [{dma_addr_width_minus1}:0] last_src;
  reg [{dma_addr_width_minus1}:0] last_dst;
  reg [31:0] last_size;
  reg [63:0] last_op_uid;
  reg [{dma_addr_width_minus1}:0] dma_src;
  reg [{dma_addr_width_minus1}:0] dma_dst;
  reg [31:0] dma_size;
  reg        cq_stage_valid;
  reg        dma_pending;
  reg [2:0]  dma_state;
  reg        gemm_pending;
  reg [1:0]  gemm_slot_valid;
  reg [1:0]  gemm_slot_done;
  reg [31:0] gemm_slot_cycles0;
  reg [31:0] gemm_slot_cycles1;
  reg [63:0] gemm_slot_uid0;
  reg [63:0] gemm_slot_uid1;
  reg [{dma_addr_width_minus1}:0] gemm_slot_src0;
  reg [{dma_addr_width_minus1}:0] gemm_slot_src1;
  reg [{dma_addr_width_minus1}:0] gemm_slot_dst0;
  reg [{dma_addr_width_minus1}:0] gemm_slot_dst1;
  reg [31:0] gemm_slot_size0;
  reg [31:0] gemm_slot_size1;
  reg [8:0]  gemm_slot_beats0;
  reg [8:0]  gemm_slot_beats1;
  reg [7:0]  gemm_slot_arlen0;
  reg [7:0]  gemm_slot_arlen1;
  reg        gemm_dma_sel;
  reg        gemm_done_pulse;
  reg [63:0] gemm_done_uid;
{compute_state_regs}
  reg [{axi_data_width_minus1}:0] dma_buf;
  reg [8:0]  dma_beats;
  reg [8:0]  dma_beats_left;
  reg [7:0]  dma_arlen;
  reg [{axi_data_width_minus1}:0] dma_buf_mem [0:255];
  reg [7:0]  dma_rd_idx;
  reg [7:0]  dma_wr_idx;
  reg [{data_width_minus1}:0] error_code;

  localparam STATUS_IDLE = 32'h1;
  localparam STATUS_BUSY = 32'h2;
  localparam STATUS_ERR  = 32'h4;

  localparam integer AXI_BEAT_BYTES = {axi_beat_bytes};

  localparam IRQ_CQ_EMPTY    = 0;
  localparam IRQ_EVENT       = 1;
  localparam IRQ_ERROR       = 2;

  // MMIO offsets (bytes)
  `include "mmio_map.vh"
{compute_instances}

  always @(*) begin
    case (mmio_addr)
      OFF_VERSION:    mmio_rdata = version;
      OFF_CAPS:       mmio_rdata = capabilities;
      OFF_STATUS:     mmio_rdata = status;
      OFF_CONTROL:    mmio_rdata = control;
      OFF_IRQ_STATUS: mmio_rdata = irq_status;
      OFF_IRQ_ENABLE: mmio_rdata = irq_enable;
      OFF_CQ_BASE_LO: mmio_rdata = cq_base_lo;
      OFF_CQ_BASE_HI: mmio_rdata = cq_base_hi;
      OFF_CQ_SIZE:    mmio_rdata = cq_size;
      OFF_CQ_HEAD:    mmio_rdata = cq_head;
      OFF_CQ_TAIL:    mmio_rdata = cq_tail;
      OFF_ERROR_CODE: mmio_rdata = error_code;
      default: mmio_rdata = 0;
    endcase
  end

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      version <= 32'h0001_0001;
      capabilities <= 32'h0000_0133; // DMA_COPY/STRIDED/GATHER/SCATTER + GEMM/VEC/SOFTMAX + EVENT_IRQ
      status <= STATUS_IDLE;
      control <= 0;
      irq_status <= 0;
      irq_enable <= 0;
      cq_base_lo <= 0;
      cq_base_hi <= 0;
      cq_size <= 0;
      cq_head <= 0;
      cq_tail <= 0;
      cq_count <= 0;
      cq_word0 <= 0;
      cq_word0_size <= 0;
      cq_pending_ext <= 0;
      error_code <= 0;
      irq <= 0;
      last_opcode <= 0;
      last_tag <= 0;
      last_src <= 0;
      last_dst <= 0;
      last_size <= 0;
      last_op_uid <= 0;
      dma_src <= 0;
      dma_dst <= 0;
      dma_size <= 0;
      cq_stage_valid <= 0;
      dma_pending <= 0;
      dma_state <= 0;
      gemm_pending <= 0;
      gemm_slot_valid <= 0;
      gemm_slot_done <= 0;
      gemm_slot_cycles0 <= 0;
      gemm_slot_cycles1 <= 0;
      gemm_slot_uid0 <= 0;
      gemm_slot_uid1 <= 0;
      gemm_slot_src0 <= 0;
      gemm_slot_src1 <= 0;
      gemm_slot_dst0 <= 0;
      gemm_slot_dst1 <= 0;
      gemm_slot_size0 <= 0;
      gemm_slot_size1 <= 0;
      gemm_slot_beats0 <= 0;
      gemm_slot_beats1 <= 0;
      gemm_slot_arlen0 <= 0;
      gemm_slot_arlen1 <= 0;
      gemm_dma_sel <= 0;
      gemm_done_pulse <= 0;
      gemm_done_uid <= 0;
{compute_reset}
      dma_buf <= 0;
      dma_beats <= 0;
      dma_beats_left <= 0;
      dma_arlen <= 0;
      dma_rd_idx <= 0;
      dma_wr_idx <= 0;
{dma_reset}
{axi_reset}
    end else begin
      // Default: clear level IRQ unless status bit set
      irq <= |(irq_status & irq_enable);
{dma_handshake}
{gemm_update}
{axi_defaults}
{axi_fsm}

      if (mmio_we) begin
        case (mmio_addr)
          OFF_CONTROL: control <= mmio_wdata;
          OFF_IRQ_STATUS: irq_status <= irq_status & ~mmio_wdata; // W1C
          OFF_IRQ_ENABLE: irq_enable <= mmio_wdata;
          OFF_CQ_BASE_LO: cq_base_lo <= mmio_wdata;
          OFF_CQ_BASE_HI: cq_base_hi <= mmio_wdata;
          OFF_CQ_SIZE:    cq_size <= mmio_wdata;
          OFF_CQ_TAIL:    cq_tail <= mmio_wdata;
          OFF_DOORBELL: begin
            // Minimal behavior: consume all queued descriptors.
            cq_count <= ((cq_tail - cq_head) >> 5);
            if (((cq_tail - cq_head) >> 5) == 0) begin
              status <= STATUS_IDLE;
              irq_status[IRQ_CQ_EMPTY] <= 1'b1;
            end else begin
              status <= STATUS_BUSY;
            end
{dma_kick}
          end
          default: begin end
        endcase
      end

{cq_block}

      if (error_code != 0) begin
        status <= STATUS_ERR;
        irq_status[IRQ_ERROR] <= 1'b1;
      end else if (!(mmio_we && mmio_addr == OFF_DOORBELL)) begin
        if ((cq_count != 0) || cq_stage_valid || dma_pending || (gemm_slot_valid != 2'b00)) begin
          status <= STATUS_BUSY;
        end else begin
          status <= STATUS_IDLE;
        end
      end
    end
  end

endmodule
"""

SRAM_1R1W_MODEL = """\
// Simple 1R1W SRAM model (behavioral, for simulation)
module sram_1r1w #(
    parameter ADDR_WIDTH = 10,
    parameter DATA_WIDTH = 32,
    parameter READ_LATENCY = 1,
    parameter BYTE_ENABLE = 1
) (
    input  wire                  clk,
    input  wire                  we,
    input  wire [ADDR_WIDTH-1:0] waddr,
    input  wire [DATA_WIDTH-1:0] wdata,
    input  wire [(DATA_WIDTH/8)-1:0] wstrb,
    input  wire                  re,
    input  wire [ADDR_WIDTH-1:0] raddr,
    output reg  [DATA_WIDTH-1:0] rdata
);
  reg [DATA_WIDTH-1:0] mem [0:(1<<ADDR_WIDTH)-1];
  reg [DATA_WIDTH-1:0] rdata_pipe [0:READ_LATENCY-1];
  integer i;

  always @(posedge clk) begin
    if (we) begin
      if (BYTE_ENABLE) begin
        for (i = 0; i < (DATA_WIDTH/8); i = i + 1) begin
          if (wstrb[i])
            mem[waddr][(i*8)+7 -: 8] <= wdata[(i*8)+7 -: 8];
        end
      end else begin
        mem[waddr] <= wdata;
      end
    end
    if (re) begin
      rdata_pipe[0] <= mem[raddr];
      for (i = 1; i < READ_LATENCY; i = i + 1)
        rdata_pipe[i] <= rdata_pipe[i-1];
      rdata <= rdata_pipe[READ_LATENCY-1];
    end
  end
endmodule
"""

SRAM_1R1W_WRAPPER = """\
// Auto-generated SRAM instance wrapper
module {inst_name} (
    input  wire                  clk,
    input  wire                  we,
    input  wire [{addr_width_minus1}:0] waddr,
    input  wire [{data_width_minus1}:0] wdata,
    input  wire [{strb_width_minus1}:0] wstrb,
    input  wire                  re,
    input  wire [{addr_width_minus1}:0] raddr,
    output wire [{data_width_minus1}:0] rdata
);
  sram_1r1w #(
    .ADDR_WIDTH({addr_width}),
    .DATA_WIDTH({data_width}),
    .READ_LATENCY({read_latency}),
    .BYTE_ENABLE({byte_enable})
  ) u_mem (
    .clk(clk),
    .we(we),
    .waddr(waddr),
    .wdata(wdata),
    .wstrb(wstrb),
    .re(re),
    .raddr(raddr),
    .rdata(rdata)
  );
endmodule
"""

GEMM_MAC_INT8 = """\
module gemm_mac_int8 #(
    parameter integer LANES = 8,
    parameter integer ACC_WIDTH = 32
) (
    input  wire [LANES*8-1:0] a_vec,
    input  wire [LANES*8-1:0] b_vec,
    output reg  signed [ACC_WIDTH-1:0] acc_out
);
  integer i;
  reg signed [ACC_WIDTH-1:0] sum;
  reg signed [7:0] a_i;
  reg signed [7:0] b_i;

  always @(*) begin
    sum = 0;
    for (i = 0; i < LANES; i = i + 1) begin
      a_i = a_vec[(i*8) +: 8];
      b_i = b_vec[(i*8) +: 8];
      sum = sum + (a_i * b_i);
    end
    acc_out = sum;
  end
endmodule
"""

AXI_LITE_BRIDGE = """\
// Simple AXI-Lite to MMIO bridge (single-beat)
module axi_lite_mmio_bridge (
    input  wire                  clk,
    input  wire                  rst_n,
    // AXI-Lite slave interface
    input  wire [31:0]           s_axi_awaddr,
    input  wire                  s_axi_awvalid,
    output reg                   s_axi_awready,
    input  wire [{data_width_minus1}:0] s_axi_wdata,
    input  wire [(32/8)-1:0]    s_axi_wstrb,
    input  wire                  s_axi_wvalid,
    output reg                   s_axi_wready,
    output reg  [1:0]            s_axi_bresp,
    output reg                   s_axi_bvalid,
    input  wire                  s_axi_bready,
    input  wire [31:0]           s_axi_araddr,
    input  wire                  s_axi_arvalid,
    output reg                   s_axi_arready,
    output reg  [{data_width_minus1}:0] s_axi_rdata,
    output reg  [1:0]            s_axi_rresp,
    output reg                   s_axi_rvalid,
    input  wire                  s_axi_rready,
    // MMIO side
    output reg  [{mmio_addr_width_minus1}:0] mmio_addr,
    output reg                   mmio_we,
    output reg  [{data_width_minus1}:0] mmio_wdata,
    input  wire [{data_width_minus1}:0] mmio_rdata
);

  reg read_pending;

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      s_axi_awready <= 1'b0;
      s_axi_wready <= 1'b0;
      s_axi_bvalid <= 1'b0;
      s_axi_bresp <= 2'b00;
      s_axi_arready <= 1'b0;
      s_axi_rvalid <= 1'b0;
      s_axi_rresp <= 2'b00;
      s_axi_rdata <= 0;
      mmio_addr <= 0;
      mmio_we <= 1'b0;
      mmio_wdata <= 0;
      read_pending <= 1'b0;
    end else begin
      s_axi_awready <= s_axi_awvalid;
      s_axi_wready <= s_axi_wvalid;
      s_axi_arready <= (!read_pending && !s_axi_rvalid);
      mmio_we <= 1'b0;

      if (s_axi_awvalid && s_axi_wvalid) begin
        mmio_addr <= s_axi_awaddr[{mmio_addr_width_minus1}:0];
        mmio_wdata <= s_axi_wdata;
        mmio_we <= 1'b1;
        s_axi_bvalid <= 1'b1;
        s_axi_bresp <= 2'b00;
      end

      if (s_axi_bvalid && s_axi_bready)
        s_axi_bvalid <= 1'b0;

      if (s_axi_arvalid && s_axi_arready) begin
        mmio_addr <= s_axi_araddr[{mmio_addr_width_minus1}:0];
        read_pending <= 1'b1;
      end

      if (read_pending && !s_axi_rvalid) begin
        s_axi_rdata <= mmio_rdata;
        s_axi_rvalid <= 1'b1;
        s_axi_rresp <= 2'b00;
        read_pending <= 1'b0;
      end

      if (s_axi_rvalid && s_axi_rready) begin
        s_axi_rvalid <= 1'b0;
      end
    end
  end

endmodule
"""

AXI_LITE_WRAPPER = """\
// Auto-generated AXI-Lite wrapper (v0.1)
module {top_name}_axi (
    input  wire                  clk,
    input  wire                  rst_n,
    // AXI-Lite slave
    input  wire [31:0]           s_axi_awaddr,
    input  wire                  s_axi_awvalid,
    output wire                  s_axi_awready,
    input  wire [31:0]           s_axi_wdata,
    input  wire [3:0]            s_axi_wstrb,
    input  wire                  s_axi_wvalid,
    output wire                  s_axi_wready,
    output wire [1:0]            s_axi_bresp,
    output wire                  s_axi_bvalid,
    input  wire                  s_axi_bready,
    input  wire [31:0]           s_axi_araddr,
    input  wire                  s_axi_arvalid,
    output wire                  s_axi_arready,
    output wire [31:0]           s_axi_rdata,
    output wire [1:0]            s_axi_rresp,
    output wire                  s_axi_rvalid,
    input  wire                  s_axi_rready,
    // Interrupt
    output wire                  irq,
    // DMA stub ports
    output wire                  dma_req_valid,
    output wire [{dma_addr_width_minus1}:0] dma_req_src,
    output wire [{dma_addr_width_minus1}:0] dma_req_dst,
    output wire [31:0]           dma_req_bytes,
    input  wire                  dma_req_ready,
    input  wire                  dma_resp_done,
    // CQ memory port
    output wire [{dma_addr_width_minus1}:0] cq_mem_addr,
    input  wire [255:0]          cq_mem_rdata,
    // AXI memory master
    output wire                  m_axi_awvalid,
    input  wire                  m_axi_awready,
    output wire [{axi_addr_width_minus1}:0] m_axi_awaddr,
    output wire [7:0]            m_axi_awlen,
    output wire [2:0]            m_axi_awsize,
    output wire                  m_axi_wvalid,
    input  wire                  m_axi_wready,
    output wire [{axi_data_width_minus1}:0] m_axi_wdata,
    output wire [{axi_strb_width_minus1}:0] m_axi_wstrb,
    output wire                  m_axi_wlast,
    input  wire                  m_axi_bvalid,
    output wire                  m_axi_bready,
    output wire                  m_axi_arvalid,
    input  wire                  m_axi_arready,
    output wire [{axi_addr_width_minus1}:0] m_axi_araddr,
    output wire [7:0]            m_axi_arlen,
    output wire [2:0]            m_axi_arsize,
    input  wire                  m_axi_rvalid,
    output wire                  m_axi_rready,
    input  wire [{axi_data_width_minus1}:0] m_axi_rdata,
    input  wire                  m_axi_rlast
);
  wire [{mmio_addr_width_minus1}:0] mmio_addr;
  wire        mmio_we;
  wire [{data_width_minus1}:0] mmio_wdata;
  wire [{data_width_minus1}:0] mmio_rdata;

  axi_lite_mmio_bridge u_bridge (
    .clk(clk),
    .rst_n(rst_n),
    .s_axi_awaddr(s_axi_awaddr),
    .s_axi_awvalid(s_axi_awvalid),
    .s_axi_awready(s_axi_awready),
    .s_axi_wdata(s_axi_wdata),
    .s_axi_wstrb(s_axi_wstrb),
    .s_axi_wvalid(s_axi_wvalid),
    .s_axi_wready(s_axi_wready),
    .s_axi_bresp(s_axi_bresp),
    .s_axi_bvalid(s_axi_bvalid),
    .s_axi_bready(s_axi_bready),
    .s_axi_araddr(s_axi_araddr),
    .s_axi_arvalid(s_axi_arvalid),
    .s_axi_arready(s_axi_arready),
    .s_axi_rdata(s_axi_rdata),
    .s_axi_rresp(s_axi_rresp),
    .s_axi_rvalid(s_axi_rvalid),
    .s_axi_rready(s_axi_rready),
    .mmio_addr(mmio_addr),
    .mmio_we(mmio_we),
    .mmio_wdata(mmio_wdata),
    .mmio_rdata(mmio_rdata)
  );

  {top_name} u_top (
    .clk(clk),
    .rst_n(rst_n),
    .mmio_addr(mmio_addr),
    .mmio_we(mmio_we),
    .mmio_wdata(mmio_wdata),
    .mmio_rdata(mmio_rdata),
    .irq(irq),
    .dma_req_valid(dma_req_valid),
    .dma_req_src(dma_req_src),
    .dma_req_dst(dma_req_dst),
    .dma_req_bytes(dma_req_bytes),
    .dma_req_ready(dma_req_ready),
    .dma_resp_done(dma_resp_done),
    .cq_mem_addr(cq_mem_addr),
    .cq_mem_rdata(cq_mem_rdata),
    .m_axi_awvalid(m_axi_awvalid),
    .m_axi_awready(m_axi_awready),
    .m_axi_awaddr(m_axi_awaddr),
    .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize),
    .m_axi_wvalid(m_axi_wvalid),
    .m_axi_wready(m_axi_wready),
    .m_axi_wdata(m_axi_wdata),
    .m_axi_wstrb(m_axi_wstrb),
    .m_axi_wlast(m_axi_wlast),
    .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .m_axi_arvalid(m_axi_arvalid),
    .m_axi_arready(m_axi_arready),
    .m_axi_araddr(m_axi_araddr),
    .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize),
    .m_axi_rvalid(m_axi_rvalid),
    .m_axi_rready(m_axi_rready),
    .m_axi_rdata(m_axi_rdata),
    .m_axi_rlast(m_axi_rlast)
  );
endmodule
"""


def die(msg: str) -> None:
    print(f"rtlgen: {msg}", file=sys.stderr)
    sys.exit(1)


def load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    if cfg.get("version") != "0.1":
        die("config version must be 0.1")
    return cfg


def generate_cpp_mac_module(gemm_cfg: dict, out_path: Path) -> tuple[str, str]:
    cpp_cfg = gemm_cfg.get("rtlgen_cpp", {})
    if cpp_cfg is None:
        cpp_cfg = {}
    if not isinstance(cpp_cfg, dict):
        die("compute.gemm.rtlgen_cpp must be an object when provided")

    rtlgen_bin = str(cpp_cfg.get("binary_path", "build/rtlgen"))
    rtlgen_bin_path = Path(rtlgen_bin)
    if not rtlgen_bin_path.is_absolute():
        rtlgen_bin_path = Path.cwd() / rtlgen_bin_path
    if not rtlgen_bin_path.exists():
        die(
            f"compute.gemm.rtlgen_cpp.binary_path not found: {rtlgen_bin_path}. "
            "Build C++ rtlgen first or update binary_path."
        )

    module_name = str(cpp_cfg.get("module_name", "gemm_mac_int8_pp"))
    mac_cfg = {
        "version": "1.1",
        "operands": [
            {
                "name": "int8",
                "dimensions": 1,
                "bit_width": 8,
                "signed": True,
            }
        ],
        "operations": [
            {
                "type": "mac",
                "module_name": module_name,
                "operand": "int8",
                "options": {
                    "ppg_algorithm": str(cpp_cfg.get("ppg_algorithm", "Booth4")),
                    "compressor_structure": str(cpp_cfg.get("compressor_structure", "AdderTree")),
                    "compressor_library": str(cpp_cfg.get("compressor_library", "fa_ha")),
                    "compressor_assignment": str(cpp_cfg.get("compressor_assignment", "legacy_fa_ha")),
                    "cpa_structure": str(cpp_cfg.get("cpa_structure", "BrentKung")),
                    "accumulation_mode": "pp_row_feedback",
                    "pipeline_depth": 1,
                },
            }
        ],
    }

    gen_dir = out_path / ".rtlgen_cpp_mac"
    gen_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = (gen_dir / "mac_config.json").resolve()
    cfg_path.write_text(json.dumps(mac_cfg, indent=2) + "\n", encoding="utf-8")

    try:
        run = subprocess.run(
            [str(rtlgen_bin_path), str(cfg_path)],
            cwd=str(gen_dir),
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        stderr_text = exc.stderr.strip() if exc.stderr else ""
        stdout_text = exc.stdout.strip() if exc.stdout else ""
        details = stderr_text or stdout_text or "no stdout/stderr"
        die(f"C++ RTLGen mac generation failed: {details}")

    module_file = gen_dir / f"{module_name}.v"
    cpa_file = gen_dir / "MG_CPA.v"
    if not module_file.exists():
        die(f"C++ RTLGen mac output missing: {module_file}")
    if not cpa_file.exists():
        die(f"C++ RTLGen mac dependency missing: {cpa_file}")

    module_text = module_file.read_text(encoding="utf-8")
    cpa_text = cpa_file.read_text(encoding="utf-8")
    return module_name, (module_text + "\n\n" + cpa_text + "\n")


def write_outputs(cfg: dict, out_dir: str) -> None:
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    top_name = cfg["top_name"]
    mmio_addr_width = int(cfg["mmio_addr_width"])
    data_width = int(cfg["data_width"])
    dma_addr_width = int(cfg.get("dma_addr_width", 64))
    dma_data_width = int(cfg.get("dma_data_width", 256))
    axi_addr_width = int(cfg.get("axi_addr_width", 64))
    axi_data_width = int(cfg.get("axi_data_width", 256))
    axi_id_width = int(cfg.get("axi_id_width", 4))

    if axi_data_width % 8 != 0:
        die("axi_data_width must be a multiple of 8")
    axi_strb_width = axi_data_width // 8
    if (axi_strb_width & (axi_strb_width - 1)) != 0:
        die("axi_data_width must be a power-of-two number of bytes")
    axi_size = int(math.log2(axi_strb_width))
    if (1 << axi_size) != axi_strb_width:
        die("axi_data_width must be a power-of-two number of bytes")

    if axi_size == 0:
        dma_beats_expr = "cq_mem_rdata[223:192]"
        dma_arlen_expr = "cq_mem_rdata[223:192] - 1"
    else:
        hi = 223
        lo = 192 + axi_size
        rem_hi = lo - 1
        dma_beats_expr = f"(cq_mem_rdata[{hi}:{lo}] + (|cq_mem_rdata[{rem_hi}:192]))"
        dma_arlen_expr = f"(cq_mem_rdata[{hi}:{lo}] + (|cq_mem_rdata[{rem_hi}:192])) - 1"

    dma_addr_width_minus1 = dma_addr_width - 1
    axi_addr_width_minus1 = axi_addr_width - 1
    axi_data_width_minus1 = axi_data_width - 1
    axi_strb_width_minus1 = axi_strb_width - 1

    compute_cfg = cfg.get("compute", {})
    if compute_cfg is None:
        compute_cfg = {}
    if not isinstance(compute_cfg, dict):
        die("compute must be an object when provided")
    gemm_cfg = compute_cfg.get("gemm", {})
    if gemm_cfg is None:
        gemm_cfg = {}
    if not isinstance(gemm_cfg, dict):
        die("compute.gemm must be an object when provided")

    compute_enabled = bool(compute_cfg.get("enabled", False))
    gemm_mac_type = str(gemm_cfg.get("mac_type", "int8")).lower()
    gemm_mac_source = str(gemm_cfg.get("mac_source", "builtin_int8_dot")).lower()
    gemm_mac_lanes = int(gemm_cfg.get("lanes", 8))
    gemm_accum_width = int(gemm_cfg.get("accum_width", 32))
    gemm_pipeline = int(gemm_cfg.get("pipeline", 1))

    if gemm_pipeline < 1:
        die("compute.gemm.pipeline must be >= 1")

    if gemm_mac_lanes < 1 or gemm_mac_lanes > 8:
        die("compute.gemm.lanes must be in [1, 8] for int8 Phase 1")
    if gemm_accum_width < 16 or gemm_accum_width > 64:
        die("compute.gemm.accum_width must be in [16, 64]")
    if compute_enabled and gemm_mac_type != "int8":
        die("Phase 1 supports only compute.gemm.mac_type=int8")
    if gemm_mac_source not in ("builtin", "builtin_int8_dot", "rtlgen_cpp"):
        die("compute.gemm.mac_source must be one of: builtin_int8_dot, builtin, rtlgen_cpp")
    if compute_enabled and gemm_mac_source == "rtlgen_cpp":
        if gemm_mac_lanes != 1:
            die("compute.gemm.lanes must be 1 when compute.gemm.mac_source=rtlgen_cpp")
        if gemm_accum_width != 16:
            die("compute.gemm.accum_width must be 16 when compute.gemm.mac_source=rtlgen_cpp")

    gemm_mac_vec_width = gemm_mac_lanes * 8
    gemm_mac_vec_width_minus1 = gemm_mac_vec_width - 1
    gemm_accum_width_minus1 = gemm_accum_width - 1
    gemm_a_hi = 64 + gemm_mac_vec_width - 1
    gemm_b_hi = 128 + gemm_mac_vec_width - 1

    use_cpp_mac = compute_enabled and (gemm_mac_source == "rtlgen_cpp")
    if use_cpp_mac:
        cpp_module_name, cpp_module_text = generate_cpp_mac_module(gemm_cfg, out_path)
        compute_modules = cpp_module_text + "\n"
    else:
        cpp_module_name = ""
        compute_modules = GEMM_MAC_INT8 + "\n\n"
    compute_state_regs = f"""  reg [{gemm_mac_vec_width_minus1}:0] gemm_mac_a_vec0;
  reg [{gemm_mac_vec_width_minus1}:0] gemm_mac_b_vec0;
  reg [{gemm_mac_vec_width_minus1}:0] gemm_mac_a_vec1;
  reg [{gemm_mac_vec_width_minus1}:0] gemm_mac_b_vec1;
  reg signed [{gemm_accum_width_minus1}:0] gemm_slot_accum0;
  reg signed [{gemm_accum_width_minus1}:0] gemm_slot_accum1;"""

    if use_cpp_mac:
        compute_instances = f"""
  wire signed [15:0] gemm_mac_next0;
  wire signed [15:0] gemm_mac_next1;

  {cpp_module_name} u_gemm_mac0 (
    .multiplicand(gemm_mac_a_vec0[7:0]),
    .multiplier(gemm_mac_b_vec0[7:0]),
    .accumulator(gemm_slot_accum0[15:0]),
    .result(gemm_mac_next0)
  );

  {cpp_module_name} u_gemm_mac1 (
    .multiplicand(gemm_mac_a_vec1[7:0]),
    .multiplier(gemm_mac_b_vec1[7:0]),
    .accumulator(gemm_slot_accum1[15:0]),
    .result(gemm_mac_next1)
  );
"""
        compute_accum_update = """      if (gemm_slot_valid[0] && !gemm_slot_done[0]) begin
        gemm_slot_accum0 <= $signed(gemm_mac_next0);
      end
      if (gemm_slot_valid[1] && !gemm_slot_done[1]) begin
        gemm_slot_accum1 <= $signed(gemm_mac_next1);
      end
"""
    else:
        compute_instances = f"""
  wire signed [{gemm_accum_width_minus1}:0] gemm_mac_dot0;
  wire signed [{gemm_accum_width_minus1}:0] gemm_mac_dot1;

  gemm_mac_int8 #(
    .LANES({gemm_mac_lanes}),
    .ACC_WIDTH({gemm_accum_width})
  ) u_gemm_mac0 (
    .a_vec(gemm_mac_a_vec0),
    .b_vec(gemm_mac_b_vec0),
    .acc_out(gemm_mac_dot0)
  );

  gemm_mac_int8 #(
    .LANES({gemm_mac_lanes}),
    .ACC_WIDTH({gemm_accum_width})
  ) u_gemm_mac1 (
    .a_vec(gemm_mac_a_vec1),
    .b_vec(gemm_mac_b_vec1),
    .acc_out(gemm_mac_dot1)
  );
"""
        compute_accum_update = """      if (gemm_slot_valid[0] && !gemm_slot_done[0]) begin
        gemm_slot_accum0 <= gemm_slot_accum0 + gemm_mac_dot0;
      end
      if (gemm_slot_valid[1] && !gemm_slot_done[1]) begin
        gemm_slot_accum1 <= gemm_slot_accum1 + gemm_mac_dot1;
      end
"""
    compute_reset = """      gemm_mac_a_vec0 <= 0;
      gemm_mac_b_vec0 <= 0;
      gemm_mac_a_vec1 <= 0;
      gemm_mac_b_vec1 <= 0;
      gemm_slot_accum0 <= 0;
      gemm_slot_accum1 <= 0;"""

    if compute_enabled:
        gemm_slot_init0_v1 = f"""                gemm_mac_a_vec0 <= cq_mem_rdata[{gemm_a_hi}:64];
                gemm_mac_b_vec0 <= cq_mem_rdata[{gemm_b_hi}:128];
                gemm_slot_accum0 <= 0;"""
        gemm_slot_init1_v1 = f"""                gemm_mac_a_vec1 <= cq_mem_rdata[{gemm_a_hi}:64];
                gemm_mac_b_vec1 <= cq_mem_rdata[{gemm_b_hi}:128];
                gemm_slot_accum1 <= 0;"""
        gemm_slot_init0_v2 = f"""                gemm_mac_a_vec0 <= cq_word0[{gemm_a_hi}:64];
                gemm_mac_b_vec0 <= cq_word0[{gemm_b_hi}:128];
                gemm_slot_accum0 <= 0;"""
        gemm_slot_init1_v2 = f"""                gemm_mac_a_vec1 <= cq_word0[{gemm_a_hi}:64];
                gemm_mac_b_vec1 <= cq_word0[{gemm_b_hi}:128];
                gemm_slot_accum1 <= 0;"""
    else:
        compute_accum_update = ""
        gemm_slot_init0_v1 = ""
        gemm_slot_init1_v1 = ""
        gemm_slot_init0_v2 = ""
        gemm_slot_init1_v2 = ""

    enable_dma_ports = bool(cfg.get("enable_dma_ports", False))
    enable_cq_mem_ports = bool(cfg.get("enable_cq_mem_ports", False))
    enable_axi_ports = bool(cfg.get("enable_axi_ports", False))
    sram_instances = cfg.get("sram_instances", [])
    if enable_dma_ports:
        dma_ports = f""",
    output reg                   dma_req_valid,
    output reg  [{dma_addr_width_minus1}:0] dma_req_src,
    output reg  [{dma_addr_width_minus1}:0] dma_req_dst,
    output reg  [31:0]           dma_req_bytes,
    input  wire                  dma_req_ready,
    input  wire                  dma_resp_done
"""
        dma_reset = """      dma_req_valid <= 0;
      dma_req_src <= 0;
      dma_req_dst <= 0;
      dma_req_bytes <= 0;"""
        dma_handshake = """      if (dma_req_valid && dma_req_ready) begin
        dma_req_valid <= 0;
      end
      if (dma_resp_done) begin
        irq_status[IRQ_EVENT] <= 1'b1;
      end"""
        dma_kick = """            // DMA request will be issued when DMA_COPY descriptor is fetched."""
    else:
        dma_ports = ""
        dma_reset = ""
        dma_handshake = ""
        dma_kick = ""

    gemm_update = f"""      // Two-slot GEMM stub with OOO-capable completion scheduling.
      gemm_done_pulse <= 1'b0;
{compute_accum_update}\
      if (gemm_slot_valid[0] && !gemm_slot_done[0]) begin
        if (gemm_slot_cycles0 != 0) begin
          gemm_slot_cycles0 <= gemm_slot_cycles0 - 1;
          if (gemm_slot_cycles0 == 1) begin
            gemm_slot_done[0] <= 1'b1;
            gemm_done_pulse <= 1'b1;
            gemm_done_uid <= gemm_slot_uid0;
          end
        end else begin
          gemm_slot_done[0] <= 1'b1;
          gemm_done_pulse <= 1'b1;
          gemm_done_uid <= gemm_slot_uid0;
        end
      end
      if (gemm_slot_valid[1] && !gemm_slot_done[1]) begin
        if (gemm_slot_cycles1 != 0) begin
          gemm_slot_cycles1 <= gemm_slot_cycles1 - 1;
          if (gemm_slot_cycles1 == 1) begin
            gemm_slot_done[1] <= 1'b1;
            gemm_done_pulse <= 1'b1;
            gemm_done_uid <= gemm_slot_uid1;
          end
        end else begin
          gemm_slot_done[1] <= 1'b1;
          gemm_done_pulse <= 1'b1;
          gemm_done_uid <= gemm_slot_uid1;
        end
      end
      // Prefer slot1 if both are done, so completion order can differ from issue order.
      if (!dma_pending) begin
        if (gemm_slot_done[1]) begin
          dma_src <= gemm_slot_src1;
          dma_dst <= gemm_slot_dst1;
          dma_size <= gemm_slot_size1;
          dma_beats <= gemm_slot_beats1;
          dma_arlen <= gemm_slot_arlen1;
          dma_pending <= 1'b1;
          gemm_slot_valid[1] <= 1'b0;
          gemm_slot_done[1] <= 1'b0;
          gemm_dma_sel <= 1'b1;
        end else if (gemm_slot_done[0]) begin
          dma_src <= gemm_slot_src0;
          dma_dst <= gemm_slot_dst0;
          dma_size <= gemm_slot_size0;
          dma_beats <= gemm_slot_beats0;
          dma_arlen <= gemm_slot_arlen0;
          dma_pending <= 1'b1;
          gemm_slot_valid[0] <= 1'b0;
          gemm_slot_done[0] <= 1'b0;
          gemm_dma_sel <= 1'b0;
        end
      end
      gemm_pending <= (gemm_slot_valid != 2'b00);"""

    if enable_cq_mem_ports:
        cq_mem_ports = f""",
    output reg  [{dma_addr_width_minus1}:0] cq_mem_addr,
    input  wire [255:0]          cq_mem_rdata
"""
        cq_block = f"""      // Command queue fetch (supports v0.1 32B and v0.2 64B descriptors).
      if (cq_count != 0) begin
        if (!cq_stage_valid && !cq_pending_ext) begin
          cq_mem_addr <= {{cq_base_hi, cq_base_lo}} + cq_head;
          cq_stage_valid <= 1'b1;
        end else if (cq_stage_valid && !cq_pending_ext) begin
          cq_word0 <= cq_mem_rdata;
          cq_word0_size <= cq_mem_rdata[23:16];
          if (cq_mem_rdata[23:16] >= 8'h02) begin
            cq_pending_ext <= 1'b1;
            cq_stage_valid <= 1'b0;
          end else begin
            last_opcode <= cq_mem_rdata[7:0];
            last_tag <= cq_mem_rdata[63:32];
            last_src <= cq_mem_rdata[127:64];
            last_dst <= cq_mem_rdata[191:128];
            last_size <= cq_mem_rdata[223:192];
            last_op_uid <= 0;
            if (cq_mem_rdata[7:0] == 8'h01) begin
              dma_req_valid <= 1'b1;
              dma_req_src <= cq_mem_rdata[127:64];
              dma_req_dst <= cq_mem_rdata[191:128];
              dma_req_bytes <= cq_mem_rdata[223:192];
              dma_src <= cq_mem_rdata[127:64];
              dma_dst <= cq_mem_rdata[191:128];
              dma_size <= cq_mem_rdata[223:192];
              dma_beats <= {dma_beats_expr};
              dma_arlen <= {dma_arlen_expr};
              dma_pending <= 1'b1;
            end else if (cq_mem_rdata[7:0] == 8'h10) begin
              // GEMM stub: v0.1 sizes packed in TAG.
              if (!gemm_slot_valid[0]) begin
                gemm_slot_valid[0] <= 1'b1;
                gemm_slot_done[0] <= 1'b0;
                gemm_slot_uid0 <= 64'h0;
{gemm_slot_init0_v1}
                if ((cq_mem_rdata[63:52] == 0) || (cq_mem_rdata[51:42] == 0) || (cq_mem_rdata[41:32] == 0)) begin
                  gemm_slot_cycles0 <= 1;
                end else begin
                  gemm_slot_cycles0 <= (((cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * cq_mem_rdata[41:32]) >> 10) + 1);
                end
                gemm_slot_src0 <= cq_mem_rdata[127:64];
                gemm_slot_dst0 <= cq_mem_rdata[255:192];
                gemm_slot_size0 <= ((cq_mem_rdata[11:8] == 4'h1 || cq_mem_rdata[11:8] == 4'h2)
                                    ? (cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * 2)
                                    : (cq_mem_rdata[63:52] * cq_mem_rdata[51:42]));
                gemm_slot_beats0 <= (((((cq_mem_rdata[11:8] == 4'h1 || cq_mem_rdata[11:8] == 4'h2)
                                        ? (cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * 2)
                                        : (cq_mem_rdata[63:52] * cq_mem_rdata[51:42]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}));
                gemm_slot_arlen0 <= (((((cq_mem_rdata[11:8] == 4'h1 || cq_mem_rdata[11:8] == 4'h2)
                                        ? (cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * 2)
                                        : (cq_mem_rdata[63:52] * cq_mem_rdata[51:42]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}) - 1);
              end else if (!gemm_slot_valid[1]) begin
                gemm_slot_valid[1] <= 1'b1;
                gemm_slot_done[1] <= 1'b0;
                gemm_slot_uid1 <= 64'h0;
{gemm_slot_init1_v1}
                if ((cq_mem_rdata[63:52] == 0) || (cq_mem_rdata[51:42] == 0) || (cq_mem_rdata[41:32] == 0)) begin
                  gemm_slot_cycles1 <= 1;
                end else begin
                  gemm_slot_cycles1 <= (((cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * cq_mem_rdata[41:32]) >> 10) + 1);
                end
                gemm_slot_src1 <= cq_mem_rdata[127:64];
                gemm_slot_dst1 <= cq_mem_rdata[255:192];
                gemm_slot_size1 <= ((cq_mem_rdata[11:8] == 4'h1 || cq_mem_rdata[11:8] == 4'h2)
                                    ? (cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * 2)
                                    : (cq_mem_rdata[63:52] * cq_mem_rdata[51:42]));
                gemm_slot_beats1 <= (((((cq_mem_rdata[11:8] == 4'h1 || cq_mem_rdata[11:8] == 4'h2)
                                        ? (cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * 2)
                                        : (cq_mem_rdata[63:52] * cq_mem_rdata[51:42]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}));
                gemm_slot_arlen1 <= (((((cq_mem_rdata[11:8] == 4'h1 || cq_mem_rdata[11:8] == 4'h2)
                                        ? (cq_mem_rdata[63:52] * cq_mem_rdata[51:42] * 2)
                                        : (cq_mem_rdata[63:52] * cq_mem_rdata[51:42]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}) - 1);
              end else begin
                error_code <= 32'h2; // GEMM in-flight queue full
              end
            end else if (cq_mem_rdata[7:0] == 8'h20) begin
              // EVENT_SIGNAL: immediately signal
              irq_status[IRQ_EVENT] <= 1'b1;
            end else if (cq_mem_rdata[7:0] == 8'h21) begin
              // EVENT_WAIT: stubbed as immediately satisfied
              irq_status[IRQ_EVENT] <= 1'b1;
            end else begin
              error_code <= 32'h1;
            end
            cq_head <= cq_head + 32;
            if (cq_count == 1) begin
              irq_status[IRQ_CQ_EMPTY] <= 1'b1;
            end
            cq_count <= cq_count - 1;
            cq_stage_valid <= 1'b0;
          end
        end else if (cq_pending_ext) begin
          if (!cq_stage_valid) begin
            cq_mem_addr <= {{cq_base_hi, cq_base_lo}} + cq_head + 32;
            cq_stage_valid <= 1'b1;
          end else begin
            last_opcode <= cq_word0[7:0];
            last_tag <= cq_word0[63:32];
            last_src <= cq_word0[127:64];
            last_dst <= cq_word0[191:128];
            last_size <= cq_mem_rdata[31:0];
            last_op_uid <= cq_mem_rdata[255:192];
            if (cq_word0[7:0] == 8'h10) begin
              // GEMM stub: v0.2 sizes in extension.
              if (!gemm_slot_valid[0]) begin
                gemm_slot_valid[0] <= 1'b1;
                gemm_slot_done[0] <= 1'b0;
                gemm_slot_uid0 <= cq_mem_rdata[255:192];
{gemm_slot_init0_v2}
                if ((cq_mem_rdata[31:0] == 0) || (cq_mem_rdata[63:32] == 0) || (cq_mem_rdata[95:64] == 0)) begin
                  gemm_slot_cycles0 <= 1;
                end else begin
                  // Optional UID-based jitter (bit63) to exercise OOO completion in tests.
                  gemm_slot_cycles0 <= (((cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * cq_mem_rdata[95:64]) >> 10)
                                        + 1 + (cq_mem_rdata[255] ? 8 : 0));
                end
                gemm_slot_src0 <= cq_word0[127:64];
                gemm_slot_dst0 <= cq_word0[255:192];
                gemm_slot_size0 <= ((cq_word0[11:8] == 4'h1 || cq_word0[11:8] == 4'h2)
                                    ? (cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * 2)
                                    : (cq_mem_rdata[31:0] * cq_mem_rdata[63:32]));
                gemm_slot_beats0 <= (((((cq_word0[11:8] == 4'h1 || cq_word0[11:8] == 4'h2)
                                        ? (cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * 2)
                                        : (cq_mem_rdata[31:0] * cq_mem_rdata[63:32]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}));
                gemm_slot_arlen0 <= (((((cq_word0[11:8] == 4'h1 || cq_word0[11:8] == 4'h2)
                                        ? (cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * 2)
                                        : (cq_mem_rdata[31:0] * cq_mem_rdata[63:32]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}) - 1);
              end else if (!gemm_slot_valid[1]) begin
                gemm_slot_valid[1] <= 1'b1;
                gemm_slot_done[1] <= 1'b0;
                gemm_slot_uid1 <= cq_mem_rdata[255:192];
{gemm_slot_init1_v2}
                if ((cq_mem_rdata[31:0] == 0) || (cq_mem_rdata[63:32] == 0) || (cq_mem_rdata[95:64] == 0)) begin
                  gemm_slot_cycles1 <= 1;
                end else begin
                  gemm_slot_cycles1 <= (((cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * cq_mem_rdata[95:64]) >> 10)
                                        + 1 + (cq_mem_rdata[255] ? 8 : 0));
                end
                gemm_slot_src1 <= cq_word0[127:64];
                gemm_slot_dst1 <= cq_word0[255:192];
                gemm_slot_size1 <= ((cq_word0[11:8] == 4'h1 || cq_word0[11:8] == 4'h2)
                                    ? (cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * 2)
                                    : (cq_mem_rdata[31:0] * cq_mem_rdata[63:32]));
                gemm_slot_beats1 <= (((((cq_word0[11:8] == 4'h1 || cq_word0[11:8] == 4'h2)
                                        ? (cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * 2)
                                        : (cq_mem_rdata[31:0] * cq_mem_rdata[63:32]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}));
                gemm_slot_arlen1 <= (((((cq_word0[11:8] == 4'h1 || cq_word0[11:8] == 4'h2)
                                        ? (cq_mem_rdata[31:0] * cq_mem_rdata[63:32] * 2)
                                        : (cq_mem_rdata[31:0] * cq_mem_rdata[63:32]))
                                       + AXI_BEAT_BYTES - 1) >> {axi_size}) - 1);
              end else begin
                error_code <= 32'h2; // GEMM in-flight queue full
              end
            end else begin
              error_code <= 32'h1;
            end
            if (cq_count <= cq_word0_size) begin
              irq_status[IRQ_CQ_EMPTY] <= 1'b1;
            end
            cq_head <= cq_head + (cq_word0_size * 32);
            cq_count <= cq_count - cq_word0_size;
            cq_stage_valid <= 1'b0;
            cq_pending_ext <= 1'b0;
          end
        end
      end"""
    else:
        cq_mem_ports = ""
        cq_block = ""

    if enable_axi_ports:
        axi_ports = f""",
    output reg                   m_axi_awvalid,
    input  wire                  m_axi_awready,
    output reg  [{axi_addr_width_minus1}:0] m_axi_awaddr,
    output reg  [7:0]            m_axi_awlen,
    output reg  [2:0]            m_axi_awsize,
    output reg                   m_axi_wvalid,
    input  wire                  m_axi_wready,
    output reg  [{axi_data_width_minus1}:0] m_axi_wdata,
    output reg  [{axi_strb_width_minus1}:0] m_axi_wstrb,
    output reg                   m_axi_wlast,
    input  wire                  m_axi_bvalid,
    output reg                   m_axi_bready,
    output reg                   m_axi_arvalid,
    input  wire                  m_axi_arready,
    output reg  [{axi_addr_width_minus1}:0] m_axi_araddr,
    output reg  [7:0]            m_axi_arlen,
    output reg  [2:0]            m_axi_arsize,
    input  wire                  m_axi_rvalid,
    output reg                   m_axi_rready,
    input  wire [{axi_data_width_minus1}:0] m_axi_rdata,
    input  wire                  m_axi_rlast
"""
        axi_defaults = """      m_axi_awvalid <= 1'b0;
      m_axi_awaddr <= 0;
      m_axi_awlen <= 0;
      m_axi_awsize <= 0;
      m_axi_wvalid <= 1'b0;
      m_axi_wdata <= 0;
      m_axi_wstrb <= 0;
      m_axi_wlast <= 1'b0;
      m_axi_bready <= 1'b0;
      m_axi_arvalid <= 1'b0;
      m_axi_araddr <= 0;
      m_axi_arlen <= 0;
      m_axi_arsize <= 0;
      m_axi_rready <= 1'b0;"""
        axi_fsm = f"""      // AXI DMA shim: burst read then burst write.
      case (dma_state)
        0: begin
          if (dma_pending) begin
            if (dma_beats_left == 0) begin
              dma_beats_left <= dma_beats;
              dma_rd_idx <= 0;
              dma_wr_idx <= 0;
            end
            m_axi_arvalid <= 1'b1;
            m_axi_araddr <= dma_src;
            m_axi_arlen <= dma_arlen;
            m_axi_arsize <= 3'd{axi_size}; // beat bytes = 2**{axi_size}
            if (m_axi_arready) begin
              dma_state <= 1;
            end
          end
        end
        1: begin
          m_axi_rready <= 1'b1;
          if (m_axi_rvalid) begin
            dma_buf_mem[dma_rd_idx] <= m_axi_rdata;
            dma_rd_idx <= dma_rd_idx + 1;
            if (m_axi_rlast) begin
              dma_state <= 2;
            end
          end
        end
        2: begin
          m_axi_awvalid <= 1'b1;
          m_axi_awaddr <= dma_dst;
          m_axi_awlen <= dma_arlen;
          m_axi_awsize <= 3'd{axi_size};
          if (m_axi_awready) begin
            dma_state <= 3;
          end
        end
        3: begin
          m_axi_wvalid <= 1'b1;
          m_axi_wdata <= dma_buf_mem[dma_wr_idx];
          m_axi_wstrb <= {{{axi_strb_width}{{1'b1}}}};
          m_axi_wlast <= (dma_beats_left == 1);
          if (m_axi_wready) begin
            if (dma_beats_left == 1) begin
              dma_state <= 4;
            end else begin
              dma_wr_idx <= dma_wr_idx + 1;
              dma_beats_left <= dma_beats_left - 1;
            end
          end
        end
        4: begin
          m_axi_bready <= 1'b1;
          if (m_axi_bvalid) begin
            dma_beats_left <= 0;
            dma_state <= 0;
            dma_pending <= 1'b0;
            irq_status[IRQ_EVENT] <= 1'b1;
          end
        end
        default: dma_state <= 0;
      endcase"""
        axi_reset = """      m_axi_awvalid <= 1'b0;
      m_axi_awaddr <= 0;
      m_axi_awlen <= 0;
      m_axi_awsize <= 0;
      m_axi_wvalid <= 1'b0;
      m_axi_wdata <= 0;
      m_axi_wstrb <= 0;
      m_axi_wlast <= 1'b0;
      m_axi_bready <= 1'b0;
      m_axi_arvalid <= 1'b0;
      m_axi_araddr <= 0;
      m_axi_arlen <= 0;
      m_axi_arsize <= 0;
      m_axi_rready <= 1'b0;"""
    else:
        axi_ports = ""
        axi_defaults = ""
        axi_fsm = ""
        axi_reset = ""

    verilog = TOP_TEMPLATE.format(
        compute_modules=compute_modules,
        top_name=top_name,
        mmio_addr_width_minus1=mmio_addr_width - 1,
        data_width_minus1=data_width - 1,
        dma_addr_width_minus1=dma_addr_width_minus1,
        dma_data_width_minus1=dma_data_width - 1,
        axi_addr_width_minus1=axi_addr_width_minus1,
        axi_data_width_minus1=axi_data_width_minus1,
        axi_strb_width_minus1=axi_strb_width_minus1,
        axi_beat_bytes=(1 << axi_size),
        dma_ports=dma_ports,
        compute_state_regs=compute_state_regs,
        dma_reset=dma_reset,
        compute_reset=compute_reset,
        dma_handshake=dma_handshake,
        dma_kick=dma_kick,
        gemm_update=gemm_update,
        cq_mem_ports=cq_mem_ports,
        cq_block=cq_block,
        compute_instances=compute_instances,
        axi_ports=axi_ports,
        axi_defaults=axi_defaults,
        axi_fsm=axi_fsm,
        axi_reset=axi_reset,
    )

    (out_path / "top.v").write_text(verilog, encoding="utf-8")
    (out_path / "config.json").write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")

    sram_map = []
    if sram_instances:
        models = [SRAM_1R1W_MODEL]
        next_base = 0x80000000
        for inst in sram_instances:
            if inst.get("port", "1r1w") != "1r1w":
                die(f"unsupported SRAM port type: {inst.get('port')}")
            read_latency = int(inst.get("read_latency", 1))
            if read_latency < 1:
                die("SRAM read_latency must be >= 1")
            sram_data_width = int(inst["width"])
            if sram_data_width % 8 != 0:
                die("SRAM width must be a multiple of 8")
            depth = int(inst["depth"])
            if depth < 2:
                die("SRAM depth must be >= 2")
            if (depth & (depth - 1)) != 0:
                die("SRAM depth must be a power of two")
            strb_width = sram_data_width // 8
            size_bytes = depth * strb_width * int(inst.get("banks", 1))
            base_addr = inst.get("base_addr")
            if base_addr is None:
                base_addr = next_base
                next_base += size_bytes
            if isinstance(base_addr, str):
                base_addr = int(base_addr, 0)
            alignment_bytes = int(inst.get("alignment_bytes", 64))
            word_bytes = sram_data_width // 8
            sram_map.append(
                {
                    "name": inst["name"],
                    "base_addr": base_addr,
                    "size_bytes": size_bytes,
                    "word_bytes": word_bytes,
                    "alignment_bytes": alignment_bytes,
                }
            )
            models.append(
                SRAM_1R1W_WRAPPER.format(
                    inst_name=inst["name"],
                    addr_width=depth.bit_length() - 1,
                    addr_width_minus1=depth.bit_length() - 2,
                    data_width=sram_data_width,
                    data_width_minus1=sram_data_width - 1,
                    strb_width_minus1=strb_width - 1,
                    read_latency=read_latency,
                    byte_enable=1 if bool(inst.get("byte_en", True)) else 0,
                )
            )
        (out_path / "sram_models.sv").write_text("\n\n".join(models) + "\n", encoding="utf-8")
        (out_path / "sram_map.json").write_text(json.dumps(sram_map, indent=2) + "\n", encoding="utf-8")

    if not sram_map:
        (out_path / "sram_map.json").write_text("[]\n", encoding="utf-8")

    count = len(sram_map)
    max_srams = 8
    vh_lines = [
        "localparam int SRAM_COUNT = %d;" % count,
        "localparam int SRAM_MAX = %d;" % max_srams,
    ]
    for idx in range(max_srams):
        if idx < count:
            entry = sram_map[idx]
            vh_lines.append("localparam logic [63:0] SRAM_BASE%d = 64'h%016x;" % (idx, entry["base_addr"]))
            vh_lines.append("localparam logic [63:0] SRAM_SIZE%d = %d;" % (idx, entry["size_bytes"]))
            vh_lines.append("localparam int SRAM_ALIGN%d = %d;" % (idx, entry["alignment_bytes"]))
            vh_lines.append("localparam int SRAM_WORD_BYTES%d = %d;" % (idx, entry["word_bytes"]))
        else:
            vh_lines.append("localparam logic [63:0] SRAM_BASE%d = 64'h0;" % idx)
            vh_lines.append("localparam logic [63:0] SRAM_SIZE%d = 0;" % idx)
            vh_lines.append("localparam int SRAM_ALIGN%d = 0;" % idx)
            vh_lines.append("localparam int SRAM_WORD_BYTES%d = 0;" % idx)
    (out_path / "sram_map.vh").write_text("\n".join(vh_lines) + "\n", encoding="utf-8")

    mmio_lines = [
        "localparam int OFF_VERSION    = 12'h000;",
        "localparam int OFF_CAPS       = 12'h004;",
        "localparam int OFF_STATUS     = 12'h008;",
        "localparam int OFF_CONTROL    = 12'h00C;",
        "localparam int OFF_IRQ_STATUS = 12'h010;",
        "localparam int OFF_IRQ_ENABLE = 12'h014;",
        "localparam int OFF_CQ_BASE_LO = 12'h020;",
        "localparam int OFF_CQ_BASE_HI = 12'h024;",
        "localparam int OFF_CQ_SIZE    = 12'h028;",
        "localparam int OFF_CQ_HEAD    = 12'h02C;",
        "localparam int OFF_CQ_TAIL    = 12'h030;",
        "localparam int OFF_DOORBELL   = 12'h040;",
        "localparam int OFF_ERROR_CODE = 12'h044;",
    ]
    (out_path / "mmio_map.vh").write_text("\n".join(mmio_lines) + "\n", encoding="utf-8")

    if bool(cfg.get("enable_axi_lite_wrapper", False)):
        bridge = AXI_LITE_BRIDGE.format(
            data_width_minus1=data_width - 1,
            mmio_addr_width_minus1=mmio_addr_width - 1,
        )
        wrapper = AXI_LITE_WRAPPER.format(
            top_name=top_name,
            mmio_addr_width_minus1=mmio_addr_width - 1,
            data_width_minus1=data_width - 1,
            dma_addr_width_minus1=dma_addr_width_minus1,
            axi_addr_width_minus1=axi_addr_width_minus1,
            axi_data_width_minus1=axi_data_width_minus1,
            axi_strb_width_minus1=axi_strb_width_minus1,
        )
        (out_path / "axi_lite_mmio_bridge.sv").write_text(bridge, encoding="utf-8")
        (out_path / "top_axi.v").write_text(wrapper, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate stub NPU RTL.")
    parser.add_argument("--config", required=True, help="Path to config JSON")
    parser.add_argument("--out", required=True, help="Output directory")
    args = parser.parse_args()

    cfg = load_config(args.config)
    write_outputs(cfg, args.out)
    print(f"rtlgen: wrote RTL to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
