#!/usr/bin/env python3
"""Generate a bounded local exact-partial reducer with 8-wave temporal persistence."""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_score32_exact_local_reducer import generate as generate_local_reducer
from npu.rtlgen.gen_attention_score32_online_state_merge import generate as generate_merge
from npu.sim.perf.attention_exact_partial import (
    LOCAL_TEMPORAL_WAVES,
    PARTIAL_LINK_BITS,
    PARTIAL_PAYLOAD_BITS,
    exact_local_temporal_reducer_service_manifest,
)

JsonDict = dict[str, Any]
_CONFIG_KEY = "attention_score32_exact_local_temporal_reducer"
_MANIFEST_NAME = "attention_score32_exact_local_temporal_reducer_manifest.json"


def _load(path: Path) -> JsonDict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"config must decode to a JSON object: {path}")
    return payload


def _clog2(value: int) -> int:
    resolved = 1
    while (1 << resolved) < max(2, int(value)):
        resolved += 1
    return resolved


def _validate(config: JsonDict) -> JsonDict:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get(_CONFIG_KEY)
    if not top_name or not isinstance(body, dict):
        raise SystemExit(f"config requires top_name and {_CONFIG_KEY}")

    producers = int(body.get("producers", 53))
    value_slices = int(body.get("value_slices", 16))
    head_id_bits = int(body.get("head_id_bits", 5))
    persistent_waves = int(body.get("persistent_waves", LOCAL_TEMPORAL_WAVES))
    if producers not in {53, 54}:
        raise SystemExit("producers must be exactly 53 or 54")
    if value_slices != 16:
        raise SystemExit("value_slices must remain fixed at 16")
    if head_id_bits != 5:
        raise SystemExit("head_id_bits must remain fixed at 5")
    if persistent_waves != LOCAL_TEMPORAL_WAVES:
        raise SystemExit(f"persistent_waves must remain fixed at {LOCAL_TEMPORAL_WAVES}")
    return {
        "top_name": top_name,
        "producers": producers,
        "value_slices": value_slices,
        "head_id_bits": head_id_bits,
        "persistent_waves": persistent_waves,
    }


def _top_pin_bits(*, producers: int, head_id_bits: int, slice_bits: int) -> int:
    leaf_bits = producers * (1 + 16 + head_id_bits + 32 + 33 + slice_bits + 1 + PARTIAL_PAYLOAD_BITS + 1)
    root_bits = 1 + 1 + 16 + head_id_bits + 32 + 33 + slice_bits + 1 + PARTIAL_PAYLOAD_BITS
    monitor_bits = (10 * 32) + 3 + 3
    return 2 + leaf_bits + root_bits + monitor_bits


def _top(*, top_name: str, reducer_top: str, merge_top: str, producers: int, head_id_bits: int) -> str:
    slice_bits = _clog2(16)
    state_decl = "\n".join(
        [
            "  reg [15:0] state_command_id_q [0:15];",
            "  reg [HEAD_ID_BITS-1:0] state_head_id_q [0:15];",
            "  reg signed [31:0] state_global_max_q [0:15];",
            "  reg [32:0] state_exp_sum_q [0:15];",
            "  reg state_last_q [0:15];",
            "  reg [PARTIAL_PAYLOAD_BITS-1:0] state_value_q [0:15];",
        ]
    )
    state_reset = "\n".join(
        [
            f"      state_command_id_q[{index}] <= 16'd0;\n"
            f"      state_head_id_q[{index}] <= {{HEAD_ID_BITS{{1'b0}}}};\n"
            f"      state_global_max_q[{index}] <= 32'sd0;\n"
            f"      state_exp_sum_q[{index}] <= 33'd0;\n"
            f"      state_last_q[{index}] <= 1'b{1 if index == 15 else 0};\n"
            f"      state_value_q[{index}] <= {{PARTIAL_PAYLOAD_BITS{{1'b0}}}};"
            for index in range(16)
        ]
    )
    emit_case = "\n".join(
        [
            f"""      4'd{index}: begin
        emit_command_id_r = state_command_id_q[{index}];
        emit_head_id_r = state_head_id_q[{index}];
        emit_global_max_r = state_global_max_q[{index}];
        emit_exp_sum_r = state_exp_sum_q[{index}];
        emit_last_r = state_last_q[{index}];
        emit_value_r = state_value_q[{index}];
      end"""
            for index in range(16)
        ]
    )
    return f"""// Auto-generated by npu/rtlgen/gen_attention_score32_exact_local_temporal_reducer.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire [{producers - 1}:0] leaf_valid,
    output wire [{producers - 1}:0] leaf_ready,
    input  wire [{producers * 16 - 1}:0] leaf_command_id,
    input  wire [{producers * head_id_bits - 1}:0] leaf_head_id,
    input  wire [{producers * 32 - 1}:0] leaf_global_max,
    input  wire [{producers * 33 - 1}:0] leaf_exp_sum,
    input  wire [{producers * slice_bits - 1}:0] leaf_slice,
    input  wire [{producers - 1}:0] leaf_last,
    input  wire [{producers * PARTIAL_PAYLOAD_BITS - 1}:0] leaf_value,
    output wire         out_valid,
    input  wire         out_ready,
    output wire [15:0]  out_command_id,
    output wire [{head_id_bits - 1}:0] out_head_id,
    output wire signed [31:0] out_global_max,
    output wire [32:0]  out_exp_sum,
    output wire [{slice_bits - 1}:0] out_slice,
    output wire         out_last,
    output wire [327:0] out_value,
    output wire [2:0]   active_wave_index,
    output wire         emitting,
    output wire [31:0]  cycle_count,
    output wire [31:0]  local_root_completed_count,
    output wire [31:0]  temporal_merge_completed_count,
    output wire [31:0]  emitted_beat_count,
    output wire [31:0]  completed_command_count,
    output wire [31:0]  local_stall_cycles,
    output wire [31:0]  output_stall_cycles,
    output wire         local_tree_protocol_error,
    output wire         temporal_merge_protocol_error,
    output wire         protocol_error
);
  localparam integer PRODUCERS = {producers};
  localparam integer HEAD_ID_BITS = {head_id_bits};
  localparam integer VALUE_SLICES = 16;
  localparam integer PARTIAL_PAYLOAD_BITS = {PARTIAL_PAYLOAD_BITS};
  localparam integer SLICE_BITS = {slice_bits};
  localparam integer PERSISTENT_WAVES = {LOCAL_TEMPORAL_WAVES};

  localparam [1:0] PHASE_COLLECT = 2'd0;
  localparam [1:0] PHASE_EMIT = 2'd1;

  wire local_root_valid_w;
  wire local_root_ready_w;
  wire [15:0] local_root_command_id_w;
  wire [HEAD_ID_BITS-1:0] local_root_head_id_w;
  wire signed [31:0] local_root_global_max_w;
  wire [32:0] local_root_exp_sum_w;
  wire [SLICE_BITS-1:0] local_root_slice_w;
  wire local_root_last_w;
  wire [PARTIAL_PAYLOAD_BITS-1:0] local_root_value_w;
  wire [31:0] local_tree_cycle_count_w;
  wire [31:0] local_tree_root_completed_count_w;
  wire [{(producers - 1) * 32 - 1}:0] local_tree_node_completed_count_unused_w;
  wire [{_clog2(producers) * 32 - 1}:0] local_tree_stage_completed_count_unused_w;
  wire [{producers - 2}:0] local_tree_node_protocol_error_unused_w;
  wire [{_clog2(producers) - 1}:0] local_tree_stage_protocol_error_unused_w;
  wire local_tree_protocol_error_w;

  reg [1:0] phase_q;
  reg [2:0] wave_count_q;
  reg [3:0] emit_index_q;
  reg [31:0] cycle_count_q;
  reg [31:0] emitted_beat_count_q;
  reg [31:0] completed_command_count_q;
  reg [31:0] local_stall_cycles_q;
  reg [31:0] output_stall_cycles_q;
  reg temporal_merge_protocol_error_q;
  reg protocol_error_q;

{state_decl}

  reg [15:0] emit_command_id_r;
  reg [HEAD_ID_BITS-1:0] emit_head_id_r;
  reg signed [31:0] emit_global_max_r;
  reg [32:0] emit_exp_sum_r;
  reg emit_last_r;
  reg [PARTIAL_PAYLOAD_BITS-1:0] emit_value_r;

  wire temporal_left_valid_w;
  wire temporal_left_ready_w;
  wire temporal_right_valid_w;
  wire temporal_right_ready_w;
  wire temporal_out_valid_w;
  wire [15:0] temporal_out_command_id_w;
  wire [HEAD_ID_BITS-1:0] temporal_out_head_id_w;
  wire signed [31:0] temporal_out_global_max_w;
  wire [32:0] temporal_out_exp_sum_w;
  wire [SLICE_BITS-1:0] temporal_out_slice_w;
  wire temporal_out_last_w;
  wire [PARTIAL_PAYLOAD_BITS-1:0] temporal_out_value_w;
  wire [31:0] temporal_merge_completed_count_w;
  wire temporal_merge_protocol_error_w;

  wire collecting_w = (phase_q == PHASE_COLLECT);
  wire emitting_w = (phase_q == PHASE_EMIT);
  wire local_root_fire_w = local_root_valid_w && local_root_ready_w;
  wire temporal_out_fire_w = temporal_out_valid_w;
  wire out_fire_w = out_valid && out_ready;

  assign active_wave_index = wave_count_q;
  assign emitting = emitting_w;
  assign cycle_count = cycle_count_q;
  assign local_root_completed_count = local_tree_root_completed_count_w;
  assign temporal_merge_completed_count = temporal_merge_completed_count_w;
  assign emitted_beat_count = emitted_beat_count_q;
  assign completed_command_count = completed_command_count_q;
  assign local_stall_cycles = local_stall_cycles_q;
  assign output_stall_cycles = output_stall_cycles_q;
  assign local_tree_protocol_error = local_tree_protocol_error_w;
  assign temporal_merge_protocol_error = temporal_merge_protocol_error_q;
  assign protocol_error = protocol_error_q || local_tree_protocol_error_w || temporal_merge_protocol_error_q;
  assign temporal_left_valid_w = collecting_w && (wave_count_q != 3'd0) && local_root_valid_w;
  assign temporal_right_valid_w = temporal_left_valid_w;

  assign local_root_ready_w =
      collecting_w
      && ((wave_count_q == 3'd0) ? 1'b1 : (temporal_left_ready_w && temporal_right_ready_w));

  assign out_valid = emitting_w;
  assign out_command_id = emit_command_id_r;
  assign out_head_id = emit_head_id_r;
  assign out_global_max = emit_global_max_r;
  assign out_exp_sum = emit_exp_sum_r;
  assign out_slice = emit_index_q;
  assign out_last = emit_last_r;
  assign out_value = emit_value_r;

  always @(*) begin
    emit_command_id_r = 16'd0;
    emit_head_id_r = {head_id_bits}'d0;
    emit_global_max_r = 32'sd0;
    emit_exp_sum_r = 33'd0;
    emit_last_r = 1'b0;
    emit_value_r = {PARTIAL_PAYLOAD_BITS}'d0;
    case (emit_index_q)
{emit_case}
      default: begin
        emit_command_id_r = state_command_id_q[15];
        emit_head_id_r = state_head_id_q[15];
        emit_global_max_r = state_global_max_q[15];
        emit_exp_sum_r = state_exp_sum_q[15];
        emit_last_r = state_last_q[15];
        emit_value_r = state_value_q[15];
      end
    endcase
  end

  {reducer_top} u_local_reducer (
      .clk(clk),
      .rst_n(rst_n),
      .leaf_valid(leaf_valid),
      .leaf_ready(leaf_ready),
      .leaf_command_id(leaf_command_id),
      .leaf_head_id(leaf_head_id),
      .leaf_global_max(leaf_global_max),
      .leaf_exp_sum(leaf_exp_sum),
      .leaf_slice(leaf_slice),
      .leaf_last(leaf_last),
      .leaf_value(leaf_value),
      .root_valid(local_root_valid_w),
      .root_ready(local_root_ready_w),
      .root_command_id(local_root_command_id_w),
      .root_head_id(local_root_head_id_w),
      .root_global_max(local_root_global_max_w),
      .root_exp_sum(local_root_exp_sum_w),
      .root_slice(local_root_slice_w),
      .root_last(local_root_last_w),
      .root_value(local_root_value_w),
      .cycle_count(local_tree_cycle_count_w),
      .root_completed_count(local_tree_root_completed_count_w),
      .node_completed_count(local_tree_node_completed_count_unused_w),
      .stage_completed_count(local_tree_stage_completed_count_unused_w),
      .node_protocol_error(local_tree_node_protocol_error_unused_w),
      .stage_protocol_error(local_tree_stage_protocol_error_unused_w),
      .protocol_error(local_tree_protocol_error_w)
  );

  {merge_top} u_temporal_merge (
      .clk(clk),
      .rst_n(rst_n),
      .left_valid(temporal_left_valid_w),
      .left_ready(temporal_left_ready_w),
      .left_command_id(local_root_command_id_w),
      .left_head_id(local_root_head_id_w),
      .left_global_max(local_root_global_max_w),
      .left_exp_sum(local_root_exp_sum_w),
      .left_slice(local_root_slice_w),
      .left_last(local_root_last_w),
      .left_value(local_root_value_w),
      .right_valid(temporal_right_valid_w),
      .right_ready(temporal_right_ready_w),
      .right_command_id(state_command_id_q[local_root_slice_w]),
      .right_head_id(state_head_id_q[local_root_slice_w]),
      .right_global_max(state_global_max_q[local_root_slice_w]),
      .right_exp_sum(state_exp_sum_q[local_root_slice_w]),
      .right_slice(local_root_slice_w),
      .right_last(state_last_q[local_root_slice_w]),
      .right_value(state_value_q[local_root_slice_w]),
      .out_valid(temporal_out_valid_w),
      .out_ready(1'b1),
      .out_command_id(temporal_out_command_id_w),
      .out_head_id(temporal_out_head_id_w),
      .out_global_max(temporal_out_global_max_w),
      .out_exp_sum(temporal_out_exp_sum_w),
      .out_slice(temporal_out_slice_w),
      .out_last(temporal_out_last_w),
      .out_value(temporal_out_value_w),
      .completed_count(temporal_merge_completed_count_w),
      .cycle_count(),
      .protocol_error(temporal_merge_protocol_error_w)
  );

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      phase_q <= PHASE_COLLECT;
      wave_count_q <= 3'd0;
      emit_index_q <= 4'd0;
      cycle_count_q <= 32'd0;
      emitted_beat_count_q <= 32'd0;
      completed_command_count_q <= 32'd0;
      local_stall_cycles_q <= 32'd0;
      output_stall_cycles_q <= 32'd0;
      temporal_merge_protocol_error_q <= 1'b0;
      protocol_error_q <= 1'b0;
{state_reset}
    end else begin
      cycle_count_q <= cycle_count_q + 1'b1;
      if (collecting_w && local_root_valid_w && !local_root_ready_w) begin
        local_stall_cycles_q <= local_stall_cycles_q + 1'b1;
      end
      if (emitting_w && out_valid && !out_ready) begin
        output_stall_cycles_q <= output_stall_cycles_q + 1'b1;
      end
      if (temporal_merge_protocol_error_w) begin
        temporal_merge_protocol_error_q <= 1'b1;
      end
      if (local_tree_protocol_error_w || temporal_merge_protocol_error_w) begin
        protocol_error_q <= 1'b1;
      end

      if (collecting_w && (wave_count_q == 3'd0) && local_root_fire_w) begin
        state_command_id_q[local_root_slice_w] <= local_root_command_id_w;
        state_head_id_q[local_root_slice_w] <= local_root_head_id_w;
        state_global_max_q[local_root_slice_w] <= local_root_global_max_w;
        state_exp_sum_q[local_root_slice_w] <= local_root_exp_sum_w;
        state_last_q[local_root_slice_w] <= local_root_last_w;
        state_value_q[local_root_slice_w] <= local_root_value_w;
        if (local_root_last_w) begin
          wave_count_q <= 3'd1;
        end
      end

      if (collecting_w && (wave_count_q != 3'd0) && temporal_out_fire_w) begin
        state_command_id_q[temporal_out_slice_w] <= temporal_out_command_id_w;
        state_head_id_q[temporal_out_slice_w] <= temporal_out_head_id_w;
        state_global_max_q[temporal_out_slice_w] <= temporal_out_global_max_w;
        state_exp_sum_q[temporal_out_slice_w] <= temporal_out_exp_sum_w;
        state_last_q[temporal_out_slice_w] <= temporal_out_last_w;
        state_value_q[temporal_out_slice_w] <= temporal_out_value_w;
        if (temporal_out_last_w) begin
          if (wave_count_q == (PERSISTENT_WAVES - 1)) begin
            phase_q <= PHASE_EMIT;
            emit_index_q <= 4'd0;
            wave_count_q <= 3'd0;
          end else begin
            wave_count_q <= wave_count_q + 1'b1;
          end
        end
      end

      if (emitting_w && out_fire_w) begin
        emitted_beat_count_q <= emitted_beat_count_q + 1'b1;
        if (emit_index_q == 4'd15) begin
          phase_q <= PHASE_COLLECT;
          emit_index_q <= 4'd0;
          completed_command_count_q <= completed_command_count_q + 1'b1;
        end else begin
          emit_index_q <= emit_index_q + 1'b1;
        end
      end
    end
  end
endmodule
"""


def generate(config: JsonDict, out_dir: Path) -> None:
    params = _validate(json.loads(json.dumps(config)))
    top_name = str(params["top_name"])
    reducer_top = f"{top_name}__local_reducer"
    merge_top = f"{top_name}__temporal_merge"

    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="score32_exact_local_temporal_") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        reducer_dir = temp_dir / "reducer"
        merge_dir = temp_dir / "merge"
        generate_local_reducer(
            {
                "top_name": reducer_top,
                "attention_score32_exact_local_reducer": {
                    "producers": int(params["producers"]),
                    "value_slices": int(params["value_slices"]),
                    "head_id_bits": int(params["head_id_bits"]),
                },
            },
            reducer_dir,
        )
        generate_merge(
            {
                "top_name": merge_top,
                "attention_score32_online_state_merge": {
                    "value_slices": int(params["value_slices"]),
                    "head_id_bits": int(params["head_id_bits"]),
                },
            },
            merge_dir,
        )
        reducer_rtl = (reducer_dir / "top.v").read_text(encoding="utf-8")
        merge_rtl = (merge_dir / "top.v").read_text(encoding="utf-8")
        reducer_manifest = json.loads(
            (reducer_dir / "attention_score32_exact_local_reducer_manifest.json").read_text(encoding="utf-8")
        )
        merge_manifest = json.loads(
            (merge_dir / "attention_score32_online_state_merge_manifest.json").read_text(encoding="utf-8")
        )

    top_text = _top(
        top_name=top_name,
        reducer_top=reducer_top,
        merge_top=merge_top,
        producers=int(params["producers"]),
        head_id_bits=int(params["head_id_bits"]),
    )
    (out_dir / "top.v").write_text(reducer_rtl + "\n\n" + merge_rtl + "\n\n" + top_text + "\n", encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    probe_defaults = config.get("probe_defaults", {})
    if not isinstance(probe_defaults, dict):
        probe_defaults = {}
    service_model = exact_local_temporal_reducer_service_manifest(
        producers=int(params["producers"]),
        waves=int(params["persistent_waves"]),
        heads=int(probe_defaults.get("heads", 1)),
    )
    manifest = {
        "version": 1,
        "generator": "npu/rtlgen/gen_attention_score32_exact_local_temporal_reducer.py",
        "top_name": top_name,
        "semantic_profile": "score32_exact_local_temporal_reducer_v1",
        "producers": int(params["producers"]),
        "value_slices": int(params["value_slices"]),
        "head_id_bits": int(params["head_id_bits"]),
        "persistent_waves": int(params["persistent_waves"]),
        "result_interface": "local_exact_partial_producer_streams_to_single_aggregate_after_8_waves",
        "partial_payload_bits_per_beat": PARTIAL_PAYLOAD_BITS,
        "partial_link_bits_per_beat": PARTIAL_LINK_BITS,
        "equivalence_hash": False,
        "top_pin_bits": _top_pin_bits(
            producers=int(params["producers"]),
            head_id_bits=int(params["head_id_bits"]),
            slice_bits=_clog2(int(params["value_slices"])),
        ),
        "command_schedule_contract": "in_order_leaf_streams_grouped_by_exact_8_wave_temporal_windows",
        "head_mapping_contract": "explicit_head_id_no_tile_or_wave_inference",
        "comparison_baseline_contract": service_model["comparison_baseline_contract"],
        "comparison_cycle_origin": service_model["comparison_cycle_origin"],
        "diagnostic_only_baseline": service_model["diagnostic_only_baseline"],
        "remaining_abstractions": service_model["remaining_abstractions"],
        "service_model": service_model,
        "submodule_manifests": {
            "local_reducer": reducer_manifest,
            "temporal_merge": merge_manifest,
        },
    }
    if isinstance(config.get("probe_defaults"), dict):
        manifest["checked_in_probe_defaults"] = config["probe_defaults"]
    (out_dir / _MANIFEST_NAME).write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
