#!/usr/bin/env python3
"""Generate a finite-buffered exact-partial temporal stream reducer."""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_score32_online_state_merge import (
    FACTORED_H33_L64_MUL_EXACT,
    generate as generate_merge,
)
from npu.sim.perf.attention_exact_partial import (
    HEAD_ID_BITS,
    PARTIAL_LINK_BITS,
    PARTIAL_PAYLOAD_BITS,
    VALUE_SLICES,
)

JsonDict = dict[str, Any]
_CONFIG_KEY = "attention_score32_exact_partial_temporal_stream"
_MANIFEST_NAME = "attention_score32_exact_partial_temporal_stream_manifest.json"
_GENERATOR = "npu/rtlgen/gen_attention_score32_exact_partial_temporal_stream.py"


def _load(path: Path) -> JsonDict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"config must decode to a JSON object: {path}")
    return payload


def _clog2(value: int) -> int:
    resolved = 1
    while (1 << resolved) < max(2, int(value)):
        resolved += 1
    return resolved


def _validate(config: JsonDict) -> JsonDict:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get(_CONFIG_KEY)
    if not top_name or not isinstance(body, dict):
        raise SystemExit(f"config requires top_name and {_CONFIG_KEY}")

    heads = int(body.get("heads", 32))
    value_slices = int(body.get("value_slices", VALUE_SLICES))
    head_id_bits = int(body.get("head_id_bits", HEAD_ID_BITS))
    fifo_depth = int(body.get("fifo_depth", 4))
    sequence_id_bits = int(body.get("sequence_id_bits", 16))
    window_index_bits = int(body.get("window_index_bits", 14))
    window_count_bits = int(body.get("window_count_bits", 15))
    max_window_count = int(body.get("max_window_count", 16384))
    exp_scale_impl = str(body.get("exp_scale_impl", FACTORED_H33_L64_MUL_EXACT)).strip()
    keep_hierarchy = bool(body.get("keep_hierarchy", True))

    if heads != 32:
        raise SystemExit("heads must remain fixed at 32")
    if value_slices != VALUE_SLICES:
        raise SystemExit("value_slices must remain fixed at 16")
    if head_id_bits != HEAD_ID_BITS:
        raise SystemExit("head_id_bits must remain fixed at 5")
    if sequence_id_bits != 16:
        raise SystemExit("sequence_id_bits must remain fixed at 16")
    if window_index_bits != 14:
        raise SystemExit("window_index_bits must remain fixed at 14")
    if window_count_bits != 15:
        raise SystemExit("window_count_bits must remain fixed at 15")
    if max_window_count != 16384:
        raise SystemExit("max_window_count must remain fixed at 16384")
    if fifo_depth < 2 or fifo_depth > 16 or fifo_depth & (fifo_depth - 1):
        raise SystemExit("fifo_depth must be a power of two in [2, 16]")

    return {
        "top_name": top_name,
        "heads": heads,
        "value_slices": value_slices,
        "head_id_bits": head_id_bits,
        "fifo_depth": fifo_depth,
        "sequence_id_bits": sequence_id_bits,
        "window_index_bits": window_index_bits,
        "window_count_bits": window_count_bits,
        "max_window_count": max_window_count,
        "exp_scale_impl": exp_scale_impl,
        "keep_hierarchy": keep_hierarchy,
    }


def _reset_memory(prefix: str, width: str, count: int, value: str) -> str:
    return "\n".join(f"      {prefix}[{index}] <= {width}'d{value};" for index in range(count))


def _reset_signed_memory(prefix: str, width: str, count: int, value: str) -> str:
    return "\n".join(f"      {prefix}[{index}] <= {width}'sd{value};" for index in range(count))


def _reset_bit_memory(prefix: str, count: int, value: str) -> str:
    return "\n".join(f"      {prefix}[{index}] <= 1'b{value};" for index in range(count))


def _lowest_pending_function() -> str:
    return """  function automatic [HEAD_ID_BITS-1:0] lowest_pending_head;
    input [HEADS-1:0] pending;
    integer scan;
    begin
      lowest_pending_head = {HEAD_ID_BITS{1'b0}};
      for (scan = HEADS - 1; scan >= 0; scan = scan - 1) begin
        if (pending[scan]) lowest_pending_head = scan[HEAD_ID_BITS-1:0];
      end
    end
  endfunction"""


def _top(*, top_name: str, merge_top: str, fifo_depth: int) -> str:
    fifo_ptr_bits = _clog2(fifo_depth)
    slice_bits = _clog2(VALUE_SLICES)
    state_slots = 32 * VALUE_SLICES
    return f"""// Auto-generated by {_GENERATOR}
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         in_valid,
    output wire         in_ready,
    input  wire [15:0]  in_sequence_id,
    input  wire [4:0]   in_head_id,
    input  wire [13:0]  in_window_index,
    input  wire [14:0]  in_window_count,
    input  wire [15:0]  in_command_id,
    input  wire signed [31:0] in_global_max,
    input  wire [32:0]  in_exp_sum,
    input  wire [3:0]   in_slice,
    input  wire         in_last,
    input  wire [327:0] in_value,
    output wire         out_valid,
    input  wire         out_ready,
    output wire [15:0]  out_sequence_id,
    output wire [4:0]   out_head_id,
    output wire [14:0]  out_window_count,
    output wire [15:0]  out_command_id,
    output wire signed [31:0] out_global_max,
    output wire [32:0]  out_exp_sum,
    output wire [3:0]   out_slice,
    output wire         out_last,
    output wire [327:0] out_value,
    output wire [31:0]  cycle_count,
    output wire [31:0]  input_accepted_count,
    output wire [31:0]  merge_completed_count,
    output wire [31:0]  emitted_beat_count,
    output wire [31:0]  completed_head_count,
    output wire [31:0]  fifo_full_stall_cycles,
    output wire [31:0]  output_stall_cycles,
    output wire [{fifo_ptr_bits}:0] fifo_level,
    output wire         protocol_error
);
  localparam integer HEADS = 32;
  localparam integer HEAD_ID_BITS = {HEAD_ID_BITS};
  localparam integer VALUE_SLICES = {VALUE_SLICES};
  localparam integer SLICE_BITS = {slice_bits};
  localparam integer PARTIAL_PAYLOAD_BITS = {PARTIAL_PAYLOAD_BITS};
  localparam integer FIFO_DEPTH = {fifo_depth};
  localparam integer FIFO_PTR_BITS = {fifo_ptr_bits};
  localparam integer STATE_SLOTS = HEADS * VALUE_SLICES;
  localparam [SLICE_BITS-1:0] LAST_SLICE = {slice_bits}'d{VALUE_SLICES - 1};
  localparam [14:0] MAX_WINDOW_COUNT = 15'd16384;

  reg [15:0] fifo_sequence_id_q [0:FIFO_DEPTH-1];
  reg [HEAD_ID_BITS-1:0] fifo_head_id_q [0:FIFO_DEPTH-1];
  reg [13:0] fifo_window_index_q [0:FIFO_DEPTH-1];
  reg [14:0] fifo_window_count_q [0:FIFO_DEPTH-1];
  reg [15:0] fifo_command_id_q [0:FIFO_DEPTH-1];
  reg signed [31:0] fifo_global_max_q [0:FIFO_DEPTH-1];
  reg [32:0] fifo_exp_sum_q [0:FIFO_DEPTH-1];
  reg [SLICE_BITS-1:0] fifo_slice_q [0:FIFO_DEPTH-1];
  reg fifo_last_q [0:FIFO_DEPTH-1];
  reg [PARTIAL_PAYLOAD_BITS-1:0] fifo_value_q [0:FIFO_DEPTH-1];
  reg [FIFO_PTR_BITS-1:0] fifo_rd_ptr_q;
  reg [FIFO_PTR_BITS-1:0] fifo_wr_ptr_q;
  reg [FIFO_PTR_BITS:0] fifo_count_q;

  reg head_active_q [0:HEADS-1];
  reg [15:0] head_sequence_id_q [0:HEADS-1];
  reg [15:0] head_command_id_q [0:HEADS-1];
  reg [14:0] head_window_count_q [0:HEADS-1];
  reg [14:0] head_next_window_q [0:HEADS-1];
  reg [SLICE_BITS-1:0] head_expected_slice_q [0:HEADS-1];

  reg state_valid_q [0:STATE_SLOTS-1];
  reg signed [31:0] state_global_max_q [0:STATE_SLOTS-1];
  reg [32:0] state_exp_sum_q [0:STATE_SLOTS-1];
  reg [PARTIAL_PAYLOAD_BITS-1:0] state_value_q [0:STATE_SLOTS-1];

  reg [HEADS-1:0] emit_pending_q;
  reg emit_active_q;
  reg [HEAD_ID_BITS-1:0] emit_head_q;
  reg [SLICE_BITS-1:0] emit_slice_q;

  reg merge_busy_q;
  reg [15:0] merge_sequence_id_q;
  reg [14:0] merge_window_index_q;
  reg [14:0] merge_window_count_q;

  reg [31:0] cycle_count_q;
  reg [31:0] input_accepted_count_q;
  reg [31:0] emitted_beat_count_q;
  reg [31:0] completed_head_count_q;
  reg [31:0] fifo_full_stall_cycles_q;
  reg [31:0] output_stall_cycles_q;
  reg protocol_error_q;

  integer reset_index;

  wire fifo_empty_w = (fifo_count_q == {{(FIFO_PTR_BITS + 1){{1'b0}}}});
  wire fifo_full_w = (fifo_count_q == FIFO_DEPTH[FIFO_PTR_BITS:0]);
  wire push_w = in_valid && in_ready;

  wire [15:0] front_sequence_id_w = fifo_sequence_id_q[fifo_rd_ptr_q];
  wire [HEAD_ID_BITS-1:0] front_head_id_w = fifo_head_id_q[fifo_rd_ptr_q];
  wire [13:0] front_window_index_w = fifo_window_index_q[fifo_rd_ptr_q];
  wire [14:0] front_window_count_w = fifo_window_count_q[fifo_rd_ptr_q];
  wire [15:0] front_command_id_w = fifo_command_id_q[fifo_rd_ptr_q];
  wire signed [31:0] front_global_max_w = fifo_global_max_q[fifo_rd_ptr_q];
  wire [32:0] front_exp_sum_w = fifo_exp_sum_q[fifo_rd_ptr_q];
  wire [SLICE_BITS-1:0] front_slice_w = fifo_slice_q[fifo_rd_ptr_q];
  wire front_last_w = fifo_last_q[fifo_rd_ptr_q];
  wire [PARTIAL_PAYLOAD_BITS-1:0] front_value_w = fifo_value_q[fifo_rd_ptr_q];
  wire [8:0] front_state_slot_w = {{front_head_id_w, front_slice_w}};
  wire front_first_for_head_w = !head_active_q[front_head_id_w];
  wire front_needs_merge_w = head_active_q[front_head_id_w] && (front_window_index_w != 14'd0);
  wire process_allowed_w =
      !protocol_error_q
      && !emit_active_q
      && !merge_busy_q
      && (emit_pending_q == {{HEADS{{1'b0}}}});
  wire front_last_semantic_error_w = (front_last_w != (front_slice_w == LAST_SLICE));
  wire front_count_error_w = (front_window_count_w == 15'd0) || (front_window_count_w > MAX_WINDOW_COUNT);
  wire front_new_head_error_w =
      front_first_for_head_w
      && ((front_window_index_w != 14'd0) || (front_slice_w != {{SLICE_BITS{{1'b0}}}}));
  wire front_active_head_error_w =
      !front_first_for_head_w
      && ((front_sequence_id_w != head_sequence_id_q[front_head_id_w])
          || (front_command_id_w != head_command_id_q[front_head_id_w])
          || (front_window_count_w != head_window_count_q[front_head_id_w])
          || ({{1'b0, front_window_index_w}} != head_next_window_q[front_head_id_w])
          || (front_slice_w != head_expected_slice_q[front_head_id_w]));
  wire front_missing_state_error_w = front_needs_merge_w && !state_valid_q[front_state_slot_w];
  wire front_protocol_error_w =
      !fifo_empty_w
      && (front_last_semantic_error_w
          || front_count_error_w
          || front_new_head_error_w
          || front_active_head_error_w
          || front_missing_state_error_w);
  wire front_direct_store_w = !fifo_empty_w && process_allowed_w && !front_protocol_error_w && !front_needs_merge_w;

  wire merge_left_ready_w;
  wire merge_right_ready_w;
  wire merge_out_valid_w;
  wire [15:0] merge_out_command_id_w;
  wire [HEAD_ID_BITS-1:0] merge_out_head_id_w;
  wire signed [31:0] merge_out_global_max_w;
  wire [32:0] merge_out_exp_sum_w;
  wire [SLICE_BITS-1:0] merge_out_slice_w;
  wire merge_out_last_w;
  wire [PARTIAL_PAYLOAD_BITS-1:0] merge_out_value_w;
  wire [31:0] merge_completed_count_w;
  wire merge_protocol_error_w;
  wire merge_input_valid_w =
      !fifo_empty_w
      && process_allowed_w
      && !front_protocol_error_w
      && front_needs_merge_w
      && !merge_busy_q;
  wire merge_launch_fire_w = merge_input_valid_w && merge_left_ready_w && merge_right_ready_w;
  wire merge_out_fire_w = merge_out_valid_w;
  wire pop_w = front_direct_store_w || merge_launch_fire_w || (!fifo_empty_w && process_allowed_w && front_protocol_error_w);

  wire [8:0] merge_out_state_slot_w = {{merge_out_head_id_w, merge_out_slice_w}};
  wire merge_out_window_complete_w = merge_out_last_w && (merge_window_index_q == (merge_window_count_q - 15'd1));
  wire direct_window_complete_w = front_last_w && ({{1'b0, front_window_index_w}} == (front_window_count_w - 15'd1));
  wire emit_fire_w = out_valid && out_ready;
  wire [HEAD_ID_BITS-1:0] next_emit_head_w = lowest_pending_head(emit_pending_q);
  wire [8:0] emit_state_slot_w = {{emit_head_q, emit_slice_q}};

  assign in_ready = !fifo_full_w && !protocol_error_q;
  assign out_valid = emit_active_q && !protocol_error_q;
  assign out_sequence_id = head_sequence_id_q[emit_head_q];
  assign out_head_id = emit_head_q;
  assign out_window_count = head_window_count_q[emit_head_q];
  assign out_command_id = head_command_id_q[emit_head_q];
  assign out_global_max = state_global_max_q[emit_state_slot_w];
  assign out_exp_sum = state_exp_sum_q[emit_state_slot_w];
  assign out_slice = emit_slice_q;
  assign out_last = (emit_slice_q == LAST_SLICE);
  assign out_value = state_value_q[emit_state_slot_w];
  assign cycle_count = cycle_count_q;
  assign input_accepted_count = input_accepted_count_q;
  assign merge_completed_count = merge_completed_count_w;
  assign emitted_beat_count = emitted_beat_count_q;
  assign completed_head_count = completed_head_count_q;
  assign fifo_full_stall_cycles = fifo_full_stall_cycles_q;
  assign output_stall_cycles = output_stall_cycles_q;
  assign fifo_level = fifo_count_q;
  assign protocol_error = protocol_error_q || merge_protocol_error_w;

{_lowest_pending_function()}

  {merge_top} u_pair_merge (
      .clk(clk),
      .rst_n(rst_n),
      .left_valid(merge_input_valid_w),
      .left_ready(merge_left_ready_w),
      .left_command_id(front_command_id_w),
      .left_head_id(front_head_id_w),
      .left_global_max(front_global_max_w),
      .left_exp_sum(front_exp_sum_w),
      .left_slice(front_slice_w),
      .left_last(front_last_w),
      .left_value(front_value_w),
      .right_valid(merge_input_valid_w),
      .right_ready(merge_right_ready_w),
      .right_command_id(head_command_id_q[front_head_id_w]),
      .right_head_id(front_head_id_w),
      .right_global_max(state_global_max_q[front_state_slot_w]),
      .right_exp_sum(state_exp_sum_q[front_state_slot_w]),
      .right_slice(front_slice_w),
      .right_last(front_last_w),
      .right_value(state_value_q[front_state_slot_w]),
      .out_valid(merge_out_valid_w),
      .out_ready(1'b1),
      .out_command_id(merge_out_command_id_w),
      .out_head_id(merge_out_head_id_w),
      .out_global_max(merge_out_global_max_w),
      .out_exp_sum(merge_out_exp_sum_w),
      .out_slice(merge_out_slice_w),
      .out_last(merge_out_last_w),
      .out_value(merge_out_value_w),
      .completed_count(merge_completed_count_w),
      .cycle_count(),
      .protocol_error(merge_protocol_error_w)
  );

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      fifo_rd_ptr_q <= {{FIFO_PTR_BITS{{1'b0}}}};
      fifo_wr_ptr_q <= {{FIFO_PTR_BITS{{1'b0}}}};
      fifo_count_q <= {{(FIFO_PTR_BITS + 1){{1'b0}}}};
      emit_pending_q <= {{HEADS{{1'b0}}}};
      emit_active_q <= 1'b0;
      emit_head_q <= {{HEAD_ID_BITS{{1'b0}}}};
      emit_slice_q <= {{SLICE_BITS{{1'b0}}}};
      merge_busy_q <= 1'b0;
      merge_sequence_id_q <= 16'd0;
      merge_window_index_q <= 15'd0;
      merge_window_count_q <= 15'd0;
      cycle_count_q <= 32'd0;
      input_accepted_count_q <= 32'd0;
      emitted_beat_count_q <= 32'd0;
      completed_head_count_q <= 32'd0;
      fifo_full_stall_cycles_q <= 32'd0;
      output_stall_cycles_q <= 32'd0;
      protocol_error_q <= 1'b0;
      for (reset_index = 0; reset_index < FIFO_DEPTH; reset_index = reset_index + 1) begin
        fifo_sequence_id_q[reset_index] <= 16'd0;
        fifo_head_id_q[reset_index] <= {{HEAD_ID_BITS{{1'b0}}}};
        fifo_window_index_q[reset_index] <= 14'd0;
        fifo_window_count_q[reset_index] <= 15'd0;
        fifo_command_id_q[reset_index] <= 16'd0;
        fifo_global_max_q[reset_index] <= 32'sd0;
        fifo_exp_sum_q[reset_index] <= 33'd0;
        fifo_slice_q[reset_index] <= {{SLICE_BITS{{1'b0}}}};
        fifo_last_q[reset_index] <= 1'b0;
        fifo_value_q[reset_index] <= {{PARTIAL_PAYLOAD_BITS{{1'b0}}}};
      end
      for (reset_index = 0; reset_index < HEADS; reset_index = reset_index + 1) begin
        head_active_q[reset_index] <= 1'b0;
        head_sequence_id_q[reset_index] <= 16'd0;
        head_command_id_q[reset_index] <= 16'd0;
        head_window_count_q[reset_index] <= 15'd0;
        head_next_window_q[reset_index] <= 15'd0;
        head_expected_slice_q[reset_index] <= {{SLICE_BITS{{1'b0}}}};
      end
      for (reset_index = 0; reset_index < STATE_SLOTS; reset_index = reset_index + 1) begin
        state_valid_q[reset_index] <= 1'b0;
        state_global_max_q[reset_index] <= 32'sd0;
        state_exp_sum_q[reset_index] <= 33'd0;
        state_value_q[reset_index] <= {{PARTIAL_PAYLOAD_BITS{{1'b0}}}};
      end
    end else begin
      cycle_count_q <= cycle_count_q + 1'b1;
      if (in_valid && !in_ready) fifo_full_stall_cycles_q <= fifo_full_stall_cycles_q + 1'b1;
      if (out_valid && !out_ready) output_stall_cycles_q <= output_stall_cycles_q + 1'b1;
      if (merge_protocol_error_w) protocol_error_q <= 1'b1;

      if (push_w) begin
        fifo_sequence_id_q[fifo_wr_ptr_q] <= in_sequence_id;
        fifo_head_id_q[fifo_wr_ptr_q] <= in_head_id;
        fifo_window_index_q[fifo_wr_ptr_q] <= in_window_index;
        fifo_window_count_q[fifo_wr_ptr_q] <= in_window_count;
        fifo_command_id_q[fifo_wr_ptr_q] <= in_command_id;
        fifo_global_max_q[fifo_wr_ptr_q] <= in_global_max;
        fifo_exp_sum_q[fifo_wr_ptr_q] <= in_exp_sum;
        fifo_slice_q[fifo_wr_ptr_q] <= in_slice;
        fifo_last_q[fifo_wr_ptr_q] <= in_last;
        fifo_value_q[fifo_wr_ptr_q] <= in_value;
        fifo_wr_ptr_q <= fifo_wr_ptr_q + 1'b1;
        input_accepted_count_q <= input_accepted_count_q + 1'b1;
      end

      if (pop_w) begin
        fifo_rd_ptr_q <= fifo_rd_ptr_q + 1'b1;
      end
      case ({{push_w, pop_w}})
        2'b10: fifo_count_q <= fifo_count_q + 1'b1;
        2'b01: fifo_count_q <= fifo_count_q - 1'b1;
        default: fifo_count_q <= fifo_count_q;
      endcase

      if (!fifo_empty_w && process_allowed_w && front_protocol_error_w) begin
        protocol_error_q <= 1'b1;
      end

      if (front_direct_store_w) begin
        if (!head_active_q[front_head_id_w]) begin
          head_active_q[front_head_id_w] <= 1'b1;
          head_sequence_id_q[front_head_id_w] <= front_sequence_id_w;
          head_command_id_q[front_head_id_w] <= front_command_id_w;
          head_window_count_q[front_head_id_w] <= front_window_count_w;
          head_next_window_q[front_head_id_w] <= 15'd0;
          head_expected_slice_q[front_head_id_w] <= {{SLICE_BITS{{1'b0}}}};
        end
        state_valid_q[front_state_slot_w] <= 1'b1;
        state_global_max_q[front_state_slot_w] <= front_global_max_w;
        state_exp_sum_q[front_state_slot_w] <= front_exp_sum_w;
        state_value_q[front_state_slot_w] <= front_value_w;
        if (front_last_w) begin
          head_expected_slice_q[front_head_id_w] <= {{SLICE_BITS{{1'b0}}}};
          head_next_window_q[front_head_id_w] <= {{1'b0, front_window_index_w}} + 15'd1;
          if (direct_window_complete_w) emit_pending_q[front_head_id_w] <= 1'b1;
        end else begin
          head_expected_slice_q[front_head_id_w] <= front_slice_w + 1'b1;
        end
      end

      if (merge_launch_fire_w) begin
        merge_busy_q <= 1'b1;
        merge_sequence_id_q <= front_sequence_id_w;
        merge_window_index_q <= {{1'b0, front_window_index_w}};
        merge_window_count_q <= front_window_count_w;
      end
      if (merge_out_fire_w) begin
        merge_busy_q <= 1'b0;
        state_valid_q[merge_out_state_slot_w] <= 1'b1;
        state_global_max_q[merge_out_state_slot_w] <= merge_out_global_max_w;
        state_exp_sum_q[merge_out_state_slot_w] <= merge_out_exp_sum_w;
        state_value_q[merge_out_state_slot_w] <= merge_out_value_w;
        if (merge_out_last_w) begin
          head_expected_slice_q[merge_out_head_id_w] <= {{SLICE_BITS{{1'b0}}}};
          head_next_window_q[merge_out_head_id_w] <= merge_window_index_q + 15'd1;
          if (merge_out_window_complete_w) emit_pending_q[merge_out_head_id_w] <= 1'b1;
        end else begin
          head_expected_slice_q[merge_out_head_id_w] <= merge_out_slice_w + 1'b1;
        end
      end

      if (!emit_active_q && (emit_pending_q != {{HEADS{{1'b0}}}}) && !protocol_error_q) begin
        emit_active_q <= 1'b1;
        emit_head_q <= next_emit_head_w;
        emit_slice_q <= {{SLICE_BITS{{1'b0}}}};
        emit_pending_q[next_emit_head_w] <= 1'b0;
      end else if (emit_fire_w) begin
        emitted_beat_count_q <= emitted_beat_count_q + 1'b1;
        if (emit_slice_q == LAST_SLICE) begin
          emit_active_q <= 1'b0;
          completed_head_count_q <= completed_head_count_q + 1'b1;
          head_active_q[emit_head_q] <= 1'b0;
          head_next_window_q[emit_head_q] <= 15'd0;
          head_expected_slice_q[emit_head_q] <= {{SLICE_BITS{{1'b0}}}};
        end else begin
          emit_slice_q <= emit_slice_q + 1'b1;
        end
      end
    end
  end
endmodule
"""


def _top_pin_bits(*, fifo_depth: int) -> int:
    input_bits = 1 + 16 + HEAD_ID_BITS + 14 + 15 + 16 + 32 + 33 + _clog2(VALUE_SLICES) + 1 + PARTIAL_PAYLOAD_BITS
    output_bits = 1 + 16 + HEAD_ID_BITS + 15 + 16 + 32 + 33 + _clog2(VALUE_SLICES) + 1 + PARTIAL_PAYLOAD_BITS
    monitor_bits = (7 * 32) + (_clog2(fifo_depth) + 1) + 1
    return 2 + input_bits + output_bits + monitor_bits


def generate(config: JsonDict, out_dir: Path) -> None:
    params = _validate(json.loads(json.dumps(config)))
    top_name = str(params["top_name"])
    merge_top = f"{top_name}__pair_merge"
    out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="score32_exact_partial_temporal_stream_") as temp_dir_name:
        merge_dir = Path(temp_dir_name) / "merge"
        generate_merge(
            {
                "top_name": merge_top,
                "attention_score32_online_state_merge": {
                    "value_slices": int(params["value_slices"]),
                    "head_id_bits": int(params["head_id_bits"]),
                    "exp_scale_impl": str(params["exp_scale_impl"]),
                    "keep_hierarchy": bool(params["keep_hierarchy"]),
                },
            },
            merge_dir,
        )
        merge_rtl = (merge_dir / "top.v").read_text(encoding="utf-8")
        merge_manifest = json.loads(
            (merge_dir / "attention_score32_online_state_merge_manifest.json").read_text(encoding="utf-8")
        )

    (out_dir / "top.v").write_text(
        merge_rtl
        + "\n\n"
        + _top(top_name=top_name, merge_top=merge_top, fifo_depth=int(params["fifo_depth"]))
        + "\n",
        encoding="utf-8",
    )
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    manifest = {
        "version": 1,
        "top_name": top_name,
        "generator": _GENERATOR,
        "semantic_profile": "score32_exact_partial_temporal_stream_v1",
        "heads": int(params["heads"]),
        "value_slices": int(params["value_slices"]),
        "head_id_bits": int(params["head_id_bits"]),
        "sequence_id_bits": int(params["sequence_id_bits"]),
        "window_index_bits": int(params["window_index_bits"]),
        "window_count_bits": int(params["window_count_bits"]),
        "max_window_count": int(params["max_window_count"]),
        "fifo_depth": int(params["fifo_depth"]),
        "fifo_depth_contract": "power_of_two_depth_2_to_16_ready_valid_input_buffer",
        "partial_payload_bits_per_beat": PARTIAL_PAYLOAD_BITS,
        "partial_link_bits_per_input_beat": PARTIAL_LINK_BITS + 16 + 14 + 15,
        "result_interface": "ready_valid_exact_partial_temporal_head_slice_stream",
        "equivalence_hash": False,
        "exp_scale_impl": str(params["exp_scale_impl"]),
        "command_schedule_contract": (
            "strict_per_head_ordered_windows_and_slices_one_active_sequence_per_head_emit_16_beats_on_completion"
        ),
        "fail_closed_protocol_error": True,
        "remaining_abstractions": [
            "upstream_service_command_metadata_binding",
            "service_to_temporal_reducer_clock_domain_crossing",
            "downstream_full_context_final_normalizer",
            "physical_sram_macro_mapping_for_persistent_state",
            "physical_ppa",
        ],
        "top_pin_bits": _top_pin_bits(fifo_depth=int(params["fifo_depth"])),
        "submodule_manifests": {"pair_merge": merge_manifest},
    }
    if isinstance(config.get("probe_defaults"), dict):
        manifest["checked_in_probe_defaults"] = config["probe_defaults"]
    (out_dir / _MANIFEST_NAME).write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
