#!/usr/bin/env python3
"""Generate an exact streamed root finalizer for score32 partial state."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: dict[str, Any]) -> dict[str, int | str]:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get("attention_score32_exact_root_finalizer")
    if not top_name or not isinstance(body, dict):
        raise SystemExit("config requires top_name and attention_score32_exact_root_finalizer")
    value_slices = int(body.get("value_slices", 16))
    head_id_bits = int(body.get("head_id_bits", 5))
    divider_lanes = int(body.get("divider_lanes", 8))
    if value_slices < 1 or value_slices > 16 or (value_slices & (value_slices - 1)):
        raise SystemExit("value_slices must be a power of two in [1, 16]")
    if head_id_bits < 1 or head_id_bits > 8:
        raise SystemExit("head_id_bits must be in [1, 8]")
    if divider_lanes not in {1, 2, 4, 8}:
        raise SystemExit("divider_lanes must be one of 1, 2, 4, 8")
    return {
        "top_name": top_name,
        "value_slices": value_slices,
        "head_id_bits": head_id_bits,
        "divider_lanes": divider_lanes,
    }


def _top(*, top_name: str, value_slices: int, head_id_bits: int, divider_lanes: int) -> str:
    slice_bits = _clog2(value_slices)
    group_count = 8 // divider_lanes
    group_bits = _clog2(group_count)
    return f"""// Auto-generated by npu/rtlgen/gen_attention_score32_exact_root_finalizer.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         in_valid,
    output wire         in_ready,
    input  wire [15:0]  in_command_id,
    input  wire [{head_id_bits - 1}:0] in_head_id,
    input  wire [32:0]  in_exp_sum,
    input  wire [{slice_bits - 1}:0] in_slice,
    input  wire         in_last,
    input  wire [327:0] in_value,
    output wire         out_valid,
    input  wire         out_ready,
    output wire [15:0]  out_command_id,
    output wire [{head_id_bits - 1}:0] out_head_id,
    output wire [{slice_bits - 1}:0] out_slice,
    output wire         out_last,
    output wire [319:0] out_value,
    output reg  [31:0]  accepted_count,
    output reg  [31:0]  completed_count,
    output reg  [31:0]  cycle_count,
    output wire         protocol_error
);
  localparam integer VALUE_SLICES = {value_slices};
  localparam integer SLICE_BITS = {slice_bits};
  localparam integer HEAD_ID_BITS = {head_id_bits};
  localparam integer DIVIDER_LANES = {divider_lanes};
  localparam integer GROUP_COUNT = {group_count};
  localparam integer GROUP_BITS = {group_bits};
  localparam [GROUP_BITS-1:0] LAST_GROUP = GROUP_BITS'(GROUP_COUNT - 1);
  localparam integer NUMERATOR_BITS = 41;
  localparam integer FINAL_VALUE_BITS = 40;
  localparam integer DIVIDEND_BITS = 57;
  localparam integer DIVIDE_ITERATIONS = 57;
  localparam [{slice_bits - 1}:0] LAST_SLICE = {slice_bits}'d{value_slices - 1};
  localparam [1:0] IDLE = 2'd0, DIVIDE = 2'd1, OUTPUT = 2'd2;

  reg [1:0] state_q;
  reg [GROUP_BITS-1:0] group_index_q;
  reg [5:0] div_bit_count_q;
  reg [15:0] command_id_q;
  reg [HEAD_ID_BITS-1:0] head_id_q;
  reg [SLICE_BITS-1:0] slice_q;
  reg last_q;
  reg [32:0] exp_sum_q;
  reg [327:0] input_value_q;
  reg [319:0] out_value_q;
  reg out_valid_q;
  reg protocol_error_q;
  reg lane_sign_q [0:DIVIDER_LANES-1];
  reg [DIVIDEND_BITS-1:0] lane_quotient_q [0:DIVIDER_LANES-1];
  reg [33:0] lane_remainder_q [0:DIVIDER_LANES-1];
  reg signed [40:0] lane_numerator_r;
  reg [33:0] remainder_shift_r;
  reg [33:0] remainder_next_r;
  reg [DIVIDEND_BITS-1:0] quotient_shift_r;
  reg [DIVIDEND_BITS-1:0] quotient_next_r;
  reg [39:0] lane_output_r;
  integer lane_index;
  integer source_lane_index;
  integer next_group_index_r;

  wire input_last_semantic_error = in_last != (in_slice == LAST_SLICE);

  assign in_ready = (state_q == IDLE) && !out_valid_q;
  assign out_valid = out_valid_q;
  assign out_command_id = command_id_q;
  assign out_head_id = head_id_q;
  assign out_slice = slice_q;
  assign out_last = last_q;
  assign out_value = out_value_q;
  assign protocol_error = protocol_error_q;

  function automatic [DIVIDEND_BITS-1:0] rounded_dividend;
    input signed [40:0] numerator_in;
    input [32:0] exp_sum_in;
    reg [40:0] magnitude;
    begin
      magnitude = numerator_in[40] ? (~numerator_in[40:0]) + 1'b1 : numerator_in[40:0];
      rounded_dividend =
          ({{magnitude, 16'd0}} - {{{{16{{1'b0}}}}, magnitude}})
          + {{{{24{{1'b0}}}}, (exp_sum_in >> 1)}};
    end
  endfunction

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state_q <= IDLE;
      group_index_q <= {{GROUP_BITS{{1'b0}}}};
      div_bit_count_q <= 6'd0;
      command_id_q <= 16'd0;
      head_id_q <= {{HEAD_ID_BITS{{1'b0}}}};
      slice_q <= {{SLICE_BITS{{1'b0}}}};
      last_q <= 1'b0;
      exp_sum_q <= 33'd0;
      input_value_q <= 328'd0;
      out_value_q <= 320'd0;
      out_valid_q <= 1'b0;
      protocol_error_q <= 1'b0;
      accepted_count <= 32'd0;
      completed_count <= 32'd0;
      cycle_count <= 32'd0;
      for (lane_index = 0; lane_index < DIVIDER_LANES; lane_index = lane_index + 1) begin
        lane_sign_q[lane_index] <= 1'b0;
        lane_quotient_q[lane_index] <= {{DIVIDEND_BITS{{1'b0}}}};
        lane_remainder_q[lane_index] <= 34'd0;
      end
    end else begin
      cycle_count <= cycle_count + 1'b1;
      case (state_q)
        IDLE: begin
          if (in_valid && in_ready) begin
            accepted_count <= accepted_count + 1'b1;
            command_id_q <= in_command_id;
            head_id_q <= in_head_id;
            exp_sum_q <= in_exp_sum;
            slice_q <= in_slice;
            last_q <= in_last;
            input_value_q <= in_value;
            out_value_q <= 320'd0;
            if (input_last_semantic_error) begin
              protocol_error_q <= 1'b1;
            end
            if (in_exp_sum == 33'd0) begin
              protocol_error_q <= 1'b1;
              out_valid_q <= 1'b1;
              state_q <= OUTPUT;
            end else begin
              group_index_q <= {{GROUP_BITS{{1'b0}}}};
              div_bit_count_q <= DIVIDE_ITERATIONS[5:0];
              for (lane_index = 0; lane_index < DIVIDER_LANES; lane_index = lane_index + 1) begin
                source_lane_index = lane_index;
                lane_numerator_r = $signed(in_value[(source_lane_index * NUMERATOR_BITS) +: NUMERATOR_BITS]);
                lane_sign_q[lane_index] <= lane_numerator_r[40];
                lane_quotient_q[lane_index] <= rounded_dividend(lane_numerator_r, in_exp_sum);
                lane_remainder_q[lane_index] <= 34'd0;
              end
              state_q <= DIVIDE;
            end
          end
        end
        DIVIDE: begin
          if (div_bit_count_q == 6'd1) begin
            for (lane_index = 0; lane_index < DIVIDER_LANES; lane_index = lane_index + 1) begin
              remainder_shift_r = {{lane_remainder_q[lane_index][32:0], lane_quotient_q[lane_index][56]}};
              quotient_shift_r = {{lane_quotient_q[lane_index][55:0], 1'b0}};
              if (remainder_shift_r >= {{1'b0, exp_sum_q}}) begin
                remainder_next_r = remainder_shift_r - {{1'b0, exp_sum_q}};
                quotient_next_r = quotient_shift_r | 57'd1;
              end else begin
                remainder_next_r = remainder_shift_r;
                quotient_next_r = quotient_shift_r;
              end
              source_lane_index = (group_index_q * DIVIDER_LANES) + lane_index;
              if (quotient_next_r[56:40] != 17'd0) begin
                protocol_error_q <= 1'b1;
                lane_output_r = lane_sign_q[lane_index] ? 40'h8000000000 : 40'h7fffffffff;
              end else if (!lane_sign_q[lane_index] && quotient_next_r[39]) begin
                protocol_error_q <= 1'b1;
                lane_output_r = 40'h7fffffffff;
              end else if (lane_sign_q[lane_index]) begin
                lane_output_r = (~quotient_next_r[39:0]) + 1'b1;
              end else begin
                lane_output_r = quotient_next_r[39:0];
              end
              out_value_q[(source_lane_index * FINAL_VALUE_BITS) +: FINAL_VALUE_BITS] <= lane_output_r;
            end
            if (group_index_q == LAST_GROUP) begin
              out_valid_q <= 1'b1;
              state_q <= OUTPUT;
            end else begin
              next_group_index_r = {{{{{32 - group_bits}{{1'b0}}}}, group_index_q}};
              next_group_index_r = next_group_index_r + 1;
              group_index_q <= group_index_q + 1'b1;
              div_bit_count_q <= DIVIDE_ITERATIONS[5:0];
              for (lane_index = 0; lane_index < DIVIDER_LANES; lane_index = lane_index + 1) begin
                source_lane_index = (next_group_index_r * DIVIDER_LANES) + lane_index;
                lane_numerator_r = $signed(input_value_q[(source_lane_index * NUMERATOR_BITS) +: NUMERATOR_BITS]);
                lane_sign_q[lane_index] <= lane_numerator_r[40];
                lane_quotient_q[lane_index] <= rounded_dividend(lane_numerator_r, exp_sum_q);
                lane_remainder_q[lane_index] <= 34'd0;
              end
            end
          end else begin
            div_bit_count_q <= div_bit_count_q - 1'b1;
            for (lane_index = 0; lane_index < DIVIDER_LANES; lane_index = lane_index + 1) begin
              remainder_shift_r = {{lane_remainder_q[lane_index][32:0], lane_quotient_q[lane_index][56]}};
              quotient_shift_r = {{lane_quotient_q[lane_index][55:0], 1'b0}};
              if (remainder_shift_r >= {{1'b0, exp_sum_q}}) begin
                lane_remainder_q[lane_index] <= remainder_shift_r - {{1'b0, exp_sum_q}};
                lane_quotient_q[lane_index] <= quotient_shift_r | 57'd1;
              end else begin
                lane_remainder_q[lane_index] <= remainder_shift_r;
                lane_quotient_q[lane_index] <= quotient_shift_r;
              end
            end
          end
        end
        OUTPUT: begin
          if (out_valid_q && out_ready) begin
            completed_count <= completed_count + 1'b1;
            out_valid_q <= 1'b0;
            state_q <= IDLE;
          end
        end
        default: begin
          state_q <= IDLE;
        end
      endcase
    end
  end
endmodule
"""


def generate(config: dict[str, Any], out_dir: Path) -> None:
    params = _validate(json.loads(json.dumps(config)))
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "top.v").write_text(
        _top(
            top_name=str(params["top_name"]),
            value_slices=int(params["value_slices"]),
            head_id_bits=int(params["head_id_bits"]),
            divider_lanes=int(params["divider_lanes"]),
        ),
        encoding="utf-8",
    )
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    divider_lanes = int(params["divider_lanes"])
    manifest = {
        "version": 1,
        "top_name": params["top_name"],
        "generator": "npu/rtlgen/gen_attention_score32_exact_root_finalizer.py",
        "semantic_profile": "score32_online_exact_root_finalizer_iterdiv_v1",
        "value_slices": int(params["value_slices"]),
        "head_id_bits": int(params["head_id_bits"]),
        "divider_lanes": divider_lanes,
        "physical_divider_lanes": divider_lanes,
        "divider_groups_per_beat": 8 // divider_lanes,
        "divider_iterations_per_group": 57,
        "divider_cycles_per_beat": (8 // divider_lanes) * 57,
        "output_latency_cycles_per_beat": ((8 // divider_lanes) * 57) + 1,
        "accept_interval_cycles_per_beat": ((8 // divider_lanes) * 57) + 2,
        "input_value_bits_per_beat": 328,
        "output_value_bits_per_beat": 320,
        "result_interface": "ready_valid_exact_finalized_slice_stream",
        "protocol_error_conditions": ["last_semantics", "exp_sum_zero", "final_value_overflow"],
        "final_divider_embodied": True,
        "equivalence_hash": False,
    }
    (out_dir / "attention_score32_exact_root_finalizer_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
