#!/usr/bin/env python3
"""Generate exact-partial decode score service composed with temporal reduction."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_decode_score_multivalue_service import (
    generate as generate_service,
)
from npu.rtlgen.gen_attention_score32_exact_partial_temporal_stream import (
    generate as generate_temporal_stream,
)
from npu.sim.perf.attention_exact_partial import (
    HEAD_ID_BITS,
    PARTIAL_PAYLOAD_BITS,
    VALUE_SLICES,
)

JsonDict = dict[str, Any]

_CONFIG_KEY = "attention_decode_score_multivalue_service_temporal"
_GENERATOR = "npu/rtlgen/gen_attention_decode_score_multivalue_service_temporal.py"
_MANIFEST_NAME = "attention_decode_score_multivalue_service_temporal_manifest.json"
_SERVICE_MANIFEST_NAME = "attention_decode_score_multivalue_service_manifest.json"
_TEMPORAL_MANIFEST_NAME = "attention_score32_exact_partial_temporal_stream_manifest.json"


def _load(path: Path) -> JsonDict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"config must decode to a JSON object: {path}")
    return payload


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: JsonDict) -> JsonDict:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get(_CONFIG_KEY)
    if not top_name or not isinstance(body, dict):
        raise SystemExit(f"config requires top_name and {_CONFIG_KEY}")

    service = body.get("service")
    temporal = body.get("temporal_stream", {})
    if not isinstance(service, dict):
        raise SystemExit(f"{_CONFIG_KEY}.service must be a JSON object")
    if not isinstance(temporal, dict):
        raise SystemExit(f"{_CONFIG_KEY}.temporal_stream must be a JSON object")

    service_params = dict(service)
    result_mode = str(service_params.get("result_mode", "")).strip().lower()
    if result_mode != "exact_partial":
        raise SystemExit("service.result_mode must be exact_partial")
    head_id_bits = int(service_params.get("head_id_bits", HEAD_ID_BITS))
    if head_id_bits != HEAD_ID_BITS:
        raise SystemExit(f"service.head_id_bits must remain fixed at {HEAD_ID_BITS}")
    cluster_count = int(service_params.get("cluster_count", 1))
    if cluster_count < 1 or cluster_count > 32:
        raise SystemExit("service.cluster_count must be in [1, 32]")

    fifo_depth = int(temporal.get("fifo_depth", 4))
    if fifo_depth < 2 or fifo_depth > 16 or (fifo_depth & (fifo_depth - 1)):
        raise SystemExit("temporal_stream.fifo_depth must be a power of two in [2, 16]")
    exp_scale_impl = str(temporal.get("exp_scale_impl", "factored_h33_l64_mul_exact")).strip()
    keep_hierarchy = bool(temporal.get("keep_hierarchy", True))

    return {
        "top_name": top_name,
        "service": service_params,
        "cluster_count": cluster_count,
        "source_w": _clog2(cluster_count),
        "fifo_depth": fifo_depth,
        "exp_scale_impl": exp_scale_impl,
        "keep_hierarchy": keep_hierarchy,
    }


def _wrapper(*, top_name: str, service_top: str, temporal_top: str, cluster_count: int, source_w: int, fifo_depth: int) -> str:
    fifo_level_w = _clog2(fifo_depth) + 1
    return f"""// Auto-generated by {_GENERATOR}
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         preload_valid,
    output wire         preload_ready,
    input  wire [13:0]  preload_addr,
    input  wire [3:0]   preload_value_slice,
    input  wire [511:0] preload_matrix,
    input  wire [{cluster_count - 1}:0] cluster_command_valid,
    output wire [{cluster_count - 1}:0] cluster_command_ready,
    input  wire [{cluster_count * 16 - 1}:0] cluster_command_id,
    input  wire [{cluster_count * 16 - 1}:0] cluster_logical_sequence_id,
    input  wire [{cluster_count * 16 - 1}:0] cluster_logical_command_id,
    input  wire [{cluster_count * 14 - 1}:0] cluster_window_index,
    input  wire [{cluster_count * 15 - 1}:0] cluster_window_count,
    input  wire [{cluster_count * 15 - 1}:0] cluster_command_block_count,
    input  wire [{cluster_count * HEAD_ID_BITS - 1}:0] cluster_command_head_id,
    input  wire [{cluster_count * 32 - 1}:0] cluster_command_score_multiplier,
    input  wire [{cluster_count * 6 - 1}:0] cluster_command_score_shift,
    input  wire [{cluster_count - 1}:0] cluster_input_valid,
    output wire [{cluster_count - 1}:0] cluster_input_ready,
    input  wire [{cluster_count - 1}:0] cluster_input_last,
    input  wire [{cluster_count * 8 - 1}:0] cluster_input_a,
    input  wire [{cluster_count * 64 - 1}:0] cluster_input_b,
    output wire         out_valid,
    input  wire         out_ready,
    output wire [15:0]  out_sequence_id,
    output wire [{HEAD_ID_BITS - 1}:0] out_head_id,
    output wire [14:0]  out_window_count,
    output wire [15:0]  out_command_id,
    output wire signed [31:0] out_global_max,
    output wire [32:0]  out_exp_sum,
    output wire [3:0]   out_slice,
    output wire         out_last,
    output wire [327:0] out_value,
    output wire [{cluster_count - 1}:0] cluster_metadata_busy,
    output wire [{cluster_count - 1}:0] service_cluster_result_valid,
    output wire [{cluster_count - 1}:0] service_cluster_result_ready,
    output wire [{cluster_count * 16 - 1}:0] service_cluster_result_command_id,
    output wire [{cluster_count * 32 - 1}:0] service_cluster_result_global_max,
    output wire [{cluster_count * 33 - 1}:0] service_cluster_result_exp_sum,
    output wire [{cluster_count * HEAD_ID_BITS - 1}:0] service_cluster_result_head_id,
    output wire [{cluster_count * 4 - 1}:0] service_cluster_result_slice,
    output wire [{cluster_count - 1}:0] service_cluster_result_last,
    output wire [{cluster_count * PARTIAL_PAYLOAD_BITS - 1}:0] service_cluster_result_value,
    output wire         service_shared_result_valid,
    output wire         service_shared_result_ready,
    output wire [{source_w - 1}:0] service_shared_result_cluster,
    output wire [15:0]  service_shared_result_command_id,
    output wire [31:0]  service_shared_result_global_max,
    output wire [32:0]  service_shared_result_exp_sum,
    output wire [{HEAD_ID_BITS - 1}:0] service_shared_result_head_id,
    output wire [3:0]   service_shared_result_slice,
    output wire         service_shared_result_last,
    output wire [327:0] service_shared_result_value,
    output wire [{cluster_count * 32 - 1}:0] service_cluster_accepted_count,
    output wire [{cluster_count * 32 - 1}:0] service_cluster_completed_count,
    output wire [{cluster_count * 32 - 1}:0] service_cluster_cycle_count,
    output wire [{cluster_count - 1}:0] service_cluster_protocol_error,
    output wire [{cluster_count * 8 - 1}:0] service_transport_req_tag,
    output wire [{cluster_count * source_w - 1}:0] service_transport_wide_source,
    output wire [{cluster_count * 8 - 1}:0] service_transport_wide_tag,
    output wire [{cluster_count * 14 - 1}:0] service_transport_wide_addr,
    output wire [{cluster_count * 4 - 1}:0] service_transport_wide_value_slice,
    output wire [{cluster_count - 1}:0] service_transport_wide_valid,
    output wire [{cluster_count - 1}:0] service_reassembler_protocol_error,
    output wire [31:0]  service_router_injection_stall_cycles,
    output wire [31:0]  service_router_arbitration_contention_cycles,
    output wire [31:0]  service_router_response_block_cycles,
    output wire [31:0]  service_router_req_current_occupancy,
    output wire [31:0]  service_router_req_max_occupancy,
    output wire [31:0]  service_router_resp_current_occupancy,
    output wire [31:0]  service_router_resp_max_occupancy,
    output wire [31:0]  service_accepted_req_count,
    output wire [31:0]  service_emitted_resp_count,
    output wire [31:0]  service_bank_conflict_count,
    output wire [31:0]  service_response_block_cycles,
    output wire [31:0]  service_req_current_occupancy,
    output wire [31:0]  service_req_max_occupancy,
    output wire [31:0]  service_resp_current_occupancy,
    output wire [31:0]  service_resp_max_occupancy,
    output wire [31:0]  service_result_arbitration_contention_cycles,
    output wire [31:0]  service_result_egress_block_cycles,
    output wire [31:0]  temporal_cycle_count,
    output wire [31:0]  temporal_input_accepted_count,
    output wire [31:0]  temporal_merge_completed_count,
    output wire [31:0]  temporal_emitted_beat_count,
    output wire [31:0]  temporal_completed_head_count,
    output wire [31:0]  temporal_fifo_full_stall_cycles,
    output wire [31:0]  temporal_output_stall_cycles,
    output wire [{fifo_level_w - 1}:0] temporal_fifo_level,
    output wire         wrapper_protocol_error,
    output wire         service_protocol_error,
    output wire         temporal_protocol_error,
    output wire         protocol_error
);
  localparam integer CLUSTERS = {cluster_count};
  localparam integer SOURCE_W = {source_w};
  localparam integer HEAD_ID_BITS = {HEAD_ID_BITS};
  localparam integer PARTIAL_PAYLOAD_BITS = {PARTIAL_PAYLOAD_BITS};

  reg [CLUSTERS-1:0] metadata_valid_q;
  reg [CLUSTERS*16-1:0] metadata_sequence_id_q;
  reg [CLUSTERS*16-1:0] metadata_logical_command_id_q;
  reg [CLUSTERS*16-1:0] metadata_service_command_id_q;
  reg [CLUSTERS*14-1:0] metadata_window_index_q;
  reg [CLUSTERS*15-1:0] metadata_window_count_q;
  reg wrapper_protocol_error_q;

  wire [CLUSTERS-1:0] service_cluster_command_valid;
  wire [CLUSTERS-1:0] service_cluster_command_ready;
  wire [CLUSTERS-1:0] command_open_w = ~metadata_valid_q & {{CLUSTERS{{!protocol_error}}}};
  wire [CLUSTERS-1:0] command_fire_w;
  wire temporal_in_ready_w;
  wire selected_metadata_valid_w = metadata_valid_q[service_shared_result_cluster];
  wire [15:0] selected_sequence_id_w =
      metadata_sequence_id_q[(service_shared_result_cluster * 16) +: 16];
  wire [15:0] selected_logical_command_id_w =
      metadata_logical_command_id_q[(service_shared_result_cluster * 16) +: 16];
  wire [15:0] selected_service_command_id_w =
      metadata_service_command_id_q[(service_shared_result_cluster * 16) +: 16];
  wire [13:0] selected_window_index_w =
      metadata_window_index_q[(service_shared_result_cluster * 14) +: 14];
  wire [14:0] selected_window_count_w =
      metadata_window_count_q[(service_shared_result_cluster * 15) +: 15];
  wire service_result_metadata_error_w =
      service_shared_result_valid
      && (!selected_metadata_valid_w
          || (selected_service_command_id_w != service_shared_result_command_id));
  wire temporal_in_valid_w =
      service_shared_result_valid
      && selected_metadata_valid_w
      && !service_result_metadata_error_w
      && !protocol_error;
  wire service_to_temporal_fire_w = temporal_in_valid_w && temporal_in_ready_w;

  assign service_cluster_command_valid = cluster_command_valid & command_open_w;
  assign cluster_command_ready = service_cluster_command_ready & command_open_w;
  assign command_fire_w = service_cluster_command_valid & service_cluster_command_ready;
  assign service_shared_result_ready =
      temporal_in_ready_w
      && selected_metadata_valid_w
      && !service_result_metadata_error_w
      && !protocol_error;
  assign cluster_metadata_busy = metadata_valid_q;
  assign wrapper_protocol_error = wrapper_protocol_error_q || service_result_metadata_error_w;
  assign protocol_error = wrapper_protocol_error || service_protocol_error || temporal_protocol_error;

  integer metadata_i;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      metadata_valid_q <= {{CLUSTERS{{1'b0}}}};
      metadata_sequence_id_q <= {{(CLUSTERS * 16){{1'b0}}}};
      metadata_logical_command_id_q <= {{(CLUSTERS * 16){{1'b0}}}};
      metadata_service_command_id_q <= {{(CLUSTERS * 16){{1'b0}}}};
      metadata_window_index_q <= {{(CLUSTERS * 14){{1'b0}}}};
      metadata_window_count_q <= {{(CLUSTERS * 15){{1'b0}}}};
      wrapper_protocol_error_q <= 1'b0;
    end else begin
      if (service_result_metadata_error_w) begin
        wrapper_protocol_error_q <= 1'b1;
      end
      for (metadata_i = 0; metadata_i < CLUSTERS; metadata_i = metadata_i + 1) begin
        if (command_fire_w[metadata_i]) begin
          metadata_valid_q[metadata_i] <= 1'b1;
          metadata_sequence_id_q[(metadata_i * 16) +: 16] <=
              cluster_logical_sequence_id[(metadata_i * 16) +: 16];
          metadata_logical_command_id_q[(metadata_i * 16) +: 16] <=
              cluster_logical_command_id[(metadata_i * 16) +: 16];
          metadata_service_command_id_q[(metadata_i * 16) +: 16] <=
              cluster_command_id[(metadata_i * 16) +: 16];
          metadata_window_index_q[(metadata_i * 14) +: 14] <=
              cluster_window_index[(metadata_i * 14) +: 14];
          metadata_window_count_q[(metadata_i * 15) +: 15] <=
              cluster_window_count[(metadata_i * 15) +: 15];
        end
      end
      if (service_to_temporal_fire_w && service_shared_result_last) begin
        metadata_valid_q[service_shared_result_cluster] <= 1'b0;
      end
    end
  end

  {service_top} u_service (
      .clk(clk),
      .rst_n(rst_n),
      .preload_valid(preload_valid),
      .preload_ready(preload_ready),
      .preload_addr(preload_addr),
      .preload_value_slice(preload_value_slice),
      .preload_matrix(preload_matrix),
      .cluster_command_valid(service_cluster_command_valid),
      .cluster_command_ready(service_cluster_command_ready),
      .cluster_command_id(cluster_command_id),
      .cluster_command_block_count(cluster_command_block_count),
      .cluster_command_head_id(cluster_command_head_id),
      .cluster_command_score_multiplier(cluster_command_score_multiplier),
      .cluster_command_score_shift(cluster_command_score_shift),
      .cluster_input_valid(cluster_input_valid),
      .cluster_input_ready(cluster_input_ready),
      .cluster_input_last(cluster_input_last),
      .cluster_input_a(cluster_input_a),
      .cluster_input_b(cluster_input_b),
      .cluster_result_valid(service_cluster_result_valid),
      .cluster_result_ready(service_cluster_result_ready),
      .cluster_result_command_id(service_cluster_result_command_id),
      .cluster_result_global_max(service_cluster_result_global_max),
      .cluster_result_exp_sum(service_cluster_result_exp_sum),
      .cluster_result_head_id(service_cluster_result_head_id),
      .cluster_result_slice(service_cluster_result_slice),
      .cluster_result_last(service_cluster_result_last),
      .cluster_result_value(service_cluster_result_value),
      .shared_result_valid(service_shared_result_valid),
      .shared_result_ready(service_shared_result_ready),
      .shared_result_cluster(service_shared_result_cluster),
      .shared_result_command_id(service_shared_result_command_id),
      .shared_result_global_max(service_shared_result_global_max),
      .shared_result_exp_sum(service_shared_result_exp_sum),
      .shared_result_head_id(service_shared_result_head_id),
      .shared_result_slice(service_shared_result_slice),
      .shared_result_last(service_shared_result_last),
      .shared_result_value(service_shared_result_value),
      .cluster_accepted_count(service_cluster_accepted_count),
      .cluster_completed_count(service_cluster_completed_count),
      .cluster_cycle_count(service_cluster_cycle_count),
      .cluster_protocol_error(service_cluster_protocol_error),
      .transport_req_tag(service_transport_req_tag),
      .transport_wide_source(service_transport_wide_source),
      .transport_wide_tag(service_transport_wide_tag),
      .transport_wide_addr(service_transport_wide_addr),
      .transport_wide_value_slice(service_transport_wide_value_slice),
      .transport_wide_valid(service_transport_wide_valid),
      .reassembler_protocol_error(service_reassembler_protocol_error),
      .router_injection_stall_cycles(service_router_injection_stall_cycles),
      .router_arbitration_contention_cycles(service_router_arbitration_contention_cycles),
      .router_response_block_cycles(service_router_response_block_cycles),
      .router_req_current_occupancy(service_router_req_current_occupancy),
      .router_req_max_occupancy(service_router_req_max_occupancy),
      .router_resp_current_occupancy(service_router_resp_current_occupancy),
      .router_resp_max_occupancy(service_router_resp_max_occupancy),
      .service_accepted_req_count(service_accepted_req_count),
      .service_emitted_resp_count(service_emitted_resp_count),
      .service_bank_conflict_count(service_bank_conflict_count),
      .service_response_block_cycles(service_response_block_cycles),
      .service_req_current_occupancy(service_req_current_occupancy),
      .service_req_max_occupancy(service_req_max_occupancy),
      .service_resp_current_occupancy(service_resp_current_occupancy),
      .service_resp_max_occupancy(service_resp_max_occupancy),
      .result_arbitration_contention_cycles(service_result_arbitration_contention_cycles),
      .result_egress_block_cycles(service_result_egress_block_cycles),
      .protocol_error(service_protocol_error)
  );

  {temporal_top} u_temporal (
      .clk(clk),
      .rst_n(rst_n),
      .in_valid(temporal_in_valid_w),
      .in_ready(temporal_in_ready_w),
      .in_sequence_id(selected_sequence_id_w),
      .in_head_id(service_shared_result_head_id),
      .in_window_index(selected_window_index_w),
      .in_window_count(selected_window_count_w),
      .in_command_id(selected_logical_command_id_w),
      .in_global_max(service_shared_result_global_max),
      .in_exp_sum(service_shared_result_exp_sum),
      .in_slice(service_shared_result_slice),
      .in_last(service_shared_result_last),
      .in_value(service_shared_result_value),
      .out_valid(out_valid),
      .out_ready(out_ready),
      .out_sequence_id(out_sequence_id),
      .out_head_id(out_head_id),
      .out_window_count(out_window_count),
      .out_command_id(out_command_id),
      .out_global_max(out_global_max),
      .out_exp_sum(out_exp_sum),
      .out_slice(out_slice),
      .out_last(out_last),
      .out_value(out_value),
      .cycle_count(temporal_cycle_count),
      .input_accepted_count(temporal_input_accepted_count),
      .merge_completed_count(temporal_merge_completed_count),
      .emitted_beat_count(temporal_emitted_beat_count),
      .completed_head_count(temporal_completed_head_count),
      .fifo_full_stall_cycles(temporal_fifo_full_stall_cycles),
      .output_stall_cycles(temporal_output_stall_cycles),
      .fifo_level(temporal_fifo_level),
      .protocol_error(temporal_protocol_error)
  );
endmodule
"""


def _top_pin_bits(*, cluster_count: int, source_w: int, fifo_depth: int) -> int:
    command_bits = (
        cluster_count
        * (1 + 16 + 16 + 16 + 14 + 15 + 15 + HEAD_ID_BITS + 32 + 6 + 1 + 1 + 8 + 64)
    )
    preload_bits = 1 + 1 + 14 + 4 + 512
    full_context_output_bits = 1 + 1 + 16 + HEAD_ID_BITS + 15 + 16 + 32 + 33 + 4 + 1 + 328
    service_result_bits = cluster_count * (2 + 16 + 32 + 33 + HEAD_ID_BITS + 4 + 1 + PARTIAL_PAYLOAD_BITS)
    shared_service_bits = 2 + source_w + 16 + 32 + 33 + HEAD_ID_BITS + 4 + 1 + PARTIAL_PAYLOAD_BITS
    service_monitors = (
        cluster_count
        + (3 * cluster_count * 32)
        + cluster_count
        + (cluster_count * (8 + source_w + 8 + 14 + 4 + 1))
        + (19 * 32)
    )
    temporal_monitors = (7 * 32) + (_clog2(fifo_depth) + 1) + 3
    return preload_bits + command_bits + full_context_output_bits + service_result_bits + shared_service_bits + service_monitors + temporal_monitors


def generate(config: JsonDict, out_dir: Path) -> None:
    params = _validate(json.loads(json.dumps(config)))
    top_name = str(params["top_name"])
    service_top = f"{top_name}__service"
    temporal_top = f"{top_name}__temporal"
    out_dir.mkdir(parents=True, exist_ok=True)

    service_config = {
        "top_name": service_top,
        "attention_decode_score_multivalue_service": params["service"],
    }
    temporal_config = {
        "top_name": temporal_top,
        "attention_score32_exact_partial_temporal_stream": {
            "heads": 32,
            "value_slices": VALUE_SLICES,
            "head_id_bits": HEAD_ID_BITS,
            "fifo_depth": int(params["fifo_depth"]),
            "sequence_id_bits": 16,
            "window_index_bits": 14,
            "window_count_bits": 15,
            "max_window_count": 16384,
            "exp_scale_impl": str(params["exp_scale_impl"]),
            "keep_hierarchy": bool(params["keep_hierarchy"]),
        },
    }

    with tempfile.TemporaryDirectory(prefix="decode-service-temporal-gen-") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        service_dir = temp_dir / "service"
        temporal_dir = temp_dir / "temporal"
        generate_service(service_config, service_dir)
        generate_temporal_stream(temporal_config, temporal_dir)
        service_rtl = (service_dir / "top.v").read_text(encoding="utf-8")
        temporal_rtl = (temporal_dir / "top.v").read_text(encoding="utf-8")
        service_manifest = json.loads((service_dir / _SERVICE_MANIFEST_NAME).read_text(encoding="utf-8"))
        temporal_manifest = json.loads((temporal_dir / _TEMPORAL_MANIFEST_NAME).read_text(encoding="utf-8"))
        service_macro_manifest = json.loads((service_dir / "macro_manifest.json").read_text(encoding="utf-8"))

    wrapper = _wrapper(
        top_name=top_name,
        service_top=service_top,
        temporal_top=temporal_top,
        cluster_count=int(params["cluster_count"]),
        source_w=int(params["source_w"]),
        fifo_depth=int(params["fifo_depth"]),
    )
    top_text = "\n\n".join([service_rtl, temporal_rtl, wrapper]) + "\n"
    (out_dir / "top.v").write_text(top_text, encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    manifest = {
        "version": 1,
        "top_name": top_name,
        "generator": _GENERATOR,
        "semantic_profile": "decode_score_multivalue_service_temporal_exact_partial_same_clock_v1",
        "clocking_contract": "same_clock_only",
        "cluster_count": int(params["cluster_count"]),
        "result_mode": "exact_partial",
        "head_id_bits": HEAD_ID_BITS,
        "value_slices": VALUE_SLICES,
        "partial_payload_bits_per_service_beat": PARTIAL_PAYLOAD_BITS,
        "external_command_metadata": {
            "capture_event": "cluster_command_valid_and_cluster_command_ready",
            "sequence_id_bits": 16,
            "logical_command_id_bits": 16,
            "window_index_bits": 14,
            "window_count_bits": 15,
            "per_cluster_busy_until": "shared_terminal_result_beat_fires_into_temporal_reducer",
        },
        "retagging_contract": (
            "metadata_selected_by_service_shared_result_cluster_and_held_until_last_beat_handshake"
        ),
        "stale_egress_guard": "fail_closed_on_missing_metadata_or_service_command_id_mismatch",
        "full_context_output": "ready_valid_exact_partial_temporal_head_slice_stream",
        "submodule_monitor_exposure": {
            "service": "cluster_results_shared_result_transport_counters_protocol_error",
            "temporal": "full_context_stream_counters_fifo_level_protocol_error",
        },
        "remaining_abstractions": [
            "clock_domain_crossing",
            "downstream_full_context_final_normalizer",
            "persistent_state_sram_physical_mapping",
            "physical_ppa",
        ],
        "dependency_sources": [
            {"path": _GENERATOR, "sha256": _sha256_file(Path(__file__))},
            {
                "path": "npu/rtlgen/gen_attention_decode_score_multivalue_service.py",
                "sha256": _sha256_file(REPO_ROOT / "npu/rtlgen/gen_attention_decode_score_multivalue_service.py"),
            },
            {
                "path": "npu/rtlgen/gen_attention_score32_exact_partial_temporal_stream.py",
                "sha256": _sha256_file(REPO_ROOT / "npu/rtlgen/gen_attention_score32_exact_partial_temporal_stream.py"),
            },
        ],
        "generated_top_sha256": _sha256_text(top_text),
        "top_pin_bits": _top_pin_bits(
            cluster_count=int(params["cluster_count"]),
            source_w=int(params["source_w"]),
            fifo_depth=int(params["fifo_depth"]),
        ),
        "submodule_manifests": {
            "service": service_manifest,
            "temporal_stream": temporal_manifest,
            "service_macro_manifest": service_macro_manifest,
        },
    }
    (out_dir / _MANIFEST_NAME).write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
