#!/usr/bin/env python3
"""Generate a LEF/LIB-backed proxy for the attention score SRAM bank."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


_DEPTH_GROUPS = 8
_WIDTH_SLICES = 7
_MACRO_DEPTH = 2048
_MACRO_WIDTH = 39
_LOGICAL_DEPTH = 16 * 1024
_LOGICAL_WIDTH = 256
_PAD_BITS = (_WIDTH_SLICES * _MACRO_WIDTH) - _LOGICAL_WIDTH


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _validate(config: dict[str, Any]) -> dict[str, int]:
    if not str(config.get("top_name") or "").strip():
        raise SystemExit("config top_name must not be empty")
    body = config.get("attention_score_bank_proxy")
    if not isinstance(body, dict):
        raise SystemExit("config must contain attention_score_bank_proxy object")
    return {
        "depth_groups": _DEPTH_GROUPS,
        "width_slices": _WIDTH_SLICES,
        "macro_depth": _MACRO_DEPTH,
        "macro_width": _MACRO_WIDTH,
        "logical_depth": _LOGICAL_DEPTH,
        "logical_width": _LOGICAL_WIDTH,
        "pad_bits": _PAD_BITS,
    }


def _macro_instance(*, group: int, slice_idx: int) -> str:
    return f"""  fakeram45_2048x39 u_group_{group}_slice_{slice_idx} (
      .rd_out(group_{group}_slice_{slice_idx}_rd_out),
      .addr_in(req_row_addr),
      .we_in(group_{group}_ce && req_write),
      .wd_in(req_wdata_padded[{(slice_idx + 1) * _MACRO_WIDTH - 1}:{slice_idx * _MACRO_WIDTH}]),
      .w_mask_in(req_wmask_padded[{(slice_idx + 1) * _MACRO_WIDTH - 1}:{slice_idx * _MACRO_WIDTH}]),
      .clk(clk),
      .ce_in(group_{group}_ce)
  );
"""


def _top(*, top_name: str) -> str:
    macro_wires = []
    concat_wires = []
    instances = []
    for group in range(_DEPTH_GROUPS):
        macro_wires.append(f"  wire group_{group}_ce = req_valid && (req_depth_group == 3'd{group});")
        slice_names = []
        for slice_idx in range(_WIDTH_SLICES):
            macro_wires.append(f"  wire [38:0] group_{group}_slice_{slice_idx}_rd_out;")
            slice_names.append(f"group_{group}_slice_{slice_idx}_rd_out")
            instances.append(_macro_instance(group=group, slice_idx=slice_idx))
        concat_wires.append(
            f"  wire [272:0] group_{group}_rd_concat = "
            + "{"
            + ", ".join(reversed(slice_names))
            + "};"
        )

    rsp_cases = "\n".join(
        f"      3'd{group}: rsp_rdata_mux = group_{group}_rd_concat[255:0];" for group in range(_DEPTH_GROUPS)
    )

    return f"""// Auto-generated by npu/rtlgen/gen_attention_score_bank_proxy.py
// LEF/LIB proxy semantics only: this RTL models logical integration of
// Nangate45 fakeram45_2048x39 macros and is not SRAM signoff collateral.
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         req_valid,
    output wire         req_ready,
    input  wire         req_write,
    input  wire [13:0]  req_addr,
    input  wire [255:0] req_wdata,
    input  wire [255:0] req_wmask,
    output wire         rsp_valid,
    output wire [255:0] rsp_rdata
);
  localparam integer LOGICAL_DEPTH = {_LOGICAL_DEPTH};
  localparam integer LOGICAL_WIDTH = {_LOGICAL_WIDTH};
  localparam integer DEPTH_GROUPS = {_DEPTH_GROUPS};
  localparam integer WIDTH_SLICES = {_WIDTH_SLICES};
  localparam integer MACRO_DEPTH = {_MACRO_DEPTH};
  localparam integer MACRO_WIDTH = {_MACRO_WIDTH};
  localparam integer UNUSED_PAD_BITS = {_PAD_BITS};

  wire [2:0]  req_depth_group = req_addr[13:11];
  wire [10:0] req_row_addr = req_addr[10:0];
  wire [272:0] req_wdata_padded = {{{_PAD_BITS}'d0, req_wdata}};
  wire [272:0] req_wmask_padded = {{{_PAD_BITS}'d0, req_wmask}};
{chr(10).join(macro_wires)}
{chr(10).join(concat_wires)}

  reg         read_pending_q;
  reg  [2:0]  read_group_q;
  reg         rsp_valid_q;
  reg  [2:0]  rsp_group_q;
  reg  [255:0] rsp_rdata_mux;
  assign req_ready = 1'b1;
  assign rsp_valid = rsp_valid_q;
  assign rsp_rdata = rsp_rdata_mux;

  always @(*) begin
    case (rsp_group_q)
{rsp_cases}
      default: rsp_rdata_mux = 256'd0;
    endcase
  end

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      read_pending_q <= 1'b0;
      read_group_q <= 3'd0;
      rsp_valid_q <= 1'b0;
      rsp_group_q <= 3'd0;
    end else begin
      rsp_valid_q <= read_pending_q;
      rsp_group_q <= read_group_q;
      read_pending_q <= req_valid && !req_write;
      if (req_valid && !req_write) begin
        read_group_q <= req_depth_group;
      end
    end
  end

{chr(10).join(instances)}
endmodule
"""


def generate(config: dict[str, Any], out_dir: Path) -> None:
    params = _validate(config)
    top_name = str(config["top_name"])
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "top.v").write_text(_top(top_name=top_name), encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    manifest = {
        "version": 1,
        "top_name": top_name,
        "proxy_semantics": "lef_lib_physical_proxy_only",
        "integration_target": "attention_two_pass_stream_score_bank_adapter",
        "sram_signoff": False,
        "interface": {
            "type": "synchronous_1rw",
            "request": ["req_valid", "req_ready", "req_write", "req_addr", "req_wdata", "req_wmask"],
            "response": ["rsp_valid", "rsp_rdata"],
            "read_latency_cycles": 1,
            "max_requests_per_cycle": 1,
        },
        "logical_depth": params["logical_depth"],
        "logical_width": params["logical_width"],
        "depth_groups": params["depth_groups"],
        "width_slices_per_group": params["width_slices"],
        "macro_name": "fakeram45_2048x39",
        "macro_depth": params["macro_depth"],
        "macro_width": params["macro_width"],
        "macro_count": params["depth_groups"] * params["width_slices"],
        "unused_pad_bits": params["pad_bits"],
    }
    (out_dir / "attention_score_bank_proxy_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
