#!/usr/bin/env python3
"""Generate a composed local-cluster decode-score attention block."""

from __future__ import annotations

import argparse
import json
import math
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_score_bank_proxy import generate as generate_score_bank_proxy
from npu.rtlgen.gen_attention_two_pass_stream import generate as generate_two_pass_stream
from npu.rtlgen.gen_dense_gemm_tile_stream import generate as generate_score_tile


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: dict[str, Any]) -> dict[str, int | str]:
    top_name = str(config.get("top_name") or "").strip()
    if not top_name:
        raise SystemExit("config top_name must not be empty")
    body = config.get("attention_decode_score_local_cluster")
    if not isinstance(body, dict):
        raise SystemExit("config must contain attention_decode_score_local_cluster object")

    max_blocks = int(body.get("max_blocks", 16384))
    array_n = int(body.get("array_n", 8))
    divider_impl = str(body.get("divider_impl", "iterative_restoring")).strip()
    scale_lanes = int(body.get("score_scale_lanes_per_cycle", 1))

    if max_blocks < 8 or max_blocks > 16384 or max_blocks & (max_blocks - 1):
        raise SystemExit("attention_decode_score_local_cluster.max_blocks must be a power of two in [8, 16384]")
    if array_n != 8:
        raise SystemExit("attention_decode_score_local_cluster.array_n must be 8")
    if divider_impl != "iterative_restoring":
        raise SystemExit("attention_decode_score_local_cluster.divider_impl must be iterative_restoring")
    if scale_lanes not in {1, 2, 4, 8}:
        raise SystemExit("attention_decode_score_local_cluster.score_scale_lanes_per_cycle must be one of 1,2,4,8")

    params: dict[str, int | str] = {
        "top_name": top_name,
        "max_blocks": max_blocks,
        "array_n": array_n,
        "divider_impl": divider_impl,
        "score_scale_lanes_per_cycle": scale_lanes,
    }
    body.update({key: value for key, value in params.items() if key != "top_name"})
    return params


def requantize_s32(raw_value: int, multiplier: int, shift: int) -> int:
    """Signed32 -> signed32 requantization with symmetric magnitude rounding."""

    product = int(raw_value) * int(multiplier)
    negative = product < 0
    magnitude = -product if negative else product
    if shift < 0 or shift > 63:
        raise ValueError(f"shift must be in [0, 63], got {shift}")
    if shift:
        magnitude = (magnitude + (1 << (shift - 1))) >> shift
    if negative:
        if magnitude >= (1 << 31):
            return -(1 << 31)
        return -magnitude
    if magnitude > ((1 << 31) - 1):
        return (1 << 31) - 1
    return magnitude


def _widen_expr(*, expr: str, in_bits: int, out_bits: int) -> str:
    if in_bits >= out_bits:
        return expr
    return "{" + f"{out_bits - in_bits}'d0, {expr}" + "}"


def _compose_wrapper(
    *,
    top_name: str,
    params: dict[str, int | str],
    tile_top: str,
    bank_top: str,
    two_pass_top: str,
) -> str:
    max_blocks = int(params["max_blocks"])
    count_bits = _clog2(max_blocks + 1)
    addr_bits = _clog2(max_blocks)
    scale_lanes = int(params["score_scale_lanes_per_cycle"])
    lane_steps = max(1, scale_lanes)
    command_block_expr = "command_block_count" if count_bits == 15 else f"command_block_count[{count_bits - 1}:0]"
    replay_addr_expr = _widen_expr(expr="score_read_req_addr", in_bits=addr_bits, out_bits=14)
    score_write_addr_expr = _widen_expr(expr="score_write_addr", in_bits=addr_bits, out_bits=14)

    scale_body = "\n".join(
        f"""        lane_index = scale_lane_index_q + {offset};
        if (lane_index < 8) begin
          scaled_score_row_q[(lane_index * 32) +: 32] <= requantize_lane(
              $signed(raw_score_row_q[(lane_index * 32) +: 32]),
              active_multiplier_q,
              active_shift_q
          );
        end"""
        for offset in range(lane_steps)
    )

    return f"""// Auto-generated by npu/rtlgen/gen_attention_decode_score_local_cluster.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         command_valid,
    output wire         command_ready,
    input  wire [15:0]  command_id,
    input  wire [14:0]  command_block_count,
    input  wire [31:0]  command_score_multiplier,
    input  wire [5:0]   command_score_shift,
    input  wire         input_valid,
    output wire         input_ready,
    input  wire         input_last,
    input  wire signed [7:0]  input_a,
    input  wire signed [63:0] input_b,
    output wire         value_read_req_valid,
    input  wire         value_read_req_ready,
    output wire [13:0]  value_read_req_address,
    input  wire         value_response_valid,
    input  wire [13:0]  value_response_address,
    input  wire [511:0] value_response_matrix,
    output wire         result_valid,
    input  wire         result_ready,
    output wire [15:0]  result_command_id,
    output wire signed [31:0] result_global_max,
    output wire [32:0]  result_exp_sum,
    output wire [319:0] result_value,
    output wire [31:0]  accepted_count,
    output wire [31:0]  completed_count,
    output wire [31:0]  cycle_count,
    output reg          protocol_error
);
  localparam integer MAX_BLOCKS = {max_blocks};
  localparam integer COUNT_W = {count_bits};
  localparam integer ADDR_W = {addr_bits};
  localparam integer SCORE_SCALE_LANES_PER_CYCLE = {scale_lanes};
  localparam [2:0] STATE_IDLE = 3'd0;
  localparam [2:0] STATE_TILE_CMD = 3'd1;
  localparam [2:0] STATE_TILE_INPUT = 3'd2;
  localparam [2:0] STATE_TILE_WAIT_RESULT = 3'd3;
  localparam [2:0] STATE_SCALE = 3'd4;
  localparam [2:0] STATE_FILL = 3'd5;
  localparam [2:0] STATE_WAIT_RESULT = 3'd6;

  reg [2:0] state_q;
  reg [COUNT_W-1:0] block_index_q;
  reg [COUNT_W-1:0] active_block_count_q;
  reg [31:0] active_multiplier_q;
  reg [5:0] active_shift_q;
  reg [255:0] raw_score_row_q;
  reg [255:0] scaled_score_row_q;
  reg [3:0] scale_lane_index_q;

  reg outstanding_score_read_q;
  reg [13:0] outstanding_score_read_addr_q;
  reg score_response_buf_valid_q;
  reg [13:0] score_response_buf_addr_q;
  reg [255:0] score_response_buf_data_q;
  reg value_response_buf_valid_q;
  reg [13:0] value_response_buf_addr_q;
  reg [511:0] value_response_buf_data_q;

  wire tile_command_valid;
  wire tile_command_ready;
  wire tile_input_valid;
  wire tile_input_ready;
  wire tile_result_valid;
  wire tile_result_ready;
  wire signed [255:0] tile_result_score_row;

  wire two_pass_command_valid;
  wire two_pass_command_ready;
  wire two_pass_fill_valid;
  wire two_pass_fill_ready;
  wire [255:0] two_pass_fill_score_row;
  wire score_write_valid;
  wire score_write_ready;
  wire [ADDR_W-1:0] score_write_addr;
  wire [255:0] score_write_data;
  wire score_read_req_valid;
  wire score_read_req_ready;
  wire [ADDR_W-1:0] score_read_req_addr;
  wire replay_valid;
  wire replay_ready;
  wire [255:0] replay_score_row;
  wire [511:0] replay_value_matrix;
  wire two_pass_result_valid;
  wire [15:0] two_pass_result_command_id;
  wire signed [31:0] two_pass_result_global_max;
  wire [32:0] two_pass_result_exp_sum;
  wire [319:0] two_pass_result_value;
  wire [31:0] two_pass_accepted_count;
  wire [31:0] two_pass_completed_count;
  wire [31:0] two_pass_cycle_count;

  wire score_bank_req_valid;
  wire score_bank_req_ready;
  wire score_bank_req_write;
  wire [13:0] score_bank_req_addr;
  wire [255:0] score_bank_req_wdata;
  wire [255:0] score_bank_req_wmask;
  wire score_bank_rsp_valid;
  wire [255:0] score_bank_rsp_rdata;
  wire command_block_count_valid = command_block_count != 0
      && command_block_count <= MAX_BLOCKS;

  wire issue_replay_request = !outstanding_score_read_q
      && !score_response_buf_valid_q
      && !value_response_buf_valid_q;
  wire replay_request_fire = score_read_req_valid && value_read_req_ready && issue_replay_request;
  wire replay_match = score_response_buf_valid_q
      && value_response_buf_valid_q
      && (score_response_buf_addr_q == value_response_buf_addr_q);
  wire replay_mismatch = score_response_buf_valid_q
      && value_response_buf_valid_q
      && (score_response_buf_addr_q != value_response_buf_addr_q);

  wire value_req_valid = value_read_req_valid;
  wire value_req_ready = value_read_req_ready;
  wire [13:0] value_req_addr = value_read_req_address;
  wire value_rsp_valid = value_response_valid;
  wire value_rsp_ready = replay_match && replay_ready;
  wire [511:0] value_rsp_matrix = value_response_matrix;
  wire score_response_valid = score_bank_rsp_valid;

  integer lane_index;

  assign command_ready = (state_q == STATE_IDLE)
      && two_pass_command_ready
      && command_block_count_valid;
  assign input_ready = (state_q == STATE_TILE_INPUT) && tile_input_ready;

  assign tile_command_valid = state_q == STATE_TILE_CMD;
  assign tile_input_valid = (state_q == STATE_TILE_INPUT) && input_valid;
  assign tile_result_ready = state_q == STATE_TILE_WAIT_RESULT;

  assign two_pass_command_valid = (state_q == STATE_IDLE)
      && command_valid
      && command_block_count_valid;
  assign two_pass_fill_valid = state_q == STATE_FILL;
  assign two_pass_fill_score_row = scaled_score_row_q;

  assign value_read_req_valid = score_read_req_valid && issue_replay_request;
  assign value_read_req_address = {replay_addr_expr};
  assign score_read_req_ready = value_read_req_ready && issue_replay_request;

  assign score_write_ready = score_bank_req_ready;
  assign score_bank_req_valid = score_write_valid || replay_request_fire;
  assign score_bank_req_write = score_write_valid;
  assign score_bank_req_addr = score_write_valid
      ? {score_write_addr_expr}
      : value_read_req_address;
  assign score_bank_req_wdata = score_write_valid ? score_write_data : 256'd0;
  assign score_bank_req_wmask = score_write_valid
      ? 256'hffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff_ffff
      : 256'd0;

  assign replay_valid = replay_match;
  assign replay_score_row = score_response_buf_data_q;
  assign replay_value_matrix = value_response_buf_data_q;

  assign result_valid = two_pass_result_valid;
  assign result_command_id = two_pass_result_command_id;
  assign result_global_max = two_pass_result_global_max;
  assign result_exp_sum = two_pass_result_exp_sum;
  assign result_value = two_pass_result_value;
  assign accepted_count = two_pass_accepted_count;
  assign completed_count = two_pass_completed_count;
  assign cycle_count = two_pass_cycle_count;

  function automatic signed [31:0] requantize_lane;
    input signed [31:0] raw_lane;
    input [31:0] multiplier;
    input [5:0] shift;
    reg signed [63:0] product;
    reg negative;
    reg [63:0] magnitude;
    reg [63:0] rounded;
    begin
      product = raw_lane * $signed({{1'b0, multiplier}});
      negative = product < 0;
      magnitude = negative ? (~product) + 64'd1 : product[63:0];
      if (shift == 0)
        rounded = magnitude;
      else
        rounded = (magnitude + (64'd1 << (shift - 1'b1))) >> shift;
      if (negative) begin
        if (rounded >= 64'd2147483648)
          requantize_lane = 32'sh8000_0000;
        else
          requantize_lane = -$signed(rounded[31:0]);
      end else begin
        if (rounded > 64'd2147483647)
          requantize_lane = 32'sd2147483647;
        else
          requantize_lane = $signed(rounded[31:0]);
      end
    end
  endfunction

  {tile_top} u_score_tile (
      .clk(clk),
      .rst_n(rst_n),
      .command_valid(tile_command_valid),
      .command_ready(tile_command_ready),
      .input_valid(tile_input_valid),
      .input_ready(tile_input_ready),
      .input_last(input_last),
      .input_a(input_a),
      .input_b(input_b),
      .result_valid(tile_result_valid),
      .result_ready(tile_result_ready),
      .result_score_row(tile_result_score_row)
  );

  {bank_top} u_score_bank (
      .clk(clk),
      .rst_n(rst_n),
      .req_valid(score_bank_req_valid),
      .req_ready(score_bank_req_ready),
      .req_write(score_bank_req_write),
      .req_addr(score_bank_req_addr),
      .req_wdata(score_bank_req_wdata),
      .req_wmask(score_bank_req_wmask),
      .rsp_valid(score_bank_rsp_valid),
      .rsp_rdata(score_bank_rsp_rdata)
  );

  {two_pass_top} u_two_pass (
      .clk(clk),
      .rst_n(rst_n),
      .command_valid(two_pass_command_valid),
      .command_ready(two_pass_command_ready),
      .command_id(command_id),
      .command_block_count({command_block_expr}),
      .fill_valid(two_pass_fill_valid),
      .fill_ready(two_pass_fill_ready),
      .fill_score_row(two_pass_fill_score_row),
      .score_write_valid(score_write_valid),
      .score_write_ready(score_write_ready),
      .score_write_addr(score_write_addr),
      .score_write_data(score_write_data),
      .score_read_req_valid(score_read_req_valid),
      .score_read_req_ready(score_read_req_ready),
      .score_read_req_addr(score_read_req_addr),
      .replay_valid(replay_valid),
      .replay_ready(replay_ready),
      .replay_score_row(replay_score_row),
      .replay_value_matrix(replay_value_matrix),
      .result_valid(two_pass_result_valid),
      .result_ready(result_ready),
      .result_command_id(two_pass_result_command_id),
      .result_global_max(two_pass_result_global_max),
      .result_exp_sum(two_pass_result_exp_sum),
      .result_value(two_pass_result_value),
      .accepted_count(two_pass_accepted_count),
      .completed_count(two_pass_completed_count),
      .cycle_count(two_pass_cycle_count)
  );

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state_q <= STATE_IDLE;
      block_index_q <= {{COUNT_W{{1'b0}}}};
      active_block_count_q <= {{COUNT_W{{1'b0}}}};
      active_multiplier_q <= 32'd0;
      active_shift_q <= 6'd0;
      raw_score_row_q <= 256'd0;
      scaled_score_row_q <= 256'd0;
      scale_lane_index_q <= 4'd0;
      outstanding_score_read_q <= 1'b0;
      outstanding_score_read_addr_q <= 14'd0;
      score_response_buf_valid_q <= 1'b0;
      score_response_buf_addr_q <= 14'd0;
      score_response_buf_data_q <= 256'd0;
      value_response_buf_valid_q <= 1'b0;
      value_response_buf_addr_q <= 14'd0;
      value_response_buf_data_q <= 512'd0;
      protocol_error <= 1'b0;
    end else begin
      if (replay_mismatch) begin
        protocol_error <= 1'b1;
      end

      if (replay_valid && replay_ready) begin
        score_response_buf_valid_q <= 1'b0;
        value_response_buf_valid_q <= 1'b0;
      end

      if (score_bank_rsp_valid) begin
        if (!outstanding_score_read_q || score_response_buf_valid_q) begin
          protocol_error <= 1'b1;
        end else begin
          score_response_buf_valid_q <= 1'b1;
          score_response_buf_addr_q <= outstanding_score_read_addr_q;
          score_response_buf_data_q <= score_bank_rsp_rdata;
          outstanding_score_read_q <= 1'b0;
        end
      end

      if (value_response_valid) begin
        if (value_response_buf_valid_q || (!outstanding_score_read_q && !score_response_buf_valid_q)) begin
          protocol_error <= 1'b1;
        end else begin
          value_response_buf_valid_q <= 1'b1;
          value_response_buf_addr_q <= value_response_address;
          value_response_buf_data_q <= value_response_matrix;
        end
      end

      if (replay_request_fire) begin
        outstanding_score_read_q <= 1'b1;
        outstanding_score_read_addr_q <= value_read_req_address;
      end

      case (state_q)
        STATE_IDLE: begin
          if (command_valid && command_ready) begin
            block_index_q <= {{COUNT_W{{1'b0}}}};
            active_block_count_q <= {command_block_expr};
            active_multiplier_q <= command_score_multiplier;
            active_shift_q <= command_score_shift;
            state_q <= STATE_TILE_CMD;
          end
        end

        STATE_TILE_CMD: begin
          if (tile_command_valid && tile_command_ready) begin
            state_q <= STATE_TILE_INPUT;
          end
        end

        STATE_TILE_INPUT: begin
          if (tile_input_valid && tile_input_ready && input_last) begin
            state_q <= STATE_TILE_WAIT_RESULT;
          end
        end

        STATE_TILE_WAIT_RESULT: begin
          if (tile_result_valid && tile_result_ready) begin
            raw_score_row_q <= tile_result_score_row;
            scaled_score_row_q <= 256'd0;
            scale_lane_index_q <= 4'd0;
            state_q <= STATE_SCALE;
          end
        end

        STATE_SCALE: begin
{scale_body}
          if (scale_lane_index_q + SCORE_SCALE_LANES_PER_CYCLE >= 8) begin
            state_q <= STATE_FILL;
          end else begin
            scale_lane_index_q <= scale_lane_index_q + 4'd{scale_lanes};
          end
        end

        STATE_FILL: begin
          if (two_pass_fill_valid && two_pass_fill_ready) begin
            if (block_index_q + 1'b1 == active_block_count_q) begin
              state_q <= STATE_WAIT_RESULT;
            end else begin
              block_index_q <= block_index_q + 1'b1;
              state_q <= STATE_TILE_CMD;
            end
          end
        end

        STATE_WAIT_RESULT: begin
          if (result_valid && result_ready) begin
            state_q <= STATE_IDLE;
          end
        end

        default: begin
          state_q <= STATE_IDLE;
        end
      endcase

      if (replay_mismatch) begin
        score_response_buf_valid_q <= 1'b0;
        value_response_buf_valid_q <= 1'b0;
      end
    end
  end
endmodule
"""


def generate(config: dict[str, Any], out_dir: Path) -> None:
    params = _validate(config)
    top_name = str(params["top_name"])
    out_dir.mkdir(parents=True, exist_ok=True)

    tile_top = f"{top_name}__score_tile"
    bank_top = f"{top_name}__score_bank"
    two_pass_top = f"{top_name}__two_pass"

    with tempfile.TemporaryDirectory() as td:
      temp_root = Path(td)
      tile_dir = temp_root / "tile"
      bank_dir = temp_root / "bank"
      two_pass_dir = temp_root / "two_pass"

      generate_score_tile(
          {
              "top_name": tile_top,
              "dense_gemm_tile_stream": {
                  "array_m": 1,
                  "array_n": 8,
                  "precision": "int8",
                  "accum_bits": 32,
                  "result_mode": "packed_score_row",
              },
          },
          tile_dir,
      )
      generate_score_bank_proxy(
          {
              "top_name": bank_top,
              "attention_score_bank_proxy": {},
          },
          bank_dir,
      )
      generate_two_pass_stream(
          {
              "top_name": two_pass_top,
              "attention_two_pass_stream": {
                  "max_blocks": int(params["max_blocks"]),
                  "div_lanes_per_cycle": 1,
                  "divider_impl": "iterative_restoring",
              },
          },
          two_pass_dir,
      )

      tile_rtl = (tile_dir / "top.v").read_text(encoding="utf-8")
      bank_rtl = (bank_dir / "top.v").read_text(encoding="utf-8")
      two_pass_rtl = (two_pass_dir / "top.v").read_text(encoding="utf-8")
      tile_manifest = json.loads((tile_dir / "dense_gemm_tile_stream_manifest.json").read_text(encoding="utf-8"))
      bank_manifest = json.loads((bank_dir / "attention_score_bank_proxy_manifest.json").read_text(encoding="utf-8"))
      two_pass_manifest = json.loads((two_pass_dir / "attention_two_pass_stream_manifest.json").read_text(encoding="utf-8"))

    wrapper_rtl = _compose_wrapper(
        top_name=top_name,
        params=params,
        tile_top=tile_top,
        bank_top=bank_top,
        two_pass_top=two_pass_top,
    )
    (out_dir / "top.v").write_text(
        "\n\n".join([tile_rtl, bank_rtl, two_pass_rtl, wrapper_rtl]) + "\n",
        encoding="utf-8",
    )
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    manifest = {
        "version": 1,
        "generator": "npu/rtlgen/gen_attention_decode_score_local_cluster.py",
        "top_name": top_name,
        "semantic_profile": "decode_m1x8_score_sram_two_pass_iterdiv_v1",
        "max_blocks": int(params["max_blocks"]),
        "score_tile_result_mode": "packed_score_row",
        "score_tile_array_n": int(params["array_n"]),
        "score_scale_lanes_per_cycle": int(params["score_scale_lanes_per_cycle"]),
        "score_scaling": {
            "product_bits": 64,
            "rounding": "symmetric_magnitude_round_to_nearest",
            "shift_bits": 6,
            "shift_zero_valid": True,
            "saturation": "signed_s32",
            "metadata_source": "external_command_multiplier_shift",
        },
        "score_bank_macro_count": int(bank_manifest["macro_count"]),
        "score_bank_proxy_semantics": bank_manifest["proxy_semantics"],
        "value_replay": "external_ready_valid_address_matched",
        "divider_impl": str(params["divider_impl"]),
        "divider_cycles_per_command": two_pass_manifest["divider_cycles_per_command"],
        "read_outstanding": 1,
        "result_value_bits": 320,
        "submodules": {
            "score_tile_top_name": tile_top,
            "score_bank_top_name": bank_top,
            "two_pass_top_name": two_pass_top,
        },
        "submodule_manifests": {
            "score_tile": tile_manifest,
            "score_bank": bank_manifest,
            "two_pass": two_pass_manifest,
        },
    }
    (out_dir / "attention_decode_score_local_cluster_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
