#!/usr/bin/env python3
"""Generate an operational dense INT8 GEMM tile with narrow streaming IO."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: dict[str, Any]) -> dict[str, int | str]:
    top_name = str(config.get("top_name") or "").strip()
    if not top_name:
        raise SystemExit("config top_name must not be empty")
    body = config.get("dense_gemm_tile_stream")
    if not isinstance(body, dict):
        raise SystemExit("config must contain dense_gemm_tile_stream object")

    array_m = int(body.get("array_m", 4))
    array_n = int(body.get("array_n", 4))
    precision = str(body.get("precision", "int8")).strip().lower()
    accum_bits = int(body.get("accum_bits", 32))
    result_mode = str(body.get("result_mode", "scalar_stream")).strip().lower()

    if array_m < 1 or array_m > 16:
        raise SystemExit("dense_gemm_tile_stream.array_m must be in [1, 16]")
    if array_n < 1 or array_n > 16:
        raise SystemExit("dense_gemm_tile_stream.array_n must be in [1, 16]")
    if precision != "int8":
        raise SystemExit("dense_gemm_tile_stream.precision must be int8")
    if accum_bits != 32:
        raise SystemExit("dense_gemm_tile_stream.accum_bits must be 32")
    if result_mode not in {"scalar_stream", "packed_score_row"}:
        raise SystemExit("dense_gemm_tile_stream.result_mode must be scalar_stream or packed_score_row")
    if result_mode == "packed_score_row" and array_m != 1:
        raise SystemExit("dense_gemm_tile_stream.result_mode=packed_score_row requires array_m=1")

    params: dict[str, int | str] = {
        "array_m": array_m,
        "array_n": array_n,
        "precision": precision,
        "accum_bits": accum_bits,
        "result_mode": result_mode,
    }
    body.update(params)
    return params


def _top(*, top_name: str, params: dict[str, int | str]) -> str:
    array_m = int(params["array_m"])
    array_n = int(params["array_n"])
    acc_count = array_m * array_n
    row_bits = _clog2(array_m)
    col_bits = _clog2(array_n)
    index_bits = _clog2(acc_count)
    result_mode = str(params["result_mode"])
    packed_mode = result_mode == "packed_score_row"

    clear_lines = "\n".join(f"        accum[{idx}] <= 32'sd0;" for idx in range(acc_count))
    pack_clear = f"      result_score_row_q <= {{{array_n * 32}{{1'b0}}}};"
    if packed_mode:
        result_score_row_assign = "  assign result_score_row = result_score_row_q;"
        pack_capture_lines = "\n".join(
            f"            result_score_row_q[({col} * 32) +: 32] <= accum[{col}]"
            f" + ($signed(input_a[0 +: 8]) * $signed(input_b[({col} * 8) +: 8]));"
            for col in range(array_n)
        )
        result_step = "        state <= STATE_IDLE;"
    else:
        result_score_row_assign = f"  assign result_score_row = {{{array_n * 32}{{1'b0}}}};"
        pack_capture_lines = ""
        result_step = """        if (result_index_q == ACC_COUNT - 1) begin
          state <= STATE_IDLE;
        end else begin
          result_index_q <= result_index_q + 1'b1;
          if (result_col_q == ARRAY_N - 1) begin
            result_col_q <= {{COL_BITS{{1'b0}}}};
            result_row_q <= result_row_q + 1'b1;
          end else begin
            result_col_q <= result_col_q + 1'b1;
          end
        end"""

    return f"""// Auto-generated by npu/rtlgen/gen_dense_gemm_tile_stream.py
// Operational dense GEMM stream tile. This is a functional streaming tile,
// distinct from the PPA harness generated by gen_dense_gemm_tile.py.
module {top_name} (
    input  wire                         clk,
    input  wire                         rst_n,
    input  wire                         command_valid,
    output wire                         command_ready,
    input  wire                         input_valid,
    output wire                         input_ready,
    input  wire                         input_last,
    input  wire signed [{array_m * 8 - 1}:0] input_a,
    input  wire signed [{array_n * 8 - 1}:0] input_b,
    output wire                         result_valid,
    input  wire                         result_ready,
    output wire [{row_bits - 1}:0]      result_row,
    output wire [{col_bits - 1}:0]      result_col,
    output wire [{index_bits - 1}:0]    result_index,
    output wire signed [31:0]           result_value,
    output wire signed [{array_n * 32 - 1}:0] result_score_row
);
  localparam integer ARRAY_M = {array_m};
  localparam integer ARRAY_N = {array_n};
  localparam integer ACC_COUNT = {acc_count};
  localparam integer ROW_BITS = {row_bits};
  localparam integer COL_BITS = {col_bits};
  localparam integer INDEX_BITS = {index_bits};
  localparam [1:0] STATE_IDLE = 2'd0;
  localparam [1:0] STATE_ACCUM = 2'd1;
  localparam [1:0] STATE_RESULT = 2'd2;

  reg [1:0] state;
  reg [INDEX_BITS-1:0] result_index_q;
  reg [ROW_BITS-1:0] result_row_q;
  reg [COL_BITS-1:0] result_col_q;
  reg signed [31:0] accum [0:ACC_COUNT-1];
  reg signed [{array_n * 32 - 1}:0] result_score_row_q;

  integer row_iter;
  integer col_iter;
  integer acc_iter;
  assign command_ready = state == STATE_IDLE;
  assign input_ready = state == STATE_ACCUM;
  assign result_valid = state == STATE_RESULT;
  assign result_index = result_index_q;
  assign result_row = result_row_q;
  assign result_col = result_col_q;
  assign result_value = accum[result_index_q];
{result_score_row_assign}

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= STATE_IDLE;
      result_index_q <= {{INDEX_BITS{{1'b0}}}};
      result_row_q <= {{ROW_BITS{{1'b0}}}};
      result_col_q <= {{COL_BITS{{1'b0}}}};
{pack_clear}
      for (acc_iter = 0; acc_iter < ACC_COUNT; acc_iter = acc_iter + 1) begin
        accum[acc_iter] <= 32'sd0;
      end
    end else begin
      if (state == STATE_IDLE && command_valid) begin
        state <= STATE_ACCUM;
        result_index_q <= {{INDEX_BITS{{1'b0}}}};
        result_row_q <= {{ROW_BITS{{1'b0}}}};
        result_col_q <= {{COL_BITS{{1'b0}}}};
{pack_clear}
{clear_lines}
      end else if (state == STATE_ACCUM && input_valid) begin
        for (row_iter = 0; row_iter < ARRAY_M; row_iter = row_iter + 1) begin
          for (col_iter = 0; col_iter < ARRAY_N; col_iter = col_iter + 1) begin
            accum[row_iter * ARRAY_N + col_iter] <=
                accum[row_iter * ARRAY_N + col_iter]
                + ($signed(input_a[(row_iter * 8) +: 8]) * $signed(input_b[(col_iter * 8) +: 8]));
          end
        end
        if (input_last) begin
          state <= STATE_RESULT;
          result_index_q <= {{INDEX_BITS{{1'b0}}}};
          result_row_q <= {{ROW_BITS{{1'b0}}}};
          result_col_q <= {{COL_BITS{{1'b0}}}};
{pack_capture_lines}
        end
      end else if (state == STATE_RESULT && result_ready) begin
{result_step}
      end
    end
  end
endmodule
"""


def generate(config: dict[str, Any], out_dir: Path) -> None:
    params = _validate(config)
    top_name = str(config["top_name"]).strip()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "top.v").write_text(_top(top_name=top_name, params=params), encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    manifest = {
        "version": 1,
        "generator": "npu/rtlgen/gen_dense_gemm_tile_stream.py",
        "top_name": top_name,
        "semantic_profile": "operational_dense_gemm_outer_product_stream_s8_s8_acc32",
        "array_m": params["array_m"],
        "array_n": params["array_n"],
        "operand_bits": 8,
        "operand_signed": True,
        "accum_bits": params["accum_bits"],
        "accum_signed": True,
        "result_mode": params["result_mode"],
        "command_interface": "ready_valid_start",
        "input_interface": "ready_valid_vector_outer_product",
        "result_interface": "ready_valid_scalar_accumulator_stream",
        "command_clears_accumulators": True,
        "input_accepts_same_cycle_as_command": False,
        "result_order": "row_major",
        "all_accumulators_observable": True,
        "functional_observability": "row_col_index_value",
    }
    if params["result_mode"] == "packed_score_row":
        manifest["result_interface"] = "ready_valid_packed_score_row"
        manifest["result_order"] = "packed_score_row_lane_major"
        manifest["functional_observability"] = "packed_score_row"
        manifest["packed_score_row_semantics"] = {
            "array_m_required": 1,
            "lane_bits": 32,
            "lane_signed": True,
            "lane_order": "result_score_row[j*32 +: 32] == lane_j",
            "fill_score_row_compatible": True,
            "emission": "single_result_beat_per_command_after_final_input_accept",
            "backpressure": "result_score_row_stable_while_result_valid_and_not_ready",
        }
    (out_dir / "dense_gemm_tile_stream_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
