#!/usr/bin/env python3
"""Generate a radix-2 streamed exact-reduction tree with an embodied root finalizer."""

from __future__ import annotations

import argparse
import json
import math
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_score32_exact_partial_tree import generate as generate_tree
from npu.rtlgen.gen_attention_score32_exact_root_finalizer import generate as generate_finalizer
from npu.sim.perf.attention_exact_partial import (
    FINAL_LINK_BITS,
    FINAL_PAYLOAD_BITS,
    PARTIAL_LINK_BITS,
    PARTIAL_PAYLOAD_BITS,
    exact_finalized_tree_service_manifest,
)

JsonDict = dict[str, Any]


def _load(path: Path) -> JsonDict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"config must decode to a JSON object: {path}")
    return payload


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: JsonDict) -> JsonDict:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get("attention_score32_exact_finalized_tree")
    if not top_name or not isinstance(body, dict):
        raise SystemExit("config requires top_name and attention_score32_exact_finalized_tree")

    clusters = int(body.get("clusters", 16))
    radix = int(body.get("radix", 2))
    value_slices = int(body.get("value_slices", 16))
    head_id_bits = int(body.get("head_id_bits", 5))
    divider_lanes = int(body.get("divider_lanes", 8))
    if clusters < 2 or clusters > 16 or (clusters & (clusters - 1)):
        raise SystemExit("clusters must be a power of two in [2, 16]")
    if radix != 2:
        raise SystemExit("phase C only implements radix=2")
    if value_slices < 1 or value_slices > 16 or (value_slices & (value_slices - 1)):
        raise SystemExit("value_slices must be a power of two in [1, 16]")
    if head_id_bits < 1 or head_id_bits > 8:
        raise SystemExit("head_id_bits must be in [1, 8]")
    if divider_lanes not in {1, 2, 4, 8}:
        raise SystemExit("divider_lanes must be one of 1, 2, 4, 8")
    return {
        "top_name": top_name,
        "clusters": clusters,
        "radix": radix,
        "value_slices": value_slices,
        "head_id_bits": head_id_bits,
        "divider_lanes": divider_lanes,
    }


def _top_pin_bits(*, clusters: int, head_id_bits: int, stages: int, nodes: int, slice_bits: int) -> int:
    leaf_bits = clusters * (1 + 16 + head_id_bits + 32 + 33 + slice_bits + 1 + PARTIAL_PAYLOAD_BITS + 1)
    root_bits = 1 + 1 + 16 + head_id_bits + slice_bits + 1 + FINAL_PAYLOAD_BITS
    monitor_bits = 32 + 32 + 32 + 32 + (nodes * 32) + (stages * 32) + nodes + stages + 3
    return 2 + leaf_bits + root_bits + monitor_bits


def _top(*, top_name: str, tree_top_name: str, finalizer_top_name: str, clusters: int, value_slices: int, head_id_bits: int) -> str:
    slice_bits = _clog2(value_slices)
    node_count = clusters - 1
    stage_count = int(math.log2(clusters))
    return f"""// Auto-generated by npu/rtlgen/gen_attention_score32_exact_finalized_tree.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire [{clusters - 1}:0] leaf_valid,
    output wire [{clusters - 1}:0] leaf_ready,
    input  wire [{clusters * 16 - 1}:0] leaf_command_id,
    input  wire [{clusters * head_id_bits - 1}:0] leaf_head_id,
    input  wire [{clusters * 32 - 1}:0] leaf_global_max,
    input  wire [{clusters * 33 - 1}:0] leaf_exp_sum,
    input  wire [{clusters * slice_bits - 1}:0] leaf_slice,
    input  wire [{clusters - 1}:0] leaf_last,
    input  wire [{clusters * PARTIAL_PAYLOAD_BITS - 1}:0] leaf_value,
    output wire         root_valid,
    input  wire         root_ready,
    output wire [15:0]  root_command_id,
    output wire [{head_id_bits - 1}:0] root_head_id,
    output wire [{slice_bits - 1}:0] root_slice,
    output wire         root_last,
    output wire [319:0] root_value,
    output wire [31:0]  cycle_count,
    output wire [31:0]  root_completed_count,
    output wire [31:0]  finalizer_accepted_count,
    output wire [31:0]  tree_root_completed_count,
    output wire [{node_count * 32 - 1}:0] node_completed_count,
    output wire [{stage_count * 32 - 1}:0] stage_completed_count,
    output wire [{node_count - 1}:0] node_protocol_error,
    output wire [{stage_count - 1}:0] stage_protocol_error,
    output wire         tree_protocol_error,
    output wire         finalizer_protocol_error,
    output wire         protocol_error
);
  localparam integer PARTIAL_PAYLOAD_BITS = {PARTIAL_PAYLOAD_BITS};

  wire tree_root_valid;
  wire tree_root_ready;
  wire [15:0] tree_root_command_id;
  wire [{head_id_bits - 1}:0] tree_root_head_id;
  wire signed [31:0] tree_root_global_max;
  wire [32:0] tree_root_exp_sum;
  wire [{slice_bits - 1}:0] tree_root_slice;
  wire tree_root_last;
  wire [327:0] tree_root_value;
  wire [31:0] tree_cycle_count;
  wire [31:0] tree_root_completed_count_w;

  wire [31:0] finalizer_accepted_count_w;
  wire [31:0] finalizer_completed_count_w;
  wire [31:0] finalizer_cycle_count_w;

  assign cycle_count = finalizer_cycle_count_w;
  assign root_completed_count = finalizer_completed_count_w;
  assign finalizer_accepted_count = finalizer_accepted_count_w;
  assign tree_root_completed_count = tree_root_completed_count_w;
  assign protocol_error = tree_protocol_error | finalizer_protocol_error;

  {tree_top_name} u_tree (
      .clk(clk),
      .rst_n(rst_n),
      .leaf_valid(leaf_valid),
      .leaf_ready(leaf_ready),
      .leaf_command_id(leaf_command_id),
      .leaf_head_id(leaf_head_id),
      .leaf_global_max(leaf_global_max),
      .leaf_exp_sum(leaf_exp_sum),
      .leaf_slice(leaf_slice),
      .leaf_last(leaf_last),
      .leaf_value(leaf_value),
      .root_valid(tree_root_valid),
      .root_ready(tree_root_ready),
      .root_command_id(tree_root_command_id),
      .root_head_id(tree_root_head_id),
      .root_global_max(tree_root_global_max),
      .root_exp_sum(tree_root_exp_sum),
      .root_slice(tree_root_slice),
      .root_last(tree_root_last),
      .root_value(tree_root_value),
      .cycle_count(tree_cycle_count),
      .root_completed_count(tree_root_completed_count_w),
      .node_completed_count(node_completed_count),
      .stage_completed_count(stage_completed_count),
      .node_protocol_error(node_protocol_error),
      .stage_protocol_error(stage_protocol_error),
      .protocol_error(tree_protocol_error)
  );

  {finalizer_top_name} u_finalizer (
      .clk(clk),
      .rst_n(rst_n),
      .in_valid(tree_root_valid),
      .in_ready(tree_root_ready),
      .in_command_id(tree_root_command_id),
      .in_head_id(tree_root_head_id),
      .in_exp_sum(tree_root_exp_sum),
      .in_slice(tree_root_slice),
      .in_last(tree_root_last),
      .in_value(tree_root_value),
      .out_valid(root_valid),
      .out_ready(root_ready),
      .out_command_id(root_command_id),
      .out_head_id(root_head_id),
      .out_slice(root_slice),
      .out_last(root_last),
      .out_value(root_value),
      .accepted_count(finalizer_accepted_count_w),
      .completed_count(finalizer_completed_count_w),
      .cycle_count(finalizer_cycle_count_w),
      .protocol_error(finalizer_protocol_error)
  );
endmodule
"""


def generate(config: JsonDict, out_dir: Path) -> None:
    params = _validate(json.loads(json.dumps(config)))
    out_dir.mkdir(parents=True, exist_ok=True)

    tree_top_name = f"{params['top_name']}__partial_tree"
    finalizer_top_name = f"{params['top_name']}__root_finalizer"
    with tempfile.TemporaryDirectory(prefix="score32_exact_finalized_tree_") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        generate_tree(
            {
                "top_name": tree_top_name,
                "attention_score32_exact_partial_tree": {
                    "clusters": int(params["clusters"]),
                    "radix": int(params["radix"]),
                    "value_slices": int(params["value_slices"]),
                    "head_id_bits": int(params["head_id_bits"]),
                },
            },
            temp_dir / "tree",
        )
        generate_finalizer(
            {
                "top_name": finalizer_top_name,
                "attention_score32_exact_root_finalizer": {
                    "value_slices": int(params["value_slices"]),
                    "head_id_bits": int(params["head_id_bits"]),
                    "divider_lanes": int(params["divider_lanes"]),
                },
            },
            temp_dir / "finalizer",
        )
        tree_rtl = (temp_dir / "tree" / "top.v").read_text(encoding="utf-8")
        finalizer_rtl = (temp_dir / "finalizer" / "top.v").read_text(encoding="utf-8")
        tree_manifest = json.loads(
            (temp_dir / "tree" / "attention_score32_exact_partial_tree_manifest.json").read_text(encoding="utf-8")
        )
        finalizer_manifest = json.loads(
            (temp_dir / "finalizer" / "attention_score32_exact_root_finalizer_manifest.json").read_text(
                encoding="utf-8"
            )
        )

    top_text = _top(
        top_name=str(params["top_name"]),
        tree_top_name=tree_top_name,
        finalizer_top_name=finalizer_top_name,
        clusters=int(params["clusters"]),
        value_slices=int(params["value_slices"]),
        head_id_bits=int(params["head_id_bits"]),
    )
    (out_dir / "top.v").write_text(tree_rtl + "\n\n" + finalizer_rtl + "\n\n" + top_text, encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    node_count = int(params["clusters"]) - 1
    stage_count = int(math.log2(int(params["clusters"])))
    manifest = {
        "version": 1,
        "top_name": params["top_name"],
        "generator": "npu/rtlgen/gen_attention_score32_exact_finalized_tree.py",
        "semantic_profile": "score32_online_exact_finalized_radix2_tree_v1",
        "clusters": int(params["clusters"]),
        "radix": int(params["radix"]),
        "value_slices": int(params["value_slices"]),
        "head_id_bits": int(params["head_id_bits"]),
        "divider_lanes": int(params["divider_lanes"]),
        "tree_stages": stage_count,
        "tree_nodes": node_count,
        "result_interface": "clusters_ready_valid_exact_partial_leaf_streams_to_exact_finalized_root_stream",
        "partial_payload_bits_per_beat": PARTIAL_PAYLOAD_BITS,
        "partial_link_bits_per_beat": PARTIAL_LINK_BITS,
        "final_payload_bits_per_beat": FINAL_PAYLOAD_BITS,
        "final_link_bits_per_beat": FINAL_LINK_BITS,
        "equivalence_hash": False,
        "direct_328bit_links_unclosed": True,
        "final_divider_embodied": True,
        "macro_eval_excludes_io_pads": True,
        "top_pin_bits": _top_pin_bits(
            clusters=int(params["clusters"]),
            head_id_bits=int(params["head_id_bits"]),
            stages=stage_count,
            nodes=node_count,
            slice_bits=_clog2(int(params["value_slices"])),
        ),
        "theoretical_full_llama_service_manifest": exact_finalized_tree_service_manifest(
            clusters=int(params["clusters"]),
            heads=32,
            divider_lanes=int(params["divider_lanes"]),
        ),
        "submodule_manifests": {
            "partial_tree": tree_manifest,
            "root_finalizer": finalizer_manifest,
        },
    }
    (out_dir / "attention_score32_exact_finalized_tree_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
