#!/usr/bin/env python3
"""Generate a c2 exact-partial producer-coupled finalized tree slice."""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_decode_score_multivalue_cluster import generate as generate_cluster
from npu.rtlgen.gen_attention_score32_exact_banked_finalized_tree import (
    generate as generate_banked_tree,
)
from npu.sim.perf.attention_exact_partial import (
    FINAL_LINK_BITS,
    FINAL_PAYLOAD_BITS,
    PARTIAL_LINK_BITS,
    PARTIAL_PAYLOAD_BITS,
    exact_partial_producer_tree_service_manifest,
)

JsonDict = dict[str, Any]


def _load(path: Path) -> JsonDict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"config must decode to a JSON object: {path}")
    return payload


def _validate(config: JsonDict) -> JsonDict:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get("attention_score32_exact_partial_producer_tree")
    if not top_name or not isinstance(body, dict):
        raise SystemExit("config requires top_name and attention_score32_exact_partial_producer_tree")

    producers = int(body.get("producers", 2))
    clusters = int(body.get("clusters", 2))
    radix = int(body.get("radix", 2))
    max_blocks = int(body.get("max_blocks", 16384))
    value_slices = int(body.get("value_slices", 16))
    head_id_bits = int(body.get("head_id_bits", 5))
    divider_lanes = int(body.get("divider_lanes", 8))
    finalizer_banks = int(body.get("finalizer_banks", 59))

    if producers != 2:
        raise SystemExit("producer-coupled slice currently requires producers=2")
    if clusters != 2:
        raise SystemExit("producer-coupled slice currently requires clusters=2")
    if radix != 2:
        raise SystemExit("producer-coupled slice currently requires radix=2")
    if max_blocks < 8 or max_blocks > 16384 or (max_blocks & (max_blocks - 1)):
        raise SystemExit("max_blocks must be a power of two in [8, 16384]")
    if value_slices != 16:
        raise SystemExit("producer-coupled slice currently requires value_slices=16")
    if head_id_bits < 1 or head_id_bits > 8:
        raise SystemExit("head_id_bits must be in [1, 8]")
    if divider_lanes != 8:
        raise SystemExit("producer-coupled slice currently requires divider_lanes=8")
    if finalizer_banks != 59:
        raise SystemExit("producer-coupled slice currently requires finalizer_banks=59")

    return {
        "top_name": top_name,
        "producers": producers,
        "clusters": clusters,
        "radix": radix,
        "max_blocks": max_blocks,
        "value_slices": value_slices,
        "head_id_bits": head_id_bits,
        "divider_lanes": divider_lanes,
        "finalizer_banks": finalizer_banks,
    }


def _top(*, top_name: str, producer_top_name: str, tree_top_name: str, head_id_bits: int) -> str:
    return f"""// Auto-generated by npu/rtlgen/gen_attention_score32_exact_partial_producer_tree.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         command_valid,
    output wire         command_ready,
    input  wire [15:0]  command_id,
    input  wire [{head_id_bits - 1}:0] command_head_id,
    input  wire [14:0]  command_block_count,
    input  wire [31:0]  command_score_multiplier,
    input  wire [5:0]   command_score_shift,
    input  wire         producer0_input_valid,
    output wire         producer0_input_ready,
    input  wire         producer0_input_last,
    input  wire signed [7:0] producer0_input_a,
    input  wire signed [63:0] producer0_input_b,
    output wire         producer0_value_read_req_valid,
    input  wire         producer0_value_read_req_ready,
    output wire [13:0]  producer0_value_read_req_address,
    output wire [3:0]   producer0_value_read_req_slice,
    input  wire         producer0_value_response_valid,
    output wire         producer0_value_response_ready,
    input  wire [13:0]  producer0_value_response_address,
    input  wire [3:0]   producer0_value_response_slice,
    input  wire [511:0] producer0_value_response_matrix,
    input  wire         producer1_input_valid,
    output wire         producer1_input_ready,
    input  wire         producer1_input_last,
    input  wire signed [7:0] producer1_input_a,
    input  wire signed [63:0] producer1_input_b,
    output wire         producer1_value_read_req_valid,
    input  wire         producer1_value_read_req_ready,
    output wire [13:0]  producer1_value_read_req_address,
    output wire [3:0]   producer1_value_read_req_slice,
    input  wire         producer1_value_response_valid,
    output wire         producer1_value_response_ready,
    input  wire [13:0]  producer1_value_response_address,
    input  wire [3:0]   producer1_value_response_slice,
    input  wire [511:0] producer1_value_response_matrix,
    output wire         root_valid,
    input  wire         root_ready,
    output wire [15:0]  root_command_id,
    output wire [{head_id_bits - 1}:0] root_head_id,
    output wire [3:0]   root_slice,
    output wire         root_last,
    output wire [319:0] root_value,
    output wire [31:0]  cycle_count,
    output wire [31:0]  command_accept_count,
    output wire [31:0]  command_completed_count,
    output wire [31:0]  producer0_command_accept_count,
    output wire [31:0]  producer1_command_accept_count,
    output wire [31:0]  producer0_partial_completed_count,
    output wire [31:0]  producer1_partial_completed_count,
    output wire [31:0]  producer0_leaf_stall_cycles,
    output wire [31:0]  producer1_leaf_stall_cycles,
    output wire [1:0]   producer_partial_valid,
    output wire [1:0]   producer_partial_ready,
    output wire [1:0]   producer_partial_last,
    output wire [31:0]  tree_root_completed_count,
    output wire [31:0]  finalizer_accepted_count,
    output wire [31:0]  order_fifo_occupancy,
    output wire [31:0]  order_fifo_high_watermark,
    output wire [31:0]  order_enqueued_count,
    output wire [31:0]  order_dequeued_count,
    output wire [31:0]  tree_dispatch_stall_cycles,
    output wire [31:0]  dispatch_bank_id,
    output wire [31:0]  head_bank_id,
    output wire [31:0]  node_completed_count,
    output wire [31:0]  stage_completed_count,
    output wire [0:0]   node_protocol_error,
    output wire [0:0]   stage_protocol_error,
    output wire [58:0]  bank_protocol_error,
    output wire [58:0]  bank_outstanding,
    output wire [1:0]   producer_protocol_error,
    output wire         tree_protocol_error,
    output wire         order_protocol_error,
    output wire         finalizer_protocol_error,
    output wire         protocol_error
);
  localparam integer PARTIAL_PAYLOAD_BITS = {PARTIAL_PAYLOAD_BITS};

  wire producer0_command_ready_w;
  wire producer1_command_ready_w;
  wire producer0_result_valid_w;
  wire producer0_result_ready_w;
  wire [15:0] producer0_result_command_id_w;
  wire [{head_id_bits - 1}:0] producer0_result_head_id_w;
  wire signed [31:0] producer0_result_global_max_w;
  wire [32:0] producer0_result_exp_sum_w;
  wire [3:0] producer0_result_slice_w;
  wire producer0_result_last_w;
  wire [327:0] producer0_result_value_w;
  wire [31:0] producer0_accepted_count_w;
  wire [31:0] producer0_completed_count_w;
  wire [31:0] producer0_cycle_count_w;
  wire producer0_protocol_error_w;
  wire producer1_result_valid_w;
  wire producer1_result_ready_w;
  wire [15:0] producer1_result_command_id_w;
  wire [{head_id_bits - 1}:0] producer1_result_head_id_w;
  wire signed [31:0] producer1_result_global_max_w;
  wire [32:0] producer1_result_exp_sum_w;
  wire [3:0] producer1_result_slice_w;
  wire producer1_result_last_w;
  wire [327:0] producer1_result_value_w;
  wire [31:0] producer1_accepted_count_w;
  wire [31:0] producer1_completed_count_w;
  wire [31:0] producer1_cycle_count_w;
  wire producer1_protocol_error_w;
  wire [31:0] tree_cycle_count_w;
  wire [31:0] root_completed_count_w;
  reg [31:0] cycle_count_q;
  reg [31:0] command_accept_count_q;
  reg [31:0] command_completed_count_q;
  reg [31:0] producer0_leaf_stall_cycles_q;
  reg [31:0] producer1_leaf_stall_cycles_q;

  wire command_fire_w = command_valid && command_ready;
  wire producer_command_valid_w = command_valid && command_ready;
  wire root_fire_w = root_valid && root_ready;

  wire [1:0] tree_leaf_valid_w;
  wire [1:0] tree_leaf_ready_w;
  wire [31:0] tree_leaf_command_id_w;
  wire [{2 * head_id_bits - 1}:0] tree_leaf_head_id_w;
  wire [63:0] tree_leaf_global_max_w;
  wire [65:0] tree_leaf_exp_sum_w;
  wire [7:0] tree_leaf_slice_w;
  wire [1:0] tree_leaf_last_w;
  wire [655:0] tree_leaf_value_w;

  assign command_ready = producer0_command_ready_w && producer1_command_ready_w;
  assign cycle_count = cycle_count_q;
  assign command_accept_count = command_accept_count_q;
  assign command_completed_count = command_completed_count_q;
  assign producer0_command_accept_count = producer0_accepted_count_w;
  assign producer1_command_accept_count = producer1_accepted_count_w;
  assign producer0_partial_completed_count = producer0_completed_count_w;
  assign producer1_partial_completed_count = producer1_completed_count_w;
  assign producer0_leaf_stall_cycles = producer0_leaf_stall_cycles_q;
  assign producer1_leaf_stall_cycles = producer1_leaf_stall_cycles_q;
  assign producer_partial_valid = {{producer1_result_valid_w, producer0_result_valid_w}};
  assign producer_partial_ready = {{producer1_result_ready_w, producer0_result_ready_w}};
  assign producer_partial_last = {{producer1_result_last_w, producer0_result_last_w}};
  assign producer_protocol_error = {{producer1_protocol_error_w, producer0_protocol_error_w}};
  assign protocol_error =
      producer0_protocol_error_w || producer1_protocol_error_w || tree_protocol_error || order_protocol_error
      || finalizer_protocol_error;

  assign tree_leaf_valid_w[0] = producer0_result_valid_w;
  assign tree_leaf_valid_w[1] = producer1_result_valid_w;
  assign producer0_result_ready_w = tree_leaf_ready_w[0];
  assign producer1_result_ready_w = tree_leaf_ready_w[1];
  assign tree_leaf_command_id_w[0 +: 16] = producer0_result_command_id_w;
  assign tree_leaf_command_id_w[16 +: 16] = producer1_result_command_id_w;
  assign tree_leaf_head_id_w[0 +: {head_id_bits}] = producer0_result_head_id_w;
  assign tree_leaf_head_id_w[{head_id_bits} +: {head_id_bits}] = producer1_result_head_id_w;
  assign tree_leaf_global_max_w[0 +: 32] = producer0_result_global_max_w;
  assign tree_leaf_global_max_w[32 +: 32] = producer1_result_global_max_w;
  assign tree_leaf_exp_sum_w[0 +: 33] = producer0_result_exp_sum_w;
  assign tree_leaf_exp_sum_w[33 +: 33] = producer1_result_exp_sum_w;
  assign tree_leaf_slice_w[0 +: 4] = producer0_result_slice_w;
  assign tree_leaf_slice_w[4 +: 4] = producer1_result_slice_w;
  assign tree_leaf_last_w[0] = producer0_result_last_w;
  assign tree_leaf_last_w[1] = producer1_result_last_w;
  assign tree_leaf_value_w[0 +: PARTIAL_PAYLOAD_BITS] = producer0_result_value_w;
  assign tree_leaf_value_w[PARTIAL_PAYLOAD_BITS +: PARTIAL_PAYLOAD_BITS] = producer1_result_value_w;

  {producer_top_name} u_producer_0 (
      .clk(clk),
      .rst_n(rst_n),
      .command_valid(producer_command_valid_w),
      .command_ready(producer0_command_ready_w),
      .command_id(command_id),
      .command_head_id(command_head_id),
      .command_block_count(command_block_count),
      .command_score_multiplier(command_score_multiplier),
      .command_score_shift(command_score_shift),
      .input_valid(producer0_input_valid),
      .input_ready(producer0_input_ready),
      .input_last(producer0_input_last),
      .input_a(producer0_input_a),
      .input_b(producer0_input_b),
      .value_read_req_valid(producer0_value_read_req_valid),
      .value_read_req_ready(producer0_value_read_req_ready),
      .value_read_req_address(producer0_value_read_req_address),
      .value_read_req_slice(producer0_value_read_req_slice),
      .value_response_valid(producer0_value_response_valid),
      .value_response_ready(producer0_value_response_ready),
      .value_response_address(producer0_value_response_address),
      .value_response_slice(producer0_value_response_slice),
      .value_response_matrix(producer0_value_response_matrix),
      .result_valid(producer0_result_valid_w),
      .result_ready(producer0_result_ready_w),
      .result_command_id(producer0_result_command_id_w),
      .result_head_id(producer0_result_head_id_w),
      .result_global_max(producer0_result_global_max_w),
      .result_exp_sum(producer0_result_exp_sum_w),
      .result_slice(producer0_result_slice_w),
      .result_last(producer0_result_last_w),
      .result_value(producer0_result_value_w),
      .accepted_count(producer0_accepted_count_w),
      .completed_count(producer0_completed_count_w),
      .cycle_count(producer0_cycle_count_w),
      .protocol_error(producer0_protocol_error_w)
  );

  {producer_top_name} u_producer_1 (
      .clk(clk),
      .rst_n(rst_n),
      .command_valid(producer_command_valid_w),
      .command_ready(producer1_command_ready_w),
      .command_id(command_id),
      .command_head_id(command_head_id),
      .command_block_count(command_block_count),
      .command_score_multiplier(command_score_multiplier),
      .command_score_shift(command_score_shift),
      .input_valid(producer1_input_valid),
      .input_ready(producer1_input_ready),
      .input_last(producer1_input_last),
      .input_a(producer1_input_a),
      .input_b(producer1_input_b),
      .value_read_req_valid(producer1_value_read_req_valid),
      .value_read_req_ready(producer1_value_read_req_ready),
      .value_read_req_address(producer1_value_read_req_address),
      .value_read_req_slice(producer1_value_read_req_slice),
      .value_response_valid(producer1_value_response_valid),
      .value_response_ready(producer1_value_response_ready),
      .value_response_address(producer1_value_response_address),
      .value_response_slice(producer1_value_response_slice),
      .value_response_matrix(producer1_value_response_matrix),
      .result_valid(producer1_result_valid_w),
      .result_ready(producer1_result_ready_w),
      .result_command_id(producer1_result_command_id_w),
      .result_head_id(producer1_result_head_id_w),
      .result_global_max(producer1_result_global_max_w),
      .result_exp_sum(producer1_result_exp_sum_w),
      .result_slice(producer1_result_slice_w),
      .result_last(producer1_result_last_w),
      .result_value(producer1_result_value_w),
      .accepted_count(producer1_accepted_count_w),
      .completed_count(producer1_completed_count_w),
      .cycle_count(producer1_cycle_count_w),
      .protocol_error(producer1_protocol_error_w)
  );

  {tree_top_name} u_banked_tree (
      .clk(clk),
      .rst_n(rst_n),
      .leaf_valid(tree_leaf_valid_w),
      .leaf_ready(tree_leaf_ready_w),
      .leaf_command_id(tree_leaf_command_id_w),
      .leaf_head_id(tree_leaf_head_id_w),
      .leaf_global_max(tree_leaf_global_max_w),
      .leaf_exp_sum(tree_leaf_exp_sum_w),
      .leaf_slice(tree_leaf_slice_w),
      .leaf_last(tree_leaf_last_w),
      .leaf_value(tree_leaf_value_w),
      .root_valid(root_valid),
      .root_ready(root_ready),
      .root_command_id(root_command_id),
      .root_head_id(root_head_id),
      .root_slice(root_slice),
      .root_last(root_last),
      .root_value(root_value),
      .cycle_count(tree_cycle_count_w),
      .root_completed_count(root_completed_count_w),
      .finalizer_accepted_count(finalizer_accepted_count),
      .tree_root_completed_count(tree_root_completed_count),
      .order_fifo_occupancy(order_fifo_occupancy),
      .order_fifo_high_watermark(order_fifo_high_watermark),
      .order_enqueued_count(order_enqueued_count),
      .order_dequeued_count(order_dequeued_count),
      .dispatch_stall_cycles(tree_dispatch_stall_cycles),
      .dispatch_bank_id(dispatch_bank_id),
      .head_bank_id(head_bank_id),
      .node_completed_count(node_completed_count),
      .stage_completed_count(stage_completed_count),
      .node_protocol_error(node_protocol_error),
      .stage_protocol_error(stage_protocol_error),
      .bank_protocol_error(bank_protocol_error),
      .bank_outstanding(bank_outstanding),
      .tree_protocol_error(tree_protocol_error),
      .order_protocol_error(order_protocol_error),
      .finalizer_protocol_error(finalizer_protocol_error),
      .protocol_error()
  );

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      cycle_count_q <= 32'd0;
      command_accept_count_q <= 32'd0;
      command_completed_count_q <= 32'd0;
      producer0_leaf_stall_cycles_q <= 32'd0;
      producer1_leaf_stall_cycles_q <= 32'd0;
    end else begin
      cycle_count_q <= cycle_count_q + 1'b1;
      if (command_fire_w) begin
        command_accept_count_q <= command_accept_count_q + 1'b1;
      end
      if (root_fire_w && root_last) begin
        command_completed_count_q <= command_completed_count_q + 1'b1;
      end
      if (producer0_result_valid_w && !producer0_result_ready_w) begin
        producer0_leaf_stall_cycles_q <= producer0_leaf_stall_cycles_q + 1'b1;
      end
      if (producer1_result_valid_w && !producer1_result_ready_w) begin
        producer1_leaf_stall_cycles_q <= producer1_leaf_stall_cycles_q + 1'b1;
      end
    end
  end
endmodule
"""


def generate(config: JsonDict, out_dir: Path) -> None:
    params = _validate(json.loads(json.dumps(config)))
    top_name = str(params["top_name"])
    producer_top_name = f"{top_name}__producer"
    tree_top_name = f"{top_name}__banked_tree"
    head_id_bits = int(params["head_id_bits"])

    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="score32_exact_partial_producer_tree_") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        producer_dir = temp_dir / "producer"
        tree_dir = temp_dir / "tree"
        generate_cluster(
            {
                "top_name": producer_top_name,
                "attention_decode_score_multivalue_cluster": {
                    "max_blocks": int(params["max_blocks"]),
                    "array_n": 8,
                    "value_slices": int(params["value_slices"]),
                    "divider_impl": "iterative_restoring",
                    "score_scale_lanes_per_cycle": 1,
                    "result_mode": "exact_partial",
                    "head_id_bits": head_id_bits,
                },
            },
            producer_dir,
        )
        generate_banked_tree(
            {
                "top_name": tree_top_name,
                "attention_score32_exact_banked_finalized_tree": {
                    "clusters": 2,
                    "radix": 2,
                    "value_slices": int(params["value_slices"]),
                    "head_id_bits": head_id_bits,
                    "divider_lanes": int(params["divider_lanes"]),
                    "finalizer_banks": int(params["finalizer_banks"]),
                },
            },
            tree_dir,
        )
        producer_rtl = (producer_dir / "top.v").read_text(encoding="utf-8")
        tree_rtl = (tree_dir / "top.v").read_text(encoding="utf-8")
        producer_manifest = json.loads(
            (producer_dir / "attention_decode_score_multivalue_cluster_manifest.json").read_text(encoding="utf-8")
        )
        tree_manifest = json.loads(
            (tree_dir / "attention_score32_exact_banked_finalized_tree_manifest.json").read_text(encoding="utf-8")
        )

    top_text = _top(
        top_name=top_name,
        producer_top_name=producer_top_name,
        tree_top_name=tree_top_name,
        head_id_bits=head_id_bits,
    )
    (out_dir / "top.v").write_text(producer_rtl + "\n\n" + tree_rtl + "\n\n" + top_text, encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    service_model = exact_partial_producer_tree_service_manifest(
        heads=int(config.get("probe_defaults", {}).get("heads", 32)) if isinstance(config.get("probe_defaults"), dict) else 32,
        max_blocks=int(params["max_blocks"]),
        divider_lanes=int(params["divider_lanes"]),
        finalizer_banks=int(params["finalizer_banks"]),
    )
    manifest = {
        "version": 1,
        "generator": "npu/rtlgen/gen_attention_score32_exact_partial_producer_tree.py",
        "top_name": top_name,
        "semantic_profile": "score32_online_exact_partial_two_producer_coupled_banked_tree_v1",
        "producers": 2,
        "clusters": 2,
        "radix": 2,
        "max_blocks": int(params["max_blocks"]),
        "value_slices": int(params["value_slices"]),
        "head_id_bits": head_id_bits,
        "divider_lanes": int(params["divider_lanes"]),
        "finalizer_banks": int(params["finalizer_banks"]),
        "producer_result_mode": "exact_partial",
        "command_schedule_contract": "in_order_head_commands_broadcast_to_both_producers",
        "head_mapping_contract": "explicit_head_id_no_tile_or_wave_inference",
        "result_interface": "two_exact_partial_producers_to_c2_ordered_banked_exact_finalized_tree",
        "partial_payload_bits_per_beat": PARTIAL_PAYLOAD_BITS,
        "partial_link_bits_per_beat": PARTIAL_LINK_BITS,
        "final_payload_bits_per_beat": FINAL_PAYLOAD_BITS,
        "final_link_bits_per_beat": FINAL_LINK_BITS,
        "comparison_baseline_contract": service_model["comparison_baseline_contract"],
        "comparison_cycle_origin": service_model["comparison_cycle_origin"],
        "diagnostic_only_baseline": service_model["diagnostic_only_baseline"],
        "llama_tile_cadence_unclosed": True,
        "producer_block_workload_assumptions": service_model["producer_block_workload_assumptions"],
        "exact_protocols": {
            "producer_partial_protocol": service_model["producer_partial_protocol"],
            "finalized_protocol": service_model["finalized_protocol"],
        },
        "remaining_abstractions": service_model["remaining_abstractions"],
        "equivalence_hash": False,
        "service_model": service_model,
        "submodule_manifests": {
            "producer": producer_manifest,
            "banked_tree": tree_manifest,
        },
    }
    if isinstance(config.get("probe_defaults"), dict):
        manifest["checked_in_probe_defaults"] = config["probe_defaults"]
    (out_dir / "attention_score32_exact_partial_producer_tree_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
