#!/usr/bin/env python3
"""Generate a two-pass attention reducer shared across multiple value slices."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: dict[str, Any]) -> dict[str, int | str]:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get("attention_two_pass_multivalue_stream")
    if not top_name or not isinstance(body, dict):
        raise SystemExit("config requires top_name and attention_two_pass_multivalue_stream")
    max_blocks = int(body.get("max_blocks", 16384))
    value_slices = int(body.get("value_slices", 16))
    divider_impl = str(body.get("divider_impl", "iterative_restoring"))
    fsm_encoding = str(body.get("fsm_encoding", "default")).strip().lower()
    if max_blocks < 8 or max_blocks > 16384 or max_blocks & (max_blocks - 1):
        raise SystemExit("max_blocks must be a power of two in [8, 16384]")
    if value_slices < 1 or value_slices > 16 or value_slices & (value_slices - 1):
        raise SystemExit("value_slices must be a power of two in [1, 16]")
    if divider_impl != "iterative_restoring":
        raise SystemExit("divider_impl must be iterative_restoring")
    if fsm_encoding not in {"default", "binary"}:
        raise SystemExit("fsm_encoding must be default or binary")
    body.update({"max_blocks": max_blocks, "value_slices": value_slices, "divider_impl": divider_impl})
    return {
        "top_name": top_name,
        "max_blocks": max_blocks,
        "value_slices": value_slices,
        "divider_impl": divider_impl,
        "fsm_encoding": fsm_encoding,
    }


def _exp_cases() -> str:
    return "\n".join(
        f"      32'd{bucket}: exp_lut = 16'd{max(1, int(math.exp(-(bucket / 256.0)) * 65535 + 0.5))};"
        for bucket in range(2049)
    )


def _clear_cases(value_slices: int) -> str:
    cases = []
    for value_slice in range(value_slices):
        assignments = "\n".join(
            f"          numerator_accum[{value_slice * 8 + lane}] <= 41'sd0;" for lane in range(8)
        )
        cases.append(f"        {value_slice}: begin\n{assignments}\n        end")
    return "\n".join(cases)


def _accumulate_cases(value_slices: int) -> str:
    cases = []
    for value_slice in range(value_slices):
        assignments = []
        for lane in range(8):
            assignments.append(
                f"          numerator_accum[{value_slice * 8 + lane}] <= "
                f"numerator_accum[{value_slice * 8 + lane}] + block_numerator[{lane}];"
            )
        cases.append(f"        {value_slice}: begin\n" + "\n".join(assignments) + "\n        end")
    return "\n".join(cases)


def _top(*, top_name: str, max_blocks: int, value_slices: int, fsm_encoding: str) -> str:
    addr_bits = _clog2(max_blocks)
    count_bits = _clog2(max_blocks + 1)
    slice_bits = _clog2(value_slices)
    value_dims = value_slices * 8
    dim_bits = _clog2(value_dims)
    fsm_attribute = '(* fsm_encoding = "binary" *) ' if fsm_encoding == "binary" else ""
    return f"""// Auto-generated by npu/rtlgen/gen_attention_two_pass_multivalue_stream.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         command_valid,
    output wire         command_ready,
    input  wire [15:0]  command_id,
    input  wire [{count_bits - 1}:0] command_block_count,
    input  wire         fill_valid,
    output wire         fill_ready,
    input  wire [255:0] fill_score_row,
    output wire         score_write_valid,
    input  wire         score_write_ready,
    output wire [{addr_bits - 1}:0] score_write_addr,
    output wire [255:0] score_write_data,
    output wire         score_read_req_valid,
    input  wire         score_read_req_ready,
    output wire [{addr_bits - 1}:0] score_read_req_addr,
    input  wire         score_replay_valid,
    output wire         score_replay_ready,
    input  wire [255:0] score_replay_row,
    output wire         value_read_req_valid,
    input  wire         value_read_req_ready,
    output wire [{addr_bits - 1}:0] value_read_req_address,
    output wire [{slice_bits - 1}:0] value_read_req_slice,
    input  wire         value_response_valid,
    output wire         value_response_ready,
    input  wire [{addr_bits - 1}:0] value_response_address,
    input  wire [{slice_bits - 1}:0] value_response_slice,
    input  wire [511:0] value_response_matrix,
    output reg          result_valid,
    input  wire         result_ready,
    output reg  [15:0]  result_command_id,
    output reg  signed [31:0] result_global_max,
    output reg  [32:0]  result_exp_sum,
    output reg  [{slice_bits - 1}:0] result_slice,
    output wire         result_last,
    output reg  [319:0] result_value,
    output reg  [31:0]  accepted_count,
    output reg  [31:0]  completed_count,
    output reg  [31:0]  cycle_count,
    output reg          protocol_error
);
  localparam integer MAX_BLOCKS = {max_blocks};
  localparam integer VALUE_SLICES = {value_slices};
  localparam integer VALUE_DIMS = {value_dims};
  localparam [3:0] IDLE = 4'd0, FILL = 4'd1, CLEAR = 4'd2,
      SCORE_REQ = 4'd3, SCORE_DATA = 4'd4, VALUE_REQ = 4'd5,
      VALUE_DATA = 4'd6, DIVIDE = 4'd7, DIV_LOAD = 4'd8,
      DIV_ITER = 4'd9, RESULT = 4'd10;

  {fsm_attribute}reg [3:0] state;
  reg [15:0] active_command_id;
  reg [{count_bits - 1}:0] active_block_count;
  reg [{count_bits - 1}:0] fill_count;
  reg [{addr_bits - 1}:0] read_index;
  reg [{slice_bits - 1}:0] value_slice_index;
  reg [{slice_bits - 1}:0] clear_slice_index;
  reg [{dim_bits - 1}:0] div_index;
  reg signed [31:0] global_max;
  reg [32:0] exp_sum_accum;
  reg signed [40:0] numerator_accum [0:VALUE_DIMS-1];
  reg [15:0] block_weight [0:7];
  reg [19:0] block_sum;
  reg signed [40:0] block_numerator [0:7];

  integer row_idx;
  integer lane_idx;
  reg signed [31:0] block_max;
  reg signed [31:0] score_lane;
  reg signed [32:0] delta_score;
  reg [32:0] exp_bucket;
  reg [15:0] exp_weight;
  reg [19:0] block_sum_next;
  reg [40:0] numerator_magnitude;
  reg [57:0] final_magnitude;
  reg div_negative;
  reg [6:0] div_bit_count;
  reg [57:0] div_quotient;
  reg [33:0] div_remainder;
  reg [33:0] div_trial_remainder;
  reg [57:0] div_next_quotient;

  assign command_ready = state == IDLE;
  assign fill_ready = state == FILL && score_write_ready;
  assign score_write_valid = state == FILL && fill_valid;
  assign score_write_addr = fill_count[{addr_bits - 1}:0];
  assign score_write_data = fill_score_row;
  assign score_read_req_valid = state == SCORE_REQ;
  assign score_read_req_addr = read_index;
  assign score_replay_ready = state == SCORE_DATA;
  assign value_read_req_valid = state == VALUE_REQ;
  assign value_read_req_address = read_index;
  assign value_read_req_slice = value_slice_index;
  assign value_response_ready = state == VALUE_DATA;
  assign result_last = result_slice == VALUE_SLICES - 1;

  function automatic [15:0] exp_lut;
    input [31:0] bucket;
    begin
      case (bucket)
{_exp_cases()}
      default: exp_lut = 16'd0;
      endcase
    end
  endfunction

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= IDLE;
      active_command_id <= 16'd0;
      active_block_count <= 0;
      fill_count <= 0;
      read_index <= 0;
      value_slice_index <= 0;
      clear_slice_index <= 0;
      div_index <= 0;
      global_max <= -32'sh8000_0000;
      exp_sum_accum <= 33'd0;
      result_valid <= 1'b0;
      result_command_id <= 16'd0;
      result_global_max <= 32'sd0;
      result_exp_sum <= 33'd0;
      result_slice <= 0;
      result_value <= 320'd0;
      accepted_count <= 32'd0;
      completed_count <= 32'd0;
      cycle_count <= 32'd0;
      protocol_error <= 1'b0;
      block_sum <= 20'd0;
      numerator_magnitude <= 41'd0;
      final_magnitude <= 58'd0;
      div_negative <= 1'b0;
      div_bit_count <= 7'd0;
      div_quotient <= 58'd0;
      div_remainder <= 34'd0;
    end else begin
      cycle_count <= cycle_count + 1'b1;

      if (state == IDLE && command_valid && command_ready) begin
        state <= FILL;
        active_command_id <= command_id;
        active_block_count <= command_block_count;
        fill_count <= 0;
        global_max <= -32'sh8000_0000;
        accepted_count <= accepted_count + 1'b1;
      end

      if (state == FILL && fill_valid && fill_ready) begin
        block_max = $signed(fill_score_row[0 +: 32]);
        for (row_idx = 1; row_idx < 8; row_idx = row_idx + 1) begin
          score_lane = $signed(fill_score_row[(row_idx * 32) +: 32]);
          if (score_lane > block_max) block_max = score_lane;
        end
        if (fill_count == 0 || block_max > global_max) global_max <= block_max;
        fill_count <= fill_count + 1'b1;
        if (fill_count + 1'b1 == active_block_count) begin
          state <= CLEAR;
          clear_slice_index <= 0;
          read_index <= 0;
          exp_sum_accum <= 33'd0;
        end
      end

      if (state == CLEAR) begin
        case (clear_slice_index)
{_clear_cases(value_slices)}
        endcase
        if (clear_slice_index == VALUE_SLICES - 1) begin
          state <= SCORE_REQ;
        end else begin
          clear_slice_index <= clear_slice_index + 1'b1;
        end
      end

      if (state == SCORE_REQ && score_read_req_valid && score_read_req_ready) begin
        state <= SCORE_DATA;
      end

      if (state == SCORE_DATA && score_replay_valid && score_replay_ready) begin
        block_sum_next = 20'd0;
        for (row_idx = 0; row_idx < 8; row_idx = row_idx + 1) begin
          score_lane = $signed(score_replay_row[(row_idx * 32) +: 32]);
          delta_score = $signed({{global_max[31], global_max}})
              - $signed({{score_lane[31], score_lane}});
          if (delta_score < 0) delta_score = 33'sd0;
          exp_bucket = (delta_score + 33'd524288) >> 20;
          exp_weight = exp_lut(exp_bucket[31:0]);
          block_weight[row_idx] <= exp_weight;
          block_sum_next = block_sum_next + exp_weight;
        end
        block_sum <= block_sum_next;
        value_slice_index <= 0;
        state <= VALUE_REQ;
      end

      if (state == VALUE_REQ && value_read_req_valid && value_read_req_ready) begin
        state <= VALUE_DATA;
      end

      if (state == VALUE_DATA && value_response_valid && value_response_ready) begin
        if (value_response_address != read_index || value_response_slice != value_slice_index) begin
          protocol_error <= 1'b1;
        end else begin
          for (lane_idx = 0; lane_idx < 8; lane_idx = lane_idx + 1) begin
            block_numerator[lane_idx] = 41'sd0;
            for (row_idx = 0; row_idx < 8; row_idx = row_idx + 1) begin
              block_numerator[lane_idx] = block_numerator[lane_idx]
                  + ($signed(value_response_matrix[((row_idx * 8 + lane_idx) * 8) +: 8])
                  * $signed({{1'b0, block_weight[row_idx]}}));
            end
          end
          case (value_slice_index)
{_accumulate_cases(value_slices)}
          endcase
          if (value_slice_index == 0) exp_sum_accum <= exp_sum_accum + block_sum;
          if (value_slice_index == VALUE_SLICES - 1) begin
            if (read_index + 1'b1 == active_block_count) begin
              div_index <= 0;
              result_command_id <= active_command_id;
              result_global_max <= global_max;
              result_exp_sum <= exp_sum_accum;
              result_value <= 320'd0;
              state <= DIVIDE;
            end else begin
              read_index <= read_index + 1'b1;
              state <= SCORE_REQ;
            end
          end else begin
            value_slice_index <= value_slice_index + 1'b1;
            state <= VALUE_REQ;
          end
        end
      end

      if (state == DIVIDE) begin
        div_negative <= numerator_accum[div_index] < 0;
        if (numerator_accum[div_index] < 0)
          numerator_magnitude <= (~numerator_accum[div_index]) + 1'b1;
        else
          numerator_magnitude <= numerator_accum[div_index];
        state <= DIV_LOAD;
      end

      if (state == DIV_LOAD) begin
        final_magnitude <= ({{17'd0, numerator_magnitude}} << 16)
            - {{17'd0, numerator_magnitude}} + (exp_sum_accum >> 1);
        div_quotient <= 58'd0;
        div_remainder <= 34'd0;
        div_bit_count <= 7'd58;
        state <= DIV_ITER;
      end

      if (state == DIV_ITER) begin
        div_trial_remainder = {{div_remainder[32:0], final_magnitude[57]}};
        div_next_quotient = {{div_quotient[56:0], 1'b0}};
        if (div_trial_remainder >= {{1'b0, exp_sum_accum}}) begin
          div_remainder <= div_trial_remainder - {{1'b0, exp_sum_accum}};
          div_next_quotient[0] = 1'b1;
        end else begin
          div_remainder <= div_trial_remainder;
        end
        final_magnitude <= {{final_magnitude[56:0], 1'b0}};
        div_quotient <= div_next_quotient;
        if (div_bit_count == 1) begin
          if (div_negative)
            result_value[(div_index[2:0] * 40) +: 40] <= (~div_next_quotient[39:0]) + 1'b1;
          else
            result_value[(div_index[2:0] * 40) +: 40] <= div_next_quotient[39:0];
          if (div_index[2:0] == 3'd7) begin
            result_slice <= div_index[{dim_bits - 1}:3];
            result_valid <= 1'b1;
            state <= RESULT;
          end else begin
            div_index <= div_index + 1'b1;
            state <= DIVIDE;
          end
        end else begin
          div_bit_count <= div_bit_count - 1'b1;
        end
      end

      if (state == RESULT && result_valid && result_ready) begin
        result_valid <= 1'b0;
        if (div_index == VALUE_DIMS - 1) begin
          completed_count <= completed_count + 1'b1;
          state <= IDLE;
        end else begin
          div_index <= div_index + 1'b1;
          result_value <= 320'd0;
          state <= DIVIDE;
        end
      end
    end
  end
endmodule
"""


def generate(config: dict[str, Any], out_dir: Path) -> None:
    params = _validate(config)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "top.v").write_text(
        _top(
            top_name=str(params["top_name"]),
            max_blocks=int(params["max_blocks"]),
            value_slices=int(params["value_slices"]),
            fsm_encoding=str(params["fsm_encoding"]),
        ),
        encoding="utf-8",
    )
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    value_slices = int(params["value_slices"])
    manifest = {
        "version": 1,
        "top_name": params["top_name"],
        "semantic_profile": "q8_k8_v8_a32_s32_exp_lut_b20_shared_score_multivalue_iterdiv_v1",
        "max_blocks": params["max_blocks"],
        "max_context_tokens": int(params["max_blocks"]) * 8,
        "value_slices": value_slices,
        "value_dimensions": value_slices * 8,
        "score_reads_per_block": 1,
        "value_reads_per_block": value_slices,
        "divider_impl": params["divider_impl"],
        "fsm_encoding": params["fsm_encoding"],
        "divider_units": 1,
        "divider_cycles_per_command": value_slices * 8 * 60,
        "result_interface": "ready_valid_8d_slice_stream",
        "result_beats_per_command": value_slices,
        "accumulator_clear_cycles": value_slices,
    }
    (out_dir / "attention_two_pass_multivalue_stream_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
