#!/usr/bin/env python3
"""Generate a compact attention tile command dispatcher RTL block."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _as_int(config: dict[str, Any], key: str, default: int) -> int:
    return int(config.get(key, default))


def _validate(cfg: dict[str, Any]) -> dict[str, int | str]:
    ctrl = cfg.get("attention_command_dispatch")
    if not isinstance(ctrl, dict):
        raise SystemExit("config must contain attention_command_dispatch object")
    top_name = str(cfg.get("top_name", "")).strip()
    if not top_name:
        raise SystemExit("config top_name must not be empty")

    clusters = _as_int(ctrl, "clusters", 16)
    queue_depth = _as_int(ctrl, "queue_depth", 32)
    tile_id_bits = _as_int(ctrl, "tile_id_bits", 16)
    wave_id_bits = _as_int(ctrl, "wave_id_bits", 12)
    base_token_bits = _as_int(ctrl, "base_token_bits", 18)
    max_inflight_per_cluster = _as_int(ctrl, "max_inflight_per_cluster", 4)

    if clusters < 1 or clusters > 64:
        raise SystemExit("attention_command_dispatch.clusters must be in [1, 64]")
    if queue_depth < 2 or queue_depth > 128:
        raise SystemExit("attention_command_dispatch.queue_depth must be in [2, 128]")
    if tile_id_bits < 1 or tile_id_bits > 32:
        raise SystemExit("attention_command_dispatch.tile_id_bits must be in [1, 32]")
    if wave_id_bits < 1 or wave_id_bits > 24:
        raise SystemExit("attention_command_dispatch.wave_id_bits must be in [1, 24]")
    if base_token_bits < 1 or base_token_bits > 32:
        raise SystemExit("attention_command_dispatch.base_token_bits must be in [1, 32]")
    if max_inflight_per_cluster < 1 or max_inflight_per_cluster > 16:
        raise SystemExit("attention_command_dispatch.max_inflight_per_cluster must be in [1, 16]")

    return {
        "top_name": top_name,
        "clusters": clusters,
        "queue_depth": queue_depth,
        "tile_id_bits": tile_id_bits,
        "wave_id_bits": wave_id_bits,
        "base_token_bits": base_token_bits,
        "max_inflight_per_cluster": max_inflight_per_cluster,
    }


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _generate(params: dict[str, int | str]) -> str:
    top = str(params["top_name"])
    clusters = int(params["clusters"])
    queue_depth = int(params["queue_depth"])
    tile_id_bits = int(params["tile_id_bits"])
    wave_id_bits = int(params["wave_id_bits"])
    base_token_bits = int(params["base_token_bits"])
    max_inflight = int(params["max_inflight_per_cluster"])

    cluster_bits = _clog2(clusters)
    depth_bits = _clog2(queue_depth)
    count_bits = _clog2(queue_depth + 1)
    inflight_bits = _clog2(max_inflight + 1)
    payload_bits = tile_id_bits + wave_id_bits + base_token_bits

    return f"""// Generated by npu/rtlgen/gen_attention_command_dispatch.py
module {top} (
    input  wire                         clk,
    input  wire                         rst_n,
    input  wire                         command_valid,
    output wire                         command_ready,
    input  wire [{tile_id_bits - 1}:0]  command_tile_id,
    input  wire [{wave_id_bits - 1}:0]  command_wave_id,
    input  wire [{base_token_bits - 1}:0] command_base_token,
    input  wire [{clusters - 1}:0]      cluster_ready,
    input  wire                         cluster_done_valid,
    input  wire [{cluster_bits - 1}:0]  cluster_done_id,
    output reg                          dispatch_valid,
    input  wire                         dispatch_ready,
    output reg  [{cluster_bits - 1}:0]  dispatch_cluster_id,
    output reg  [{tile_id_bits - 1}:0]  dispatch_tile_id,
    output reg  [{wave_id_bits - 1}:0]  dispatch_wave_id,
    output reg  [{base_token_bits - 1}:0] dispatch_base_token,
    output wire                         queue_empty,
    output wire                         queue_full,
    output wire [{count_bits - 1}:0]    queued_count
);
  localparam integer CLUSTERS = {clusters};
  localparam integer QUEUE_DEPTH = {queue_depth};
  localparam integer PAYLOAD_BITS = {payload_bits};
  localparam [{depth_bits - 1}:0] PTR_LAST = {depth_bits}'d{queue_depth - 1};
  localparam [{cluster_bits - 1}:0] CLUSTER_LAST = {cluster_bits}'d{clusters - 1};
  localparam integer TILE_LSB = 0;
  localparam integer WAVE_LSB = {tile_id_bits};
  localparam integer BASE_LSB = {tile_id_bits + wave_id_bits};

  reg [PAYLOAD_BITS-1:0] queue_mem [0:QUEUE_DEPTH-1];
  reg [{depth_bits - 1}:0] head_ptr;
  reg [{depth_bits - 1}:0] tail_ptr;
  reg [{count_bits - 1}:0] count;
  reg [{cluster_bits - 1}:0] rr_ptr;
  reg [{inflight_bits - 1}:0] inflight [0:CLUSTERS-1];

  reg [{cluster_bits - 1}:0] selected_cluster;
  reg                         selected_valid;
  integer i;
  integer idx;

  assign queue_empty = (count == {count_bits}'d0);
  assign queue_full = (count == {count_bits}'d{queue_depth});
  assign queued_count = count;
  assign command_ready = !queue_full;

  wire issue_fire = dispatch_valid && dispatch_ready;
  wire push_fire = command_valid && command_ready;
  wire pop_fire = issue_fire;
  wire [PAYLOAD_BITS-1:0] head_payload = queue_mem[head_ptr];

  always @* begin
    selected_cluster = {{ {cluster_bits} {{1'b0}} }};
    selected_valid = 1'b0;
    for (i = 0; i < CLUSTERS; i = i + 1) begin
      idx = rr_ptr + i[{cluster_bits - 1}:0];
      if (idx >= CLUSTERS) begin
        idx = idx - CLUSTERS;
      end
      if (!selected_valid && cluster_ready[idx] && (inflight[idx] < {inflight_bits}'d{max_inflight})) begin
        selected_cluster = idx[{cluster_bits - 1}:0];
        selected_valid = 1'b1;
      end
    end
  end

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      head_ptr <= {{ {depth_bits} {{1'b0}} }};
      tail_ptr <= {{ {depth_bits} {{1'b0}} }};
      count <= {{ {count_bits} {{1'b0}} }};
      rr_ptr <= {{ {cluster_bits} {{1'b0}} }};
      dispatch_valid <= 1'b0;
      dispatch_cluster_id <= {{ {cluster_bits} {{1'b0}} }};
      dispatch_tile_id <= {{ {tile_id_bits} {{1'b0}} }};
      dispatch_wave_id <= {{ {wave_id_bits} {{1'b0}} }};
      dispatch_base_token <= {{ {base_token_bits} {{1'b0}} }};
      for (i = 0; i < CLUSTERS; i = i + 1) begin
        inflight[i] <= {{ {inflight_bits} {{1'b0}} }};
      end
    end else begin
      if (push_fire) begin
        queue_mem[tail_ptr] <= {{command_base_token, command_wave_id, command_tile_id}};
        if (tail_ptr == PTR_LAST) begin
          tail_ptr <= {{ {depth_bits} {{1'b0}} }};
        end else begin
          tail_ptr <= tail_ptr + 1'b1;
        end
      end

      if (pop_fire) begin
        if (head_ptr == PTR_LAST) begin
          head_ptr <= {{ {depth_bits} {{1'b0}} }};
        end else begin
          head_ptr <= head_ptr + 1'b1;
        end
        if (dispatch_cluster_id == CLUSTER_LAST) begin
          rr_ptr <= {{ {cluster_bits} {{1'b0}} }};
        end else begin
          rr_ptr <= dispatch_cluster_id + 1'b1;
        end
      end

      case ({{push_fire, pop_fire}})
        2'b10: count <= count + 1'b1;
        2'b01: count <= count - 1'b1;
        default: count <= count;
      endcase

      for (i = 0; i < CLUSTERS; i = i + 1) begin
        if (cluster_done_valid && cluster_done_id == i[{cluster_bits - 1}:0] &&
            !(pop_fire && dispatch_cluster_id == i[{cluster_bits - 1}:0]) &&
            inflight[i] != {inflight_bits}'d0) begin
          inflight[i] <= inflight[i] - 1'b1;
        end else if (pop_fire && dispatch_cluster_id == i[{cluster_bits - 1}:0] &&
            !(cluster_done_valid && cluster_done_id == i[{cluster_bits - 1}:0] &&
              inflight[i] != {inflight_bits}'d0)) begin
          inflight[i] <= inflight[i] + 1'b1;
        end
      end

      if (!dispatch_valid || dispatch_ready) begin
        dispatch_valid <= !queue_empty && selected_valid;
        dispatch_cluster_id <= selected_cluster;
        dispatch_tile_id <= head_payload[TILE_LSB +: {tile_id_bits}];
        dispatch_wave_id <= head_payload[WAVE_LSB +: {wave_id_bits}];
        dispatch_base_token <= head_payload[BASE_LSB +: {base_token_bits}];
      end
    end
  end
endmodule
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    config_path = Path(args.config)
    params = _validate(_load_json(config_path))
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    top_name = str(params["top_name"])
    (out_dir / f"{top_name}.v").write_text(_generate(params), encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(_load_json(config_path), indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
