#!/usr/bin/env python3
"""Generate a shared on-chip value-service wrapper for multivalue score clusters."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_decode_score_multivalue_cluster import generate as generate_cluster

JsonDict = dict[str, Any]

_SIM_RTL_PATHS = (
    "npu/sim/rtl/noc_ready_valid_fifo.sv",
    "npu/sim/rtl/noc_ready_valid_router.sv",
    "npu/sim/rtl/banked_value_memory_service.sv",
    "npu/sim/rtl/noc_value_matrix_reassembler.sv",
)


def _load(path: Path) -> JsonDict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise SystemExit(f"config must decode to a JSON object: {path}")
    return payload


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: JsonDict) -> JsonDict:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get("attention_decode_score_multivalue_service")
    if not top_name or not isinstance(body, dict):
        raise SystemExit("config requires top_name and attention_decode_score_multivalue_service")

    cluster_count = int(body.get("cluster_count", 1))
    max_blocks = int(body.get("max_blocks", 16))
    packet_w = int(body.get("packet_w", 128))
    banks = int(body.get("banks", 2))
    req_queue_depth = int(body.get("req_queue_depth", 2))
    resp_queue_depth = int(body.get("resp_queue_depth", 2))
    bank_queue_depth = int(body.get("bank_queue_depth", 2))
    read_latency = int(body.get("read_latency", 1))
    arb_mode = str(body.get("arb_mode", "round_robin")).strip().lower()
    locality_burst_max = int(body.get("locality_burst_max", 2))
    score_scale_lanes_per_cycle = int(body.get("score_scale_lanes_per_cycle", 1))
    fsm_encoding = str(body.get("fsm_encoding", "default")).strip().lower()

    if cluster_count < 1 or cluster_count > 32:
        raise SystemExit("cluster_count must be in [1, 32]")
    if max_blocks < 8 or max_blocks > 16384 or (max_blocks & (max_blocks - 1)):
        raise SystemExit("max_blocks must be a power of two in [8, 16384]")
    if packet_w not in {128, 256}:
        raise SystemExit("packet_w must be 128 or 256")
    if banks < 1 or banks > 64:
        raise SystemExit("banks must be in [1, 64]")
    if req_queue_depth < 1 or resp_queue_depth < 1 or bank_queue_depth < 1:
        raise SystemExit("queue depths must be positive")
    if read_latency < 0 or read_latency > 64:
        raise SystemExit("read_latency must be in [0, 64]")
    if arb_mode not in {"round_robin", "locality_first_bounded"}:
        raise SystemExit("arb_mode must be round_robin or locality_first_bounded")
    if locality_burst_max < 1 or locality_burst_max > 64:
        raise SystemExit("locality_burst_max must be in [1, 64]")
    if score_scale_lanes_per_cycle not in {1, 2, 4, 8}:
        raise SystemExit("score_scale_lanes_per_cycle must be one of 1,2,4,8")
    if fsm_encoding not in {"default", "binary"}:
        raise SystemExit("fsm_encoding must be default or binary")

    return {
        "top_name": top_name,
        "cluster_count": cluster_count,
        "max_blocks": max_blocks,
        "packet_w": packet_w,
        "banks": banks,
        "req_queue_depth": req_queue_depth,
        "resp_queue_depth": resp_queue_depth,
        "bank_queue_depth": bank_queue_depth,
        "read_latency": read_latency,
        "arb_mode": arb_mode,
        "locality_burst_max": locality_burst_max,
        "score_scale_lanes_per_cycle": score_scale_lanes_per_cycle,
        "fsm_encoding": fsm_encoding,
    }


def _wrapper(*, top_name: str, params: JsonDict, cluster_top: str) -> str:
    cluster_count = int(params["cluster_count"])
    packet_w = int(params["packet_w"])
    banks = int(params["banks"])
    req_queue_depth = int(params["req_queue_depth"])
    resp_queue_depth = int(params["resp_queue_depth"])
    bank_queue_depth = int(params["bank_queue_depth"])
    read_latency = int(params["read_latency"])
    locality_burst_max = int(params["locality_burst_max"])
    arb_mode = 0 if params["arb_mode"] == "round_robin" else 1
    source_w = _clog2(cluster_count)
    frag_idx_w = _clog2(512 // packet_w)
    return f"""// Auto-generated by npu/rtlgen/gen_attention_decode_score_multivalue_service.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         preload_valid,
    output wire         preload_ready,
    input  wire [13:0]  preload_addr,
    input  wire [3:0]   preload_value_slice,
    input  wire [511:0] preload_matrix,
    input  wire [{cluster_count - 1}:0] cluster_command_valid,
    output wire [{cluster_count - 1}:0] cluster_command_ready,
    input  wire [{cluster_count * 16 - 1}:0] cluster_command_id,
    input  wire [{cluster_count * 15 - 1}:0] cluster_command_block_count,
    input  wire [{cluster_count * 32 - 1}:0] cluster_command_score_multiplier,
    input  wire [{cluster_count * 6 - 1}:0] cluster_command_score_shift,
    input  wire [{cluster_count - 1}:0] cluster_input_valid,
    output wire [{cluster_count - 1}:0] cluster_input_ready,
    input  wire [{cluster_count - 1}:0] cluster_input_last,
    input  wire [{cluster_count * 8 - 1}:0] cluster_input_a,
    input  wire [{cluster_count * 64 - 1}:0] cluster_input_b,
    output wire [{cluster_count - 1}:0] cluster_result_valid,
    input  wire [{cluster_count - 1}:0] cluster_result_ready,
    output wire [{cluster_count * 16 - 1}:0] cluster_result_command_id,
    output wire [{cluster_count * 32 - 1}:0] cluster_result_global_max,
    output wire [{cluster_count * 33 - 1}:0] cluster_result_exp_sum,
    output wire [{cluster_count * 4 - 1}:0] cluster_result_slice,
    output wire [{cluster_count - 1}:0] cluster_result_last,
    output wire [{cluster_count * 320 - 1}:0] cluster_result_value,
    output wire [{cluster_count * 32 - 1}:0] cluster_accepted_count,
    output wire [{cluster_count * 32 - 1}:0] cluster_completed_count,
    output wire [{cluster_count * 32 - 1}:0] cluster_cycle_count,
    output wire [{cluster_count - 1}:0] cluster_protocol_error,
    output wire [{cluster_count * 8 - 1}:0] transport_req_tag,
    output wire [{cluster_count * source_w - 1}:0] transport_wide_source,
    output wire [{cluster_count * 8 - 1}:0] transport_wide_tag,
    output wire [{cluster_count * 14 - 1}:0] transport_wide_addr,
    output wire [{cluster_count * 4 - 1}:0] transport_wide_value_slice,
    output wire [{cluster_count - 1}:0] transport_wide_valid,
    output wire [{cluster_count - 1}:0] reassembler_protocol_error,
    output wire [31:0]  router_injection_stall_cycles,
    output wire [31:0]  router_arbitration_contention_cycles,
    output wire [31:0]  router_response_block_cycles,
    output wire [31:0]  router_req_current_occupancy,
    output wire [31:0]  router_req_max_occupancy,
    output wire [31:0]  router_resp_current_occupancy,
    output wire [31:0]  router_resp_max_occupancy,
    output wire [31:0]  service_accepted_req_count,
    output wire [31:0]  service_emitted_resp_count,
    output wire [31:0]  service_bank_conflict_count,
    output wire [31:0]  service_response_block_cycles,
    output wire [31:0]  service_req_current_occupancy,
    output wire [31:0]  service_req_max_occupancy,
    output wire [31:0]  service_resp_current_occupancy,
    output wire [31:0]  service_resp_max_occupancy,
    output wire         protocol_error
);
  localparam integer CLUSTERS = {cluster_count};
  localparam integer PACKET_W = {packet_w};
  localparam integer VALUE_W = 512;
  localparam integer SOURCE_W = {source_w};
  localparam integer TAG_W = 8;
  localparam integer ADDR_W = 14;
  localparam integer VALUE_SLICE_W = 4;
  localparam integer FRAG_IDX_W = {frag_idx_w};

  wire [CLUSTERS-1:0] src_req_valid;
  wire [CLUSTERS-1:0] src_req_ready;
  wire [CLUSTERS*(TAG_W)-1:0] src_req_tag;
  wire [CLUSTERS*ADDR_W-1:0] src_req_addr;
  wire [CLUSTERS*VALUE_SLICE_W-1:0] src_req_value_slice;

  wire [CLUSTERS-1:0] src_resp_valid;
  wire [CLUSTERS-1:0] src_resp_ready;
  wire [CLUSTERS*SOURCE_W-1:0] src_resp_source;
  wire [CLUSTERS*TAG_W-1:0] src_resp_tag;
  wire [CLUSTERS*ADDR_W-1:0] src_resp_addr;
  wire [CLUSTERS*VALUE_SLICE_W-1:0] src_resp_value_slice;
  wire [CLUSTERS*FRAG_IDX_W-1:0] src_resp_fragment_idx;
  wire [CLUSTERS-1:0] src_resp_last;
  wire [CLUSTERS*PACKET_W-1:0] src_resp_data;

  wire req_valid;
  wire req_ready;
  wire [SOURCE_W-1:0] req_source;
  wire [TAG_W-1:0] req_tag;
  wire [ADDR_W-1:0] req_addr;
  wire [VALUE_SLICE_W-1:0] req_value_slice;

  wire resp_valid;
  wire resp_ready;
  wire [SOURCE_W-1:0] resp_source;
  wire [TAG_W-1:0] resp_tag;
  wire [ADDR_W-1:0] resp_addr;
  wire [VALUE_SLICE_W-1:0] resp_value_slice;
  wire [FRAG_IDX_W-1:0] resp_fragment_idx;
  wire resp_last;
  wire [PACKET_W-1:0] resp_data;

  wire [CLUSTERS-1:0] cluster_value_resp_valid;
  wire [CLUSTERS-1:0] cluster_value_resp_ready;
  wire [CLUSTERS*ADDR_W-1:0] cluster_value_resp_addr;
  wire [CLUSTERS*VALUE_SLICE_W-1:0] cluster_value_resp_slice;
  wire [CLUSTERS*VALUE_W-1:0] cluster_value_resp_matrix;
  reg  [TAG_W-1:0] request_tag_q [0:CLUSTERS-1];

  genvar gi;
  generate
    for (gi = 0; gi < CLUSTERS; gi = gi + 1) begin : gen_cluster
      assign src_req_tag[(gi * TAG_W) +: TAG_W] = request_tag_q[gi];
      assign transport_req_tag[(gi * TAG_W) +: TAG_W] = request_tag_q[gi];
      assign transport_wide_valid[gi] = cluster_value_resp_valid[gi];

      {cluster_top} u_cluster (
          .clk(clk),
          .rst_n(rst_n),
          .command_valid(cluster_command_valid[gi]),
          .command_ready(cluster_command_ready[gi]),
          .command_id(cluster_command_id[(gi * 16) +: 16]),
          .command_block_count(cluster_command_block_count[(gi * 15) +: 15]),
          .command_score_multiplier(cluster_command_score_multiplier[(gi * 32) +: 32]),
          .command_score_shift(cluster_command_score_shift[(gi * 6) +: 6]),
          .input_valid(cluster_input_valid[gi]),
          .input_ready(cluster_input_ready[gi]),
          .input_last(cluster_input_last[gi]),
          .input_a(cluster_input_a[(gi * 8) +: 8]),
          .input_b(cluster_input_b[(gi * 64) +: 64]),
          .value_read_req_valid(src_req_valid[gi]),
          .value_read_req_ready(src_req_ready[gi]),
          .value_read_req_address(src_req_addr[(gi * ADDR_W) +: ADDR_W]),
          .value_read_req_slice(src_req_value_slice[(gi * VALUE_SLICE_W) +: VALUE_SLICE_W]),
          .value_response_valid(cluster_value_resp_valid[gi]),
          .value_response_ready(cluster_value_resp_ready[gi]),
          .value_response_address(cluster_value_resp_addr[(gi * ADDR_W) +: ADDR_W]),
          .value_response_slice(cluster_value_resp_slice[(gi * VALUE_SLICE_W) +: VALUE_SLICE_W]),
          .value_response_matrix(cluster_value_resp_matrix[(gi * VALUE_W) +: VALUE_W]),
          .result_valid(cluster_result_valid[gi]),
          .result_ready(cluster_result_ready[gi]),
          .result_command_id(cluster_result_command_id[(gi * 16) +: 16]),
          .result_global_max(cluster_result_global_max[(gi * 32) +: 32]),
          .result_exp_sum(cluster_result_exp_sum[(gi * 33) +: 33]),
          .result_slice(cluster_result_slice[(gi * 4) +: 4]),
          .result_last(cluster_result_last[gi]),
          .result_value(cluster_result_value[(gi * 320) +: 320]),
          .accepted_count(cluster_accepted_count[(gi * 32) +: 32]),
          .completed_count(cluster_completed_count[(gi * 32) +: 32]),
          .cycle_count(cluster_cycle_count[(gi * 32) +: 32]),
          .protocol_error(cluster_protocol_error[gi])
      );

      noc_value_matrix_reassembler #(
        .PACKET_W(PACKET_W),
        .VALUE_W(VALUE_W),
        .SOURCE_W(SOURCE_W),
        .TAG_W(TAG_W),
        .ADDR_W(ADDR_W),
        .VALUE_SLICE_W(VALUE_SLICE_W)
      ) u_reassembler (
        .clk(clk),
        .rst_n(rst_n),
        .seg_valid(src_resp_valid[gi]),
        .seg_ready(src_resp_ready[gi]),
        .seg_source(src_resp_source[(gi * SOURCE_W) +: SOURCE_W]),
        .seg_tag(src_resp_tag[(gi * TAG_W) +: TAG_W]),
        .seg_addr(src_resp_addr[(gi * ADDR_W) +: ADDR_W]),
        .seg_value_slice(src_resp_value_slice[(gi * VALUE_SLICE_W) +: VALUE_SLICE_W]),
        .seg_fragment_idx(src_resp_fragment_idx[(gi * FRAG_IDX_W) +: FRAG_IDX_W]),
        .seg_last(src_resp_last[gi]),
        .seg_data(src_resp_data[(gi * PACKET_W) +: PACKET_W]),
        .wide_valid(cluster_value_resp_valid[gi]),
        .wide_ready(cluster_value_resp_ready[gi]),
        .wide_source(transport_wide_source[(gi * SOURCE_W) +: SOURCE_W]),
        .wide_tag(transport_wide_tag[(gi * TAG_W) +: TAG_W]),
        .wide_addr(transport_wide_addr[(gi * ADDR_W) +: ADDR_W]),
        .wide_value_slice(transport_wide_value_slice[(gi * VALUE_SLICE_W) +: VALUE_SLICE_W]),
        .wide_matrix(cluster_value_resp_matrix[(gi * VALUE_W) +: VALUE_W]),
        .protocol_error(reassembler_protocol_error[gi])
      );
    end
  endgenerate

  noc_ready_valid_router #(
    .PACKET_W(PACKET_W),
    .VALUE_W(VALUE_W),
    .SOURCES(CLUSTERS),
    .SOURCE_W(SOURCE_W),
    .TAG_W(TAG_W),
    .ADDR_W(ADDR_W),
    .VALUE_SLICE_W(VALUE_SLICE_W),
    .BANKS({banks}),
    .REQ_QUEUE_DEPTH({req_queue_depth}),
    .RESP_QUEUE_DEPTH({resp_queue_depth}),
    .ARB_MODE({arb_mode}),
    .LOCALITY_BURST_MAX({locality_burst_max})
  ) u_router (
    .clk(clk),
    .rst_n(rst_n),
    .src_req_valid(src_req_valid),
    .src_req_ready(src_req_ready),
    .src_req_tag(src_req_tag),
    .src_req_addr(src_req_addr),
    .src_req_value_slice(src_req_value_slice),
    .src_resp_valid(src_resp_valid),
    .src_resp_ready(src_resp_ready),
    .src_resp_source(src_resp_source),
    .src_resp_tag(src_resp_tag),
    .src_resp_addr(src_resp_addr),
    .src_resp_value_slice(src_resp_value_slice),
    .src_resp_fragment_idx(src_resp_fragment_idx),
    .src_resp_last(src_resp_last),
    .src_resp_data(src_resp_data),
    .req_valid(req_valid),
    .req_ready(req_ready),
    .req_source(req_source),
    .req_tag(req_tag),
    .req_addr(req_addr),
    .req_value_slice(req_value_slice),
    .resp_valid(resp_valid),
    .resp_ready(resp_ready),
    .resp_source(resp_source),
    .resp_tag(resp_tag),
    .resp_addr(resp_addr),
    .resp_value_slice(resp_value_slice),
    .resp_fragment_idx(resp_fragment_idx),
    .resp_last(resp_last),
    .resp_data(resp_data),
    .injection_stall_cycles(router_injection_stall_cycles),
    .arbitration_contention_cycles(router_arbitration_contention_cycles),
    .response_block_cycles(router_response_block_cycles),
    .req_current_occupancy(router_req_current_occupancy),
    .req_max_occupancy(router_req_max_occupancy),
    .resp_current_occupancy(router_resp_current_occupancy),
    .resp_max_occupancy(router_resp_max_occupancy)
  );

  banked_value_memory_service #(
    .PACKET_W(PACKET_W),
    .VALUE_W(VALUE_W),
    .SOURCE_W(SOURCE_W),
    .TAG_W(TAG_W),
    .ADDR_W(ADDR_W),
    .VALUE_SLICE_W(VALUE_SLICE_W),
    .STORE_DEPTH({int(params["max_blocks"])}),
    .BANKS({banks}),
    .BANK_QUEUE_DEPTH({bank_queue_depth}),
    .READ_LATENCY({read_latency}),
    .INIT_FROM_GENERATOR(0)
  ) u_service (
    .clk(clk),
    .rst_n(rst_n),
    .preload_valid(preload_valid),
    .preload_ready(preload_ready),
    .preload_addr(preload_addr),
    .preload_value_slice(preload_value_slice),
    .preload_matrix(preload_matrix),
    .req_valid(req_valid),
    .req_ready(req_ready),
    .req_source(req_source),
    .req_tag(req_tag),
    .req_addr(req_addr),
    .req_value_slice(req_value_slice),
    .resp_valid(resp_valid),
    .resp_ready(resp_ready),
    .resp_source(resp_source),
    .resp_tag(resp_tag),
    .resp_addr(resp_addr),
    .resp_value_slice(resp_value_slice),
    .resp_fragment_idx(resp_fragment_idx),
    .resp_last(resp_last),
    .resp_data(resp_data),
    .accepted_req_count(service_accepted_req_count),
    .emitted_resp_count(service_emitted_resp_count),
    .bank_conflict_count(service_bank_conflict_count),
    .response_block_cycles(service_response_block_cycles),
    .req_current_occupancy(service_req_current_occupancy),
    .req_max_occupancy(service_req_max_occupancy),
    .resp_current_occupancy(service_resp_current_occupancy),
    .resp_max_occupancy(service_resp_max_occupancy)
  );

  assign protocol_error = (|cluster_protocol_error) || (|reassembler_protocol_error);

  integer tag_i;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      for (tag_i = 0; tag_i < CLUSTERS; tag_i = tag_i + 1) begin
        request_tag_q[tag_i] <= {{TAG_W{{1'b0}}}};
      end
    end else begin
      for (tag_i = 0; tag_i < CLUSTERS; tag_i = tag_i + 1) begin
        if (src_req_valid[tag_i] && src_req_ready[tag_i]) begin
          request_tag_q[tag_i] <= request_tag_q[tag_i] + {{{{(TAG_W-1){{1'b0}}}}, 1'b1}};
        end
      end
    end
  end
endmodule
"""


def generate(config: JsonDict, out_dir: Path) -> None:
    params = _validate(config)
    top_name = str(params["top_name"])
    cluster_top = f"{top_name}__cluster"
    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="multivalue-service-gen-") as tmp_text:
        tmp = Path(tmp_text)
        cluster_dir = tmp / "cluster"
        generate_cluster(
            {
                "top_name": cluster_top,
                "attention_decode_score_multivalue_cluster": {
                    "max_blocks": params["max_blocks"],
                    "array_n": 8,
                    "value_slices": 16,
                    "divider_impl": "iterative_restoring",
                    "score_scale_lanes_per_cycle": params["score_scale_lanes_per_cycle"],
                    "fsm_encoding": params["fsm_encoding"],
                },
            },
            cluster_dir,
        )
        cluster_text = (cluster_dir / "top.v").read_text(encoding="utf-8")
        cluster_manifest = json.loads(
            (cluster_dir / "attention_decode_score_multivalue_cluster_manifest.json").read_text(encoding="utf-8")
        )
        sim_rtl = [(REPO_ROOT / rel).read_text(encoding="utf-8") for rel in _SIM_RTL_PATHS]
        wrapper = _wrapper(top_name=top_name, params=params, cluster_top=cluster_top)

    top_text = "\n\n".join([cluster_text, *sim_rtl, wrapper]) + "\n"
    (out_dir / "top.v").write_text(top_text, encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    dependency_sources = [
        {
            "path": "npu/rtlgen/gen_attention_decode_score_multivalue_service.py",
            "sha256": _sha256_file(Path(__file__)),
        },
        {
            "path": "npu/rtlgen/gen_attention_decode_score_multivalue_cluster.py",
            "sha256": _sha256_file(REPO_ROOT / "npu/rtlgen/gen_attention_decode_score_multivalue_cluster.py"),
        },
        *[
            {
                "path": rel,
                "sha256": _sha256_file(REPO_ROOT / rel),
            }
            for rel in _SIM_RTL_PATHS
        ],
    ]
    manifest = {
        "version": 1,
        "generator": "npu/rtlgen/gen_attention_decode_score_multivalue_service.py",
        "top_name": top_name,
        "semantic_profile": "decode_m1x8_shared_score_16x8d_value_iterdiv_onchip_service_v1",
        "cluster_count": params["cluster_count"],
        "max_blocks": params["max_blocks"],
        "packet_w": params["packet_w"],
        "banks": params["banks"],
        "req_queue_depth": params["req_queue_depth"],
        "resp_queue_depth": params["resp_queue_depth"],
        "bank_queue_depth": params["bank_queue_depth"],
        "read_latency": params["read_latency"],
        "arb_mode": params["arb_mode"],
        "locality_burst_max": params["locality_burst_max"],
        "value_dimensions": 128,
        "value_slices": 16,
        "score_scale_lanes_per_cycle": params["score_scale_lanes_per_cycle"],
        "fsm_encoding": params["fsm_encoding"],
        "dependency_sources": dependency_sources,
        "generated_top_sha256": _sha256_text(top_text),
        "submodule_manifests": {
            "multivalue_cluster": cluster_manifest,
        },
    }
    (out_dir / "attention_decode_score_multivalue_service_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
