#!/usr/bin/env python3
"""Generate a decode-score cluster sharing one score pass across value slices."""

from __future__ import annotations

import argparse
import json
import math
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu.rtlgen.gen_attention_score_bank_proxy import generate as generate_score_bank
from npu.rtlgen.gen_attention_two_pass_multivalue_stream import generate as generate_multivalue
from npu.rtlgen.gen_dense_gemm_tile_stream import generate as generate_score_tile


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _clog2(value: int) -> int:
    return max(1, math.ceil(math.log2(max(2, value))))


def _validate(config: dict[str, Any]) -> dict[str, int | str]:
    top_name = str(config.get("top_name") or "").strip()
    body = config.get("attention_decode_score_multivalue_cluster")
    if not top_name or not isinstance(body, dict):
        raise SystemExit("config requires top_name and attention_decode_score_multivalue_cluster")
    max_blocks = int(body.get("max_blocks", 16384))
    array_n = int(body.get("array_n", 8))
    value_slices = int(body.get("value_slices", 16))
    scale_lanes = int(body.get("score_scale_lanes_per_cycle", 1))
    divider_impl = str(body.get("divider_impl", "iterative_restoring"))
    if max_blocks < 8 or max_blocks > 16384 or max_blocks & (max_blocks - 1):
        raise SystemExit("max_blocks must be a power of two in [8, 16384]")
    if array_n != 8 or value_slices != 16:
        raise SystemExit("array_n must be 8 and value_slices must be 16")
    if scale_lanes not in {1, 2, 4, 8}:
        raise SystemExit("score_scale_lanes_per_cycle must be one of 1,2,4,8")
    if divider_impl != "iterative_restoring":
        raise SystemExit("divider_impl must be iterative_restoring")
    body.update(
        {
            "max_blocks": max_blocks,
            "array_n": array_n,
            "value_slices": value_slices,
            "score_scale_lanes_per_cycle": scale_lanes,
            "divider_impl": divider_impl,
        }
    )
    return {
        "top_name": top_name,
        "max_blocks": max_blocks,
        "array_n": array_n,
        "value_slices": value_slices,
        "score_scale_lanes_per_cycle": scale_lanes,
        "divider_impl": divider_impl,
    }


def _widen(expr: str, in_bits: int, out_bits: int) -> str:
    if in_bits >= out_bits:
        return expr
    return "{" + f"{out_bits - in_bits}'d0, {expr}" + "}"


def _wrapper(*, top_name: str, params: dict[str, int | str], tile_top: str, bank_top: str, reduce_top: str) -> str:
    max_blocks = int(params["max_blocks"])
    count_bits = _clog2(max_blocks + 1)
    addr_bits = _clog2(max_blocks)
    scale_lanes = int(params["score_scale_lanes_per_cycle"])
    command_count = "command_block_count" if count_bits == 15 else f"command_block_count[{count_bits - 1}:0]"
    read_addr = _widen("score_read_req_addr", addr_bits, 14)
    write_addr = _widen("score_write_addr", addr_bits, 14)
    scale_body = "\n".join(
        f"""        lane_index = scale_lane_index_q + {offset};
        if (lane_index < 8) begin
          scaled_score_row_q[(lane_index * 32) +: 32] <= requantize_lane(
              $signed(raw_score_row_q[(lane_index * 32) +: 32]), active_multiplier_q, active_shift_q);
        end"""
        for offset in range(scale_lanes)
    )
    return f"""// Auto-generated by npu/rtlgen/gen_attention_decode_score_multivalue_cluster.py
module {top_name} (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         command_valid,
    output wire         command_ready,
    input  wire [15:0]  command_id,
    input  wire [14:0]  command_block_count,
    input  wire [31:0]  command_score_multiplier,
    input  wire [5:0]   command_score_shift,
    input  wire         input_valid,
    output wire         input_ready,
    input  wire         input_last,
    input  wire signed [7:0] input_a,
    input  wire signed [63:0] input_b,
    output wire         value_read_req_valid,
    input  wire         value_read_req_ready,
    output wire [13:0]  value_read_req_address,
    output wire [3:0]   value_read_req_slice,
    input  wire         value_response_valid,
    output wire         value_response_ready,
    input  wire [13:0]  value_response_address,
    input  wire [3:0]   value_response_slice,
    input  wire [511:0] value_response_matrix,
    output wire         result_valid,
    input  wire         result_ready,
    output wire [15:0]  result_command_id,
    output wire signed [31:0] result_global_max,
    output wire [32:0]  result_exp_sum,
    output wire [3:0]   result_slice,
    output wire         result_last,
    output wire [319:0] result_value,
    output wire [31:0]  accepted_count,
    output wire [31:0]  completed_count,
    output wire [31:0]  cycle_count,
    output wire         protocol_error
);
  localparam integer MAX_BLOCKS = {max_blocks};
  localparam integer COUNT_W = {count_bits};
  localparam integer ADDR_W = {addr_bits};
  localparam integer SCORE_SCALE_LANES_PER_CYCLE = {scale_lanes};
  localparam [2:0] IDLE = 3'd0, TILE_CMD = 3'd1, TILE_INPUT = 3'd2,
      TILE_RESULT = 3'd3, SCALE = 3'd4, FILL = 3'd5, WAIT_RESULT = 3'd6;

  reg [2:0] state_q;
  reg [COUNT_W-1:0] block_index_q;
  reg [COUNT_W-1:0] active_block_count_q;
  reg [31:0] active_multiplier_q;
  reg [5:0] active_shift_q;
  reg [255:0] raw_score_row_q;
  reg [255:0] scaled_score_row_q;
  reg [3:0] scale_lane_index_q;
  reg outstanding_score_read_q;
  reg [13:0] outstanding_score_addr_q;
  reg score_response_valid_q;
  reg [255:0] score_response_data_q;
  reg protocol_error_q;

  wire tile_command_valid, tile_command_ready;
  wire tile_input_valid, tile_input_ready;
  wire tile_result_valid, tile_result_ready;
  wire signed [255:0] tile_result_score_row;
  wire reduce_command_ready;
  wire reduce_fill_ready;
  wire score_write_valid, score_write_ready;
  wire [ADDR_W-1:0] score_write_addr;
  wire [255:0] score_write_data;
  wire score_read_req_valid, score_read_req_ready;
  wire [ADDR_W-1:0] score_read_req_addr;
  wire [ADDR_W-1:0] value_read_req_addr_narrow;
  wire score_replay_ready;
  wire reduce_protocol_error;
  wire bank_req_valid, bank_req_ready, bank_req_write;
  wire [13:0] bank_req_addr;
  wire [255:0] bank_req_wdata, bank_rsp_rdata;
  wire bank_rsp_valid;
  wire command_count_valid = command_block_count != 0 && command_block_count <= MAX_BLOCKS;
  wire read_slot_open = !outstanding_score_read_q && !score_response_valid_q;
  wire score_read_fire = score_read_req_valid && score_read_req_ready;
  integer lane_index;

  assign command_ready = state_q == IDLE && reduce_command_ready && command_count_valid;
  assign input_ready = state_q == TILE_INPUT && tile_input_ready;
  assign tile_command_valid = state_q == TILE_CMD;
  assign tile_input_valid = state_q == TILE_INPUT && input_valid;
  assign tile_result_ready = state_q == TILE_RESULT;
  assign score_write_ready = bank_req_ready;
  assign score_read_req_ready = read_slot_open && !score_write_valid && bank_req_ready;
  assign bank_req_valid = score_write_valid || (score_read_req_valid && read_slot_open);
  assign bank_req_write = score_write_valid;
  assign bank_req_addr = score_write_valid ? {write_addr} : {read_addr};
  assign bank_req_wdata = score_write_valid ? score_write_data : 256'd0;
  assign protocol_error = protocol_error_q || reduce_protocol_error;
  assign value_read_req_address = {_widen("value_read_req_addr_narrow", addr_bits, 14)};

  function automatic signed [31:0] requantize_lane;
    input signed [31:0] raw_value;
    input [31:0] multiplier;
    input [5:0] shift;
    reg signed [64:0] product;
    reg [64:0] magnitude;
    begin
      product = raw_value * $signed({{1'b0, multiplier}});
      magnitude = product < 0 ? -product : product;
      if (shift != 0) magnitude = (magnitude + (65'd1 << (shift - 1'b1))) >> shift;
      if (product < 0) begin
        if (magnitude >= (65'd1 << 31)) requantize_lane = -32'sh8000_0000;
        else requantize_lane = -$signed(magnitude[31:0]);
      end else begin
        if (magnitude > 65'h7fff_ffff) requantize_lane = 32'sh7fff_ffff;
        else requantize_lane = $signed(magnitude[31:0]);
      end
    end
  endfunction

  {tile_top} score_tile (
      .clk(clk), .rst_n(rst_n), .command_valid(tile_command_valid), .command_ready(tile_command_ready),
      .input_valid(tile_input_valid), .input_ready(tile_input_ready),
      .input_last(input_last), .input_a(input_a), .input_b(input_b),
      .result_valid(tile_result_valid), .result_ready(tile_result_ready),
      .result_score_row(tile_result_score_row)
  );

  {bank_top} score_bank (
      .clk(clk), .rst_n(rst_n), .req_valid(bank_req_valid), .req_ready(bank_req_ready),
      .req_write(bank_req_write), .req_addr(bank_req_addr), .req_wdata(bank_req_wdata),
      .req_wmask(bank_req_write ? {{256{{1'b1}}}} : 256'd0),
      .rsp_valid(bank_rsp_valid), .rsp_rdata(bank_rsp_rdata)
  );

  {reduce_top} reducer (
      .clk(clk), .rst_n(rst_n),
      .command_valid(state_q == IDLE && command_valid && command_count_valid),
      .command_ready(reduce_command_ready), .command_id(command_id),
      .command_block_count({command_count}),
      .fill_valid(state_q == FILL), .fill_ready(reduce_fill_ready), .fill_score_row(scaled_score_row_q),
      .score_write_valid(score_write_valid), .score_write_ready(score_write_ready),
      .score_write_addr(score_write_addr), .score_write_data(score_write_data),
      .score_read_req_valid(score_read_req_valid), .score_read_req_ready(score_read_req_ready),
      .score_read_req_addr(score_read_req_addr), .score_replay_valid(score_response_valid_q),
      .score_replay_ready(score_replay_ready), .score_replay_row(score_response_data_q),
      .value_read_req_valid(value_read_req_valid), .value_read_req_ready(value_read_req_ready),
      .value_read_req_address(value_read_req_addr_narrow),
      .value_read_req_slice(value_read_req_slice), .value_response_valid(value_response_valid),
      .value_response_ready(value_response_ready),
      .value_response_address(value_response_address[ADDR_W-1:0]),
      .value_response_slice(value_response_slice), .value_response_matrix(value_response_matrix),
      .result_valid(result_valid), .result_ready(result_ready), .result_command_id(result_command_id),
      .result_global_max(result_global_max), .result_exp_sum(result_exp_sum),
      .result_slice(result_slice), .result_last(result_last), .result_value(result_value),
      .accepted_count(accepted_count), .completed_count(completed_count), .cycle_count(cycle_count),
      .protocol_error(reduce_protocol_error)
  );

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state_q <= IDLE;
      block_index_q <= 0;
      active_block_count_q <= 0;
      active_multiplier_q <= 0;
      active_shift_q <= 0;
      raw_score_row_q <= 0;
      scaled_score_row_q <= 0;
      scale_lane_index_q <= 0;
      outstanding_score_read_q <= 0;
      outstanding_score_addr_q <= 0;
      score_response_valid_q <= 0;
      score_response_data_q <= 0;
      protocol_error_q <= 0;
    end else begin
      if (score_response_valid_q && score_replay_ready) score_response_valid_q <= 0;
      if (score_read_fire) begin
        outstanding_score_read_q <= 1;
        outstanding_score_addr_q <= {read_addr};
      end
      if (bank_rsp_valid) begin
        if (!outstanding_score_read_q || score_response_valid_q) protocol_error_q <= 1;
        else begin
          outstanding_score_read_q <= 0;
          score_response_valid_q <= 1;
          score_response_data_q <= bank_rsp_rdata;
        end
      end

      case (state_q)
        IDLE: if (command_valid && command_ready) begin
          block_index_q <= 0;
          active_block_count_q <= {command_count};
          active_multiplier_q <= command_score_multiplier;
          active_shift_q <= command_score_shift;
          state_q <= TILE_CMD;
        end
        TILE_CMD: if (tile_command_ready) state_q <= TILE_INPUT;
        TILE_INPUT: if (tile_input_valid && tile_input_ready && input_last) state_q <= TILE_RESULT;
        TILE_RESULT: if (tile_result_valid && tile_result_ready) begin
          raw_score_row_q <= tile_result_score_row;
          scaled_score_row_q <= 0;
          scale_lane_index_q <= 0;
          state_q <= SCALE;
        end
        SCALE: begin
{scale_body}
          if (scale_lane_index_q + SCORE_SCALE_LANES_PER_CYCLE >= 8) state_q <= FILL;
          else scale_lane_index_q <= scale_lane_index_q + SCORE_SCALE_LANES_PER_CYCLE;
        end
        FILL: if (reduce_fill_ready) begin
          if (block_index_q + 1'b1 == active_block_count_q) state_q <= WAIT_RESULT;
          else begin block_index_q <= block_index_q + 1'b1; state_q <= TILE_CMD; end
        end
        WAIT_RESULT: if (result_valid && result_ready && result_last) state_q <= IDLE;
        default: state_q <= IDLE;
      endcase
    end
  end
endmodule
"""


def generate(config: dict[str, Any], out_dir: Path) -> None:
    params = _validate(config)
    top_name = str(params["top_name"])
    tile_top = f"{top_name}__score_tile"
    bank_top = f"{top_name}__score_bank"
    reduce_top = f"{top_name}__multivalue"
    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp_text:
        tmp = Path(tmp_text)
        tile_dir, bank_dir, reduce_dir = tmp / "tile", tmp / "bank", tmp / "reduce"
        generate_score_tile(
            {
                "top_name": tile_top,
                "dense_gemm_tile_stream": {
                    "array_m": 1,
                    "array_n": 8,
                    "precision": "int8",
                    "accum_bits": 32,
                    "result_mode": "packed_score_row",
                },
            },
            tile_dir,
        )
        generate_score_bank({"top_name": bank_top, "attention_score_bank_proxy": {}}, bank_dir)
        generate_multivalue(
            {
                "top_name": reduce_top,
                "attention_two_pass_multivalue_stream": {
                    "max_blocks": int(params["max_blocks"]),
                    "value_slices": int(params["value_slices"]),
                    "divider_impl": "iterative_restoring",
                },
            },
            reduce_dir,
        )
        rtl = [
            (tile_dir / "top.v").read_text(encoding="utf-8"),
            (bank_dir / "top.v").read_text(encoding="utf-8"),
            (reduce_dir / "top.v").read_text(encoding="utf-8"),
            _wrapper(top_name=top_name, params=params, tile_top=tile_top, bank_top=bank_top, reduce_top=reduce_top),
        ]
        tile_manifest = json.loads((tile_dir / "dense_gemm_tile_stream_manifest.json").read_text())
        bank_manifest = json.loads((bank_dir / "attention_score_bank_proxy_manifest.json").read_text())
        reduce_manifest = json.loads(
            (reduce_dir / "attention_two_pass_multivalue_stream_manifest.json").read_text()
        )
    (out_dir / "top.v").write_text("\n\n".join(rtl) + "\n", encoding="utf-8")
    (out_dir / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    manifest = {
        "version": 1,
        "generator": "npu/rtlgen/gen_attention_decode_score_multivalue_cluster.py",
        "top_name": top_name,
        "semantic_profile": "decode_m1x8_shared_score_16x8d_value_iterdiv_v1",
        "max_blocks": params["max_blocks"],
        "score_tile_array_n": 8,
        "score_scale_lanes_per_cycle": params["score_scale_lanes_per_cycle"],
        "value_slices": params["value_slices"],
        "value_dimensions": int(params["value_slices"]) * 8,
        "score_passes_per_command": 1,
        "score_writes_per_block": 1,
        "score_reads_per_block": 1,
        "value_reads_per_block": params["value_slices"],
        "result_beats_per_command": params["value_slices"],
        "result_value_bits_per_beat": 320,
        "score_bank_macro_count": bank_manifest["macro_count"],
        "score_bank_proxy_semantics": bank_manifest["proxy_semantics"],
        "divider_cycles_per_command": reduce_manifest["divider_cycles_per_command"],
        "submodule_manifests": {
            "score_tile": tile_manifest,
            "score_bank": bank_manifest,
            "multivalue_reducer": reduce_manifest,
        },
    }
    (out_dir / "attention_decode_score_multivalue_cluster_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    generate(_load(args.config), args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
