/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "yosys_mult4s_lowpowerbooth_yosys.v:1.1-8.10" *)
module yosys_mult4s_lowpowerbooth(multiplicand, multiplier, product);
  wire _000_;
  wire _001_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [0:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [0:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [0:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [0:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [0:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [0:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [0:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [0:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [0:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [0:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [0:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [0:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [0:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [0:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [0:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [0:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [0:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [0:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [0:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [0:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [0:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [0:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [0:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [0:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [0:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [0:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [0:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [0:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [0:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [0:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [0:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [0:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [0:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [0:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [0:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [0:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* src = "yosys_mult4s_lowpowerbooth_yosys.v:2.22-2.34" *)
  input [3:0] multiplicand;
  wire [3:0] multiplicand;
  (* src = "yosys_mult4s_lowpowerbooth_yosys.v:3.22-3.32" *)
  input [3:0] multiplier;
  wire [3:0] multiplier;
  (* src = "yosys_mult4s_lowpowerbooth_yosys.v:4.23-4.30" *)
  output [7:0] product;
  wire [7:0] product;
  assign product[2] = _006_ ^ _053_;
  assign product[3] = _013_ ^ _043_;
  assign product[4] = _020_ ^ _044_;
  assign product[5] = _026_ ^ _045_;
  assign product[6] = _033_ ^ _046_;
  assign product[7] = _037_ ^ _047_;
  assign _001_ = ~multiplier[3];
  assign _043_ = _006_ & _053_;
  assign _044_ = _013_ & _043_;
  assign _045_ = _020_ & _044_;
  assign _046_ = _026_ & _045_;
  assign _047_ = _033_ & _046_;
  assign _030_ = ~_017_;
  assign _031_ = ~_054_;
  assign _039_ = ~multiplier[2];
  assign _040_ = ~multiplier[1];
  assign _071_ = ~(1'h0 | _048_);
  assign _072_ = ~(_050_ | _052_);
  assign _050_ = _001_ & _049_;
  assign _049_ = multiplier[2] & multiplier[1];
  assign _048_ = multiplier[1] & _038_;
  assign _052_ = multiplier[3] & _051_;
  assign _051_ = _039_ & _040_;
  assign _077_ = ~(multiplier[1] ^ multiplier[2]);
  assign _053_ = _064_ & multiplier[3];
  assign _064_ = _040_ | _039_;
  assign _078_ = ~(multiplicand[2] ^ multiplier[1]);
  assign _079_ = ~(multiplicand[3] ^ multiplier[1]);
  assign _073_ = ~(multiplicand[0] ^ multiplier[3]);
  assign _074_ = ~(multiplicand[1] ^ multiplier[3]);
  assign _075_ = ~(multiplicand[2] ^ multiplier[3]);
  assign _076_ = ~(multiplicand[3] ^ multiplier[3]);
  assign _002_ = ~(_065_ & _066_);
  assign _010_ = ~(_067_ & _068_);
  assign _017_ = ~(_069_ & _068_);
  assign _003_ = ~(_055_ & _056_);
  assign _011_ = ~(_057_ & _058_);
  assign _018_ = ~(_059_ & _060_);
  assign _024_ = ~(_061_ & _062_);
  assign _054_ = ~(_063_ & _062_);
  assign _065_ = _000_ | _071_;
  assign _067_ = _078_ | _071_;
  assign _069_ = _079_ | _071_;
  assign _055_ = _001_ | _072_;
  assign _057_ = _073_ | _072_;
  assign _059_ = _074_ | _072_;
  assign _061_ = _075_ | _072_;
  assign _063_ = _076_ | _072_;
  assign _066_ = _078_ | _038_;
  assign _068_ = _079_ | _038_;
  assign _056_ = _073_ | _077_;
  assign _058_ = _074_ | _077_;
  assign _060_ = _075_ | _077_;
  assign _062_ = _076_ | _077_;
  assign _000_ = ~(multiplicand[1] ^ multiplier[1]);
  assign product[0] = multiplicand[0] & multiplier[0];
  assign _041_ = multiplicand[1] & multiplier[0];
  assign _042_ = multiplicand[0] & multiplier[1];
  assign product[1] = _041_ ^ _042_;
  assign _070_ = ~(product[1] | product[0]);
  assign _004_ = _070_ & multiplier[1];
  assign _037_ = ~_032_;
  assign _038_ = ~multiplier[0];
  assign _005_ = _008_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _009_;
  assign _006_ = _007_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _004_;
  assign _009_ = _004_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _007_;
  assign _008_ = _002_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _003_;
  assign _007_ = _002_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _003_;
  assign _012_ = _015_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _016_;
  assign _013_ = _014_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _005_;
  assign _016_ = _005_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _014_;
  assign _015_ = _010_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _011_;
  assign _014_ = _010_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _011_;
  assign _019_ = _022_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _023_;
  assign _020_ = _021_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _012_;
  assign _023_ = _012_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _021_;
  assign _022_ = _017_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _018_;
  assign _021_ = _017_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _018_;
  assign _025_ = _028_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _029_;
  assign _026_ = _027_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _019_;
  assign _029_ = _019_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _027_;
  assign _028_ = _017_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _024_;
  assign _027_ = _017_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _024_;
  assign _032_ = _035_ |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _036_;
  assign _033_ = _034_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _025_;
  assign _036_ = _025_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _034_;
  assign _035_ = _030_ &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _031_;
  assign _034_ = _030_ ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _031_;
endmodule
