#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Dict, List


_ITEM_META_RE = re.compile(r'^- ([a-zA-Z0-9_]+): `(.*)`$')


def _strip_ticks(value: str) -> str:
    value = value.strip()
    if value.startswith('`') and value.endswith('`') and len(value) >= 2:
        return value[1:-1]
    return value


def _read_backlog_item(path: Path, repo_root: Path) -> Dict[str, str] | None:
    text = path.read_text(encoding='utf-8', errors='ignore')
    title = ''
    item_id = ''
    metadata: Dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not title and line.startswith('# '):
            title = line[2:].strip()
            continue
        match = _ITEM_META_RE.match(line)
        if match:
            key, value = match.groups()
            metadata[key] = value.strip()
            if key == 'item_id':
                item_id = value.strip()
        elif metadata and line.startswith('## '):
            break
    item_id = item_id or path.stem
    if not item_id.startswith('item_'):
        return None
    try:
        source_path = str(path.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        source_path = str(path)
    return {
        'item_id': item_id,
        'layer': metadata.get('layer', ''),
        'kind': metadata.get('kind', ''),
        'title': title,
        'status': metadata.get('status', ''),
        'priority': metadata.get('priority', ''),
        'owner': metadata.get('owner', ''),
        'proposal_id': metadata.get('proposal_id', ''),
        'updated_utc': metadata.get('updated_utc', ''),
        'source_path': source_path,
    }


def load_backlog_rows(repo_root: Path) -> List[Dict[str, str]]:
    bases = [
        repo_root / 'docs' / 'development_items' / 'items',
        repo_root / 'docs' / 'backlog' / 'items',
    ]
    by_id: Dict[str, Dict[str, str]] = {}
    for base in bases:
        if not base.exists():
            continue
        for path in sorted(base.glob('item_*.md')):
            row = _read_backlog_item(path, repo_root)
            if row is None:
                continue
            by_id[row['item_id']] = row
    return sorted(by_id.values(), key=lambda row: row['item_id'])


def load_proposal_rows(repo_root: Path) -> List[Dict[str, str]]:
    bases = [
        repo_root / 'docs' / 'developer_loop',
        repo_root / 'docs' / 'proposals',
    ]
    by_id: Dict[str, Dict[str, str]] = {}
    for base in bases:
        if not base.exists():
            continue
        for proposal_dir in sorted(p for p in base.iterdir() if p.is_dir() and p.name != '_template'):
            proposal_json = proposal_dir / 'proposal.json'
            if not proposal_json.exists():
                continue
            proposal = json.loads(proposal_json.read_text())
            decision = ''
            decision_path = proposal_dir / 'promotion_decision.json'
            if decision_path.exists():
                try:
                    decision_payload = json.loads(decision_path.read_text())
                    decision = str(decision_payload.get('decision') or '')
                except json.JSONDecodeError:
                    decision = ''
            proposal_id = str(proposal.get('proposal_id', proposal_dir.name))
            by_id[proposal_id] = {
                'proposal_id': proposal_id,
                'layer': str(proposal.get('layer', '')),
                'kind': str(proposal.get('kind', '')),
                'abstraction_layer': str(proposal.get('abstraction_layer', '')),
                'title': str(proposal.get('title', '')),
                'decision': decision,
                'created_utc': str(proposal.get('created_utc', '')),
                'source_dir': str(proposal_dir.relative_to(repo_root)),
            }
    return sorted(by_id.values(), key=lambda row: row['proposal_id'])


def render_backlog_index(rows: List[Dict[str, str]]) -> str:
    lines = [
        '# Backlog Index',
        '',
        'Canonical source of truth for new intake work lives under `docs/backlog/`.',
        '',
        '| item_id | layer | kind | title | status | priority | proposal_id | source |',
        '|---|---|---|---|---|---|---|---|',
    ]
    for row in rows:
        proposal = row['proposal_id'] or ''
        source = f"`{row['source_path']}`"
        lines.append(
            f"| `{row['item_id']}` | `{row['layer']}` | `{row['kind']}` | {row['title']} | `{row['status']}` | `{row['priority']}` | `{proposal}` | {source} |"
        )
    lines.extend(['', 'This file is generated by `scripts/sync_docs_catalog.py`.'])
    return '\n'.join(lines) + '\n'


def render_proposals_index(rows: List[Dict[str, str]]) -> str:
    lines = [
        '# Proposal Index',
        '',
        'Canonical source of truth for new proposal workspaces lives under `docs/proposals/`.',
        '',
        '| proposal_id | layer | kind | abstraction_layer | title | decision | created_utc | source |',
        '|---|---|---|---|---|---|---|---|',
    ]
    for row in rows:
        source = f"`{row['source_dir']}`"
        lines.append(
            f"| `{row['proposal_id']}` | `{row['layer']}` | `{row['kind']}` | `{row['abstraction_layer']}` | {row['title']} | `{row['decision']}` | `{row['created_utc']}` | {source} |"
        )
    lines.extend(['', 'This file is generated by `scripts/sync_docs_catalog.py`.'])
    return '\n'.join(lines) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate canonical backlog/proposal indexes.')
    parser.add_argument('--repo-root', default='.', help='Repository root path')
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    backlog_rows = load_backlog_rows(repo_root)
    proposal_rows = load_proposal_rows(repo_root)

    (repo_root / 'docs' / 'backlog' / 'index.md').write_text(render_backlog_index(backlog_rows))
    (repo_root / 'docs' / 'proposals' / 'index.md').write_text(render_proposals_index(proposal_rows))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
