/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, clang++ 18.1.8 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "yosys_mult4s_booth_yosys.v:1.1-8.10" *)
module yosys_mult4s_booth(multiplicand, multiplier, product);
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.20-198.21" *)
  wire [7:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.23-198.24" *)
  wire [7:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [7:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [7:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [7:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [7:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [7:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [7:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [7:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [7:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  wire [7:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [7:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:198.26-198.27" *)
  wire [7:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.21-200.22" *)
  (* unused_bits = "7" *)
  wire [7:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:200.24-200.25" *)
  wire [7:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.19-203.21" *)
  wire [7:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.23-203.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:203.27-203.29" *)
  wire [7:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:214.23-214.24" *)
  (* unused_bits = "7" *)
  wire [7:0] _022_;
  wire [4:0] _023_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _024_;
  (* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _025_;
  (* src = "yosys_mult4s_booth_yosys.v:2.22-2.34" *)
  input [3:0] multiplicand;
  wire [3:0] multiplicand;
  (* src = "yosys_mult4s_booth_yosys.v:3.22-3.32" *)
  input [3:0] multiplier;
  wire [3:0] multiplier;
  (* src = "yosys_mult4s_booth_yosys.v:4.23-4.30" *)
  output [7:0] product;
  wire [7:0] product;
  assign _023_[0] = ~(* src = {0{1'b0}} *) multiplicand[0];
  assign _023_[1] = ~(* src = {0{1'b0}} *) multiplicand[1];
  assign _023_[2] = ~(* src = {0{1'b0}} *) multiplicand[2];
  assign _023_[4] = ~(* src = {0{1'b0}} *) multiplicand[3];
  assign _000_[1] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _000_[2] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _001_[3] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[1];
  assign _000_[7] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[1];
  assign product[0] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _001_[1] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _001_[2] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _001_[7] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[0];
  assign _002_[2] = multiplicand[0] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _008_[3] = multiplicand[1] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _002_[4] = multiplicand[2] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _002_[7] = multiplicand[3] &(* src = {0{1'b0}} *)  multiplier[2];
  assign _014_[3] = _023_[0] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _008_[4] = _023_[1] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _008_[5] = _023_[2] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _008_[7] = _023_[4] &(* src = {0{1'b0}} *)  multiplier[3];
  assign _003_[2] = _006_[2] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[2];
  assign _003_[3] = _006_[3] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[3];
  assign _003_[4] = _006_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[4];
  assign _003_[7] = _006_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _007_[7];
  assign _004_[2] = _005_[2] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[2];
  assign _004_[3] = _005_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _001_[7];
  assign _004_[4] = _005_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[4];
  assign _004_[7] = _005_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _002_[7];
  assign _007_[2] = _002_[2] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[2];
  assign _007_[3] = _001_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[3];
  assign _007_[4] = _002_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[7];
  assign _007_[7] = _002_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _005_[7];
  assign _003_[1] = _000_[1] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[1];
  assign _006_[2] = _000_[2] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[2];
  assign _006_[3] = multiplier[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[3];
  assign _006_[7] = _000_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _001_[7];
  assign product[1] = _000_[1] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[1];
  assign _005_[2] = _000_[2] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[2];
  assign _005_[3] = multiplier[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[3];
  assign _005_[7] = _000_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _001_[7];
  assign _009_[3] = _012_[3] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _013_[3];
  assign _009_[4] = _012_[4] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _013_[4];
  assign _009_[5] = _012_[5] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _013_[5];
  assign _009_[7] = _012_[7] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _013_[7];
  assign _010_[3] = _011_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _008_[3];
  assign _010_[4] = _011_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _008_[4];
  assign _010_[5] = _011_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _008_[5];
  assign _010_[7] = _011_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _008_[7];
  assign _013_[3] = _008_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _011_[3];
  assign _013_[4] = _008_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _011_[4];
  assign _013_[5] = _008_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _011_[5];
  assign _013_[7] = _008_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _011_[7];
  assign _009_[2] = _004_[2] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _003_[1];
  assign _012_[3] = _004_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _003_[2];
  assign _012_[4] = _004_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _003_[3];
  assign _012_[5] = _004_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _003_[4];
  assign _012_[7] = _004_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _003_[7];
  assign product[2] = _004_[2] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _003_[1];
  assign _011_[3] = _004_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _003_[2];
  assign _011_[4] = _004_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _003_[3];
  assign _011_[5] = _004_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _003_[4];
  assign _011_[7] = _004_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _003_[7];
  assign _015_[3] = _018_[3] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.25-206.32" *)  _019_[3];
  assign product[3] = _017_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:206.13-206.19" *)  _014_[3];
  assign _019_[3] = _014_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.38-205.44" *)  _017_[3];
  assign _018_[3] = _010_[3] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[2];
  assign _015_[4] = _010_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[3];
  assign _015_[5] = _010_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[4];
  assign _015_[6] = _010_[7] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.26-205.31" *)  _009_[5];
  assign _017_[3] = _010_[3] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[2];
  assign _016_[4] = _010_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[3];
  assign _016_[5] = _010_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[4];
  assign _016_[6] = _010_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[5];
  assign _016_[7] = _010_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:205.14-205.19" *)  _009_[7];
  assign product[5] = _021_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _020_[4];
  assign product[6] = _021_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _020_[5];
  assign product[7] = _021_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  _020_[6];
  assign product[4] = _016_[4] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _015_[3];
  assign _021_[5] = _016_[5] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _015_[4];
  assign _021_[6] = _016_[6] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _015_[5];
  assign _021_[7] = _016_[7] ^(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:288.13-288.20" *)  _015_[6];
  assign _020_[4] = _016_[4] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _015_[3];
  assign _022_[5] = _016_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _015_[4];
  assign _022_[6] = _016_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.42-286.49" *)  _015_[5];
  assign _024_ = _021_[5] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)  _020_[4];
  assign _025_ = _021_[6] &(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)  _020_[5];
  assign _020_[5] = _022_[5] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)  _024_;
  assign _020_[6] = _022_[6] |(* src = "/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/oss-cad-suite/lib/../share/yosys/techmap.v:248.12-248.41" *)  _025_;
  assign { _000_[6:3], _000_[0] } = { _000_[7], _000_[7], _000_[7], multiplier[3], 1'h0 };
  assign { _001_[6:4], _001_[0] } = { _001_[7], _001_[7], _001_[7], product[0] };
  assign { _002_[6:5], _002_[3], _002_[1:0] } = { _002_[7], _002_[7], _001_[7], 2'h0 };
  assign { _003_[6:5], _003_[0] } = { _003_[7], _003_[7], 1'h0 };
  assign { _004_[6:5], _004_[1:0] } = { _004_[7], _004_[7], product[1:0] };
  assign { _005_[6:4], _005_[1:0] } = { _005_[7], _005_[7], _005_[7], product[1:0] };
  assign { _006_[6:4], _006_[1:0] } = { _006_[7], _006_[7], _006_[7], _003_[1], 1'h0 };
  assign { _007_[6:5], _007_[1:0] } = { _007_[7], _007_[7], 2'h0 };
  assign { _008_[6], _008_[2:0] } = { _008_[7], 3'h0 };
  assign { _009_[6], _009_[1:0] } = { _009_[7], 2'h0 };
  assign { _010_[6], _010_[2:0] } = { _010_[7], product[2:0] };
  assign { _011_[6], _011_[2:0] } = { _011_[7], product[2:0] };
  assign { _012_[6], _012_[2:0] } = { _012_[7], _009_[2], 2'h0 };
  assign { _013_[6], _013_[2:0] } = { _013_[7], 3'h0 };
  assign { _014_[7:4], _014_[2:0] } = 7'h00;
  assign _015_[2:0] = 3'h0;
  assign _016_[3:0] = product[3:0];
  assign { _017_[7:4], _017_[2:0] } = { _016_[7:4], product[2:0] };
  assign { _018_[7:4], _018_[2:0] } = { _015_[7:4], 3'h0 };
  assign { _019_[7:4], _019_[2:0] } = 7'h00;
  assign _020_[3:0] = 4'h0;
  assign _021_[4:0] = product[4:0];
  assign _022_[4:0] = { _020_[4], 4'h0 };
  assign _023_[3] = _023_[4];
endmodule
